from .base_config import OPERATOR_CODES, TEST_NAME_CODES
from .config_dns import DNS_RENAME_MAP, DNS_SCHEMA_GROUP, DNS_TEST_NAME_TO_GROUP
from .config_egaming import EGAMING_RENAME_MAP, EGAMING_SCHEMA_GROUPS, EGAMING_TEST_NAME_TO_GROUP
from .config_http import HTTP_RENAME_MAP, HTTP_SCHEMA_GROUPS, HTTP_TEST_NAME_TO_GROUP
from .config_ping import PING_RENAME_MAP, PING_SCHEMA_GROUPS, PING_TEST_NAME_TO_GROUP
from .config_streaming import STREAMING_RENAME_MAP, STREAMING_SCHEMA_GROUPS, STREAMING_TEST_NAME_TO_GROUP
from .config_videochat import VIDEOCHAT_RENAME_MAP, VIDEOCHAT_SCHEMA_GROUPS, VIDEOCHAT_TEST_NAME_TO_GROUP
from .config_mos_m2m import MOS_M2M_RENAME_MAP, MOS_M2M_SCHEMA_GROUPS
from .config_mos_ott import MOS_OTT_RENAME_MAP, MOS_OTT_SCHEMA_GROUPS
from .config_voice_m2m import VOICE_M2M_RENAME_MAP, VOICE_M2M_SCHEMA_GROUPS
from .config_voice_ott import VOICE_OTT_RENAME_MAP, VOICE_OTT_SCHEMA_GROUPS

__all__ = [
    "DNS_RENAME_MAP",
    "DNS_SCHEMA_GROUP",
    "DNS_TEST_NAME_TO_GROUP",
    "OPERATOR_CODES",
    "TEST_NAME_CODES",
    "EGAMING_SCHEMA_GROUPS",
    "EGAMING_TEST_NAME_TO_GROUP",
    "EGAMING_RENAME_MAP",
    "HTTP_RENAME_MAP",
    "HTTP_SCHEMA_GROUPS",
    "HTTP_TEST_NAME_TO_GROUP",
    "STREAMING_RENAME_MAP",
    "STREAMING_SCHEMA_GROUPS",
    "STREAMING_TEST_NAME_TO_GROUP",
    "VIDEOCHAT_RENAME_MAP",
    "VIDEOCHAT_SCHEMA_GROUPS",
    "VIDEOCHAT_TEST_NAME_TO_GROUP",
    "MOS_M2M_SCHEMA_GROUPS",
    "MOS_M2M_RENAME_MAP",
    "MOS_OTT_RENAME_MAP",
    "MOS_OTT_SCHEMA_GROUPS",
    "PING_RENAME_MAP",
    "PING_SCHEMA_GROUPS",
    "PING_TEST_NAME_TO_GROUP",
    "VOICE_M2M_SCHEMA_GROUPS",
    "VOICE_M2M_RENAME_MAP",
    "VOICE_OTT_SCHEMA_GROUPS",
    "VOICE_OTT_RENAME_MAP"
]
