from base_config import OPERATOR_CODES, TEST_NAME_CODES
from .config_dns import (
    DNS_RENAME_MAP,
    DNS_SCHEMA_GROUP,
    DNS_TEST_NAME_TO_GROUP
)
from .config_egaming import EGAMING_SCHEMA_GROUPS, EGAMING_TEST_NAME_TO_GROUP, EGAMING_RENAME_MAP

__all__ = [
    "DNS_RENAME_MAP",
    "DNS_SCHEMA_GROUP",
    "DNS_TEST_NAME_TO_GROUP",
    "OPERATOR_CODES",
    "TEST_NAME_CODES",
    "EGAMING_SCHEMA_GROUPS",
    "EGAMING_TEST_NAME_TO_GROUP",
    "EGAMING_RENAME_MAP",
]
