DNS_RENAME_MAP = {
    "Date Time": "Date",
    "Time": "Time",
    "Test_Name_2": "Test Name",
    "Type Mobility": "Type of Mobility",
    "Longitude": "Longitude",
    "Latitude": "Latitude",
    "Operator": "Operator",
    "Country": "Route Name",
    "Sequence": "Sequence",
    "MNC": "MNC",
    "Technology_Detail": "Session Start Technology",
    "HttpDataRadioBearer": "Session Start Data Radio Bearer",
    "HTTP_URL": "HTTP URL",
    "DNS_Client": "DNS Client",
    "DNS_Domain_Name": "DNS Domain Name",
    "DNS_Server_Address": "DNS Server Address",
    "DNS_Resolved_Address": "DNS Resolved Address",
    "First DNS Request": "First DNS Request",
    "DNS_First_In_Session": "DNS First In Session",
    "DNS_Host_Name_Resolution_Failure_Ratio": "DNS Host Name Resolution Failure Ratio",
    "DNS_Host_Name_Resolution_Time_sec": "DNS Host Name Resolution Time (sec)",
    "DNS_Host_Name_Total_Resolution_Time_sec": "DNS Host Name Total Resolution Time (sec)",
    "DNS Resolution Success Ratio (%)": "DNS Resolution Success Ratio (%)",
    "TAC": "Session Start TAC",
    "HttpLogfileName": "Logfile Name",
    "HttpImsi": "IMSI",
    "HttpStartTime": "Session Start Time",
    "HttpStartLatitude": "Session Start Latitude",
    "HttpStartLongitude": "Session Start Longitude",
    "HttpStartMultiRATConnectivityMode": "Session Start MultiRAT",
    "First_DNS_Request_to_HTTP_Get_First_Chunk_Downloaded_ms": "First DNS Request to HTTP Get First Chunk Downloaded (ms)",
    "First_DNS_Request_to_HTTP_Post_First_Chunk_Uploaded_ms": "First DNS Request to HTTP Post First Chunk Uploaded (ms)",
    "Seconds_Start_to_End_HTTP": "Seconds Start to End HTTP",
    "HttpEndTime": "Session End Time",
    "HttpEndMultiRATConnectivityMode": "Session End MultiRAT",
    "HttpEndLatitude": "Session End Latitude",
    "HttpEndLongitude": "Session End Longitude",
    "FirmwareVersion": "FirmwareVersion",
}

DNS_TEST_NAME_TO_GROUP = {
    "DNS": "DNS1",
}


DNS_SCHEMA_GROUP = {
    "DNS1": [
        "Date",
        "Time",
        "Test Name",
        "Sequence",
        "Logfile Name",
        "Longitude",
        "Latitude",
        "Route Name",
        "Operator",
        "Type of Mobility",
        "Session Start Time",
        "Session Start Latitude",
        "Session Start Longitude",
        "Session Start Technology",
        "Session Start Data Radio Bearer",
        "Session Start MultiRAT",
        "Session Start TAC",
        "DNS Client",
        "DNS Domain Name",
        "DNS Server Address",
        "DNS Resolved Address",
        "First DNS Request",
        "DNS First In Session",
        "DNS Host Name Resolution Failure Ratio",
        "DNS Host Name Resolution Time (sec)",
        "DNS Host Name Total Resolution Time (sec)",
        "DNS Resolution Success Ratio (%)",
        "First DNS Request to HTTP Get First Chunk Downloaded (ms)",
        "First DNS Request to HTTP Post First Chunk Uploaded (ms)",
        "Seconds Start to End HTTP",
        "Session End Time",
        "Session End MultiRAT",
        "Session End Longitude",
        "HTTP URL",
        "FirmwareVersion",
    ]
}
