VOICE_M2M_RENAME_MAP = {
    "VoiceStartTime": "VoiceStartTime Side A",
    "VoiceEndTime": "VoiceEndTime Side A",
    "Test Name": "Test Name",
    "Type Mobility": "Type of Mobility",
    "Side": "Side A",
    "DeviceDescription": "DeviceDescription Side A",
    "Operator": "Operator",
    "Country": "Route Name",
    "Sequence": "Sequence A",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "VoiceLogfileName": "Logfile Name Side A",
    "EventName": "Event Name Side A",
    "IMEI": "IMEI Side A",
    "IMSI": "IMSI Side A",
    "MCC": "MCC",
    "MNC": "MNC",
    "TAC": "TAC A",
    "Technology_Detail": "Technology Detail Side A",
    "PhoneNumber": "Phone Number Side A",
    "Dialed Number": "Dialed Number Side A",
    "Call_Status": "Call Status Side A",
    "Call_Type": "Call Type Side A",
    "Call_Number": "Call Number Side A",
    "MO_Call_Domain": "MO Call Domain Side A",
    "MO_Call_Setup_Time_ms": "MO Call Setup Time (ms) Side A",
    "MO_Call_User_Setup_Time_ms": "MO Call User Setup Time (ms) Side A",
    "MOCallDropRate": "MO Call Drop Rate Side A",
    "MOCallSetupFailureRate": "MO Call Setup Failure Rate Side A",
    "MT_Call_Domain": "MT Call Domain Side A",
    "MT_Call_Setup_Time_ms": "MT Call Setup Time (ms) Side A",
    "MT_Call_User_Setup_Time_ms": "MT Call User Setup Time (ms) Side A",
    "MTCallDropRate": "MT Call Drop Rate Side A",
    "MTCallSetupFailureRate": "MT Call Setup Failure Rate Side A",
    "Call_Duration": "Call Duration Side A",
    "Call_Setup_Duration": "Call Setup Duration Side A",
    "Call_Setup_Time_sec": "Call Setup Time (sec) Side A",
    "Voice_Call_Setup_Time_sec": "Voice Call Setup Time (sec) Side A",
    "Voice_Call_Success_Rate": "Voice Call Success Rate Side A",
    "Voice_Call_Setup_Success_Rate": "Voice Call Setup Success Rate Side A",
    "Voice_Call_Setup_Failure_Rate": "Voice Call Setup Failure Rate Side A",
    "Voice_Call_Completion_Rate": "Voice Call Completion Rate Side A",
    "Voice_Dropped_Call_Rate": "Voice Dropped Call Rate Side A",
    "Voice_Speech_Quality_On_Call_Basis": "Voice Speech Quality On Call Basis Side A",
    "Call Drop Rate": "Call Drop Rate Side A",
    "Call Dropped Count": "Call Dropped Count Side A",
    "Call Dropped VoLTE Count": "Call Dropped VoLTE Count Side A",
    "Call Block Rate": "Call Block Rate Side A",
    "Call Blocked Count": "Call Blocked Count Side A",
    "Call Blocked VoLTE Count": "Call Blocked VoLTE Count Side A",
    "Call Success Count": "Call Success Count Side A",
    "Call Success Rate": "Call Success Rate Side A",
    "Call Success VoLTE Count": "Call Success VoLTE Count Side A",
    "Call Initiation": "Call Initiation Side A",
    "Call Attempt": "Call Attempt Side A",
    "Call Attempt Retry": "Call Attempt Retry Side A",
    "Call Setup": "Call Setup Side A",
    "Call Established": "Call Established Side A",
    "Call End": "Call End Side A",
    "Call_End_Initiator": "Call End Initiator Side A",
    "CallInitiationDelay": "Call Initiation Delay Side A",
    "CallInitiationFailureRate": "Call Initiation Failure Rate Side A",
    "CallInitiationSuccessRate": "Call Initiation Success Rate Side A",
    "Data Radio Bearer": "Data Radio Bearer Side A",
    "Multi RAT Connectivity Mode": "Multi RAT Connectivity Mode Side A",
    "RadioAccessTechnologyState": "Radio Side Access Technology State Side A",
    "Is_Multi_RAB": "Is Multi RAB Side A",
    "AQM_RAT": "AQM RAT Side A",
    "AQM Algorithm DL": "AQM Algorithm DL Side A",
    "AQM Audio Channel Type DL": "AQM Audio Channel Type DL Side A",
    "AQM Score": "AQM Score Side A",
    "AQM Score DL": "AQM Score DL Side A",
    "MOS Calculator Version Downlink": "MOS Calculator Version Downlink Side A",
    "Speech Codec": "Speech Codec Side A",
    "AMR_Codec_DL": "AMR Codec DL Side A",
    "AMR_Codec_UL": "AMR Codec UL Side A",
    "AMR Codec Name DL Top #1": "AMR Codec Name DL Top #1 Side A",
    "AMR Codec Usage DL Top #1": "AMR Codec Usage DL Top #1 Side A",
    "AMR Codec Name UL Top #1": "AMR Codec Name UL Top #1 Side A",
    "AMR Codec Usage UL Top #1": "AMR Codec Usage UL Top #1 Side A",
    "SQ_MOS": "SQ MOS Side A",
    "MOS Calculator Version Downlink": "MOS Calculator Version Downlink Side A",
    "AMR_Codec_DL": "AMR Codec DL Side A",
    "AMR_Codec_UL": "AMR Codec UL Side A",
    "MultiRABServiceType1": "Multi RAB Service Type 1 Side A",
    "MultiRABServiceType2": "Multi RAB Service Type 2 Side A",
    "AQMDownlinkCallQuality": "AQM Downlink Call Quality Side A",
    "AverageAQMDownlinkCallQuality": "Average Side AQM Downlink Call Quality Side A",
    "POLQA SWB Score DL": "POLQA SWB Score DL Side A",
    "POLQA Speech Codec": "POLQA Speech Codec Side A",
    "RTP Jitter Audio RFC3550 (ms)": "RTP Jitter Audio RFC3550 (ms) Side A",
    "RTP Lost Packets Rate Audio (%)": "RTP Lost Packets Rate Audio (%) Side A",
    "RTP Relative Packet Delay Audio (ms)": "RTP Relative Packet Delay Audio (ms) Side A",
    "CodecUsed": "Codec Used Side A",
    "ConsecutivePacketsLost": "Consecutive Packets Lost Side A",
    "FERCombinedPacketLoss": "FER Combined Packet Loss Side A",
    "InterarrivalJitter": "Inter Side Arrival Jitter Side A",
    "JitterBufferSizeIncrease": "Jitter Buffer Size Increase Side A",
    "JitterBufferUnderruns": "Jitter Buffer Under runs Side A",
    "MOSequenceNumberReceived": "MO Sequence Number Received Side A",
    "MOSequenceNumberSent": "MO Sequence Number Sent Side A",
    "NumberOfPacketsLost": "Number Of Packets Lost Side A",
    "PacketInterarrivalTime": "Packet Interarrival Time Side A",
    "PacketLossRatio": "Packet Loss Ratio Side A",
    "PayloadTypeAudio": "Payload Type Audio Side A",
    "RTPTimeGap": "RTP Time Gap Side A",
    "Is CSFB Call Attempt": "Is CSFB Call Attempt",
    "Call Attempt CSFB": "Call Attempt CSFB",
    "MO CSFB Call Abnormal Release": "MO CSFB Call Abnormal Release Side A",
    "MO CSFB Call Attempt": "MO CSFB Call Attempt Side A",
    "MO CSFB Call Dropped": "MO CSFB Call Dropped Side A",
    "MO CSFB Call MS Release (Normal Cause)": "MO CSFB Call MS Release (Normal Cause) Side A",
    "MO CSFB Call NW Release (Normal Cause)": "MO CSFB Call NW Release (Normal Cause) Side A",
    "MO CSFB Call On-Call @ EOF": "MO CSFB Call On-Call @ EOF Side A",
    "MO CSFB Call Setup Failure": "MO CSFB Call Setup Failure Side A",
    "MO CSFB Call Setup Failure - No Alerting": "MO CSFB Call Setup Failure - No Alerting Side A",
    "MO CSFB Call Setup Rejected": "MO CSFB Call Setup Rejected Side A",
    "MO CSFB Call Setup Success": "MO CSFB Call Setup Success Side A",
    "MT CSFB Call Abnormal Release": "MT CSFB Call Abnormal Release Side A",
    "MT CSFB Call Attempt": "MT CSFB Call Attempt Side A",
    "MT CSFB Call Dropped": "MT CSFB Call Dropped Side A",
    "MT CSFB Call MS Release (Normal Cause)": "MT CSFB Call MS Release (Normal Cause) Side A",
    "MT CSFB Call NW Release (Normal Cause)": "MT CSFB Call NW Release (Normal Cause) Side A",
    "MT CSFB Call On-Call @ EOF": "MT CSFB Call On-Call @ EOF Side A",
    "MT CSFB Call Setup Failure": "MT CSFB Call Setup Failure Side A",
    "MT CSFB Call Setup Rejected": "MT CSFB Call Setup Rejected Side A",
    "MT CSFB Call Setup Success": "MT CSFB Call Setup Success Side A",
    "LTE_MO_CSFB_Setup_Delay_ms": "LTE MO CSFB Setup Delay ms Side A",
    "LTE_MT_CSFB_Setup_Delay_ms": "LTE MT CSFB Setup Delay ms Side A",
    "LTE_PS_Data_Interrupt_Time_Due_to_CSFB_ms": "LTE PS Data Interrupt Time Due to CSFB ms Side A",
    "CSFB_Call_Setup_Time_sec": "CSFB Call Setup Time sec Side A",
    "MO_CSFB_Call_Setup_Time_ms": "MO CSFB Call Setup Time ms Side A",
    "MO_CSFB_Call_User_Setup_Time_ms": "MO CSFB Call User Setup Time ms Side A",
    "MT_CSFB_Call_Setup_Time_ms": "MT CSFB Call Setup Time ms Side A",
    "Reselection_Time_After_CSFB_Call_Idle_to_LTE_ms": "Reselection Time After CSFB Call Idle to LTE ms Side A",
    "Reselection_Time_After_CSFB_Call_SIB19_to_LTE": "Reselection Time After CSFB Call SIB19 to LTE Side A",
    "Voice_CSFB_Setup_Failure_Rate": "Voice CSFB Setup Failure Rate Side A",
    "Voice_CSFB_Setup_Success_Rate": "Voice CSFB Setup Success Rate Side A",
    "Call Attempt EPSFB": "Call Attempt EPSFB Side A",
    "Call Blocked EPSFB": "Call Blocked EPSFB Side A",
    "Call Established EPSFB": "Call Established EPSFB Side A",
    "Call Setup EPSFB": "Call Setup EPSFB Side A",
    "SRVCC_Handover_Interruption_Time_Control_Plane": "SRVCC Handover Interruption Time Control Plane Side A",
    "Reselection_Time_After_SRVCC_Call_Idle_to_LTE": "Reselection Time After SRVCC Call Idle to LTE Side A",
    "Reselection_Time_After_SRVCC_Call_SIB19_to_LTE": "Reselection Time After SRVCC Call SIB19 to LTE Side A",
    "SRVCC Handover": "SRVCC Handover Side A",
    "SRVCC Handover (During On-going Call)": "SRVCC Handover (During On-going Call) Side A",
    "SRVCC Handover (During Setup)": "SRVCC Handover (During Setup) Side A",
    "SRVCC Handover Failure": "SRVCC Handover Failure Side A",
    "SRVCCHandoverInterruptionTimeUserPlane": "SRVCC Handover Interruption Time User Plane Side A",
    "SRVCCUserPlaneDelay": "SRVCC User Plane Delay Side A",
    "SRVCCUserPlaneInterruptionTime": "SRVCC User Plane Interruption Time Side A",
    "LTE Cell Identity(eNB Part)": "LTE Cell Identity(eNB Part) Side A",
    "LTE Cell Identity(Cell Part)": "LTE Cell Identity(Cell Part) Side A",
    "LTE Serving Cell Identity": "LTE Serving Cell Identity Side A",
    "LTE Serving Cell DL EARFCN": "LTE Serving Cell DL EARFCN Side A",
    "LTE Serving Cell Frequency Band": "LTE Serving Cell Frequency Band Side A",
    "LTE Serving Cell Channel RSSI(dBm)": "LTE Serving Cell Channel RSSI(dBm) Side A",
    "LTE Serving Cell RSRP(dBm)": "LTE Serving Cell RSRP(dBm) Side A",
    "LTE Serving Cell RS SINR(dB)": "LTE Serving Cell RS SINR(dB) Side A",
    "LTE Serving Cell RSRQ (dB)": "LTE Serving Cell RSRQ (dB) Side A",
    "LTE_Serving_Cell_Count_Average": "LTE Serving Cell Count Side Average Side A",
    "LTE Secondary Serving Cell 1 Identity": "LTE Secondary Serving Cell 1 Identity Side A",
    "LTE Secondary Serving Cell 1 DL EARFCN": "LTE Secondary Serving Cell 1 DL EARFCN Side A",
    "LTE Secondary Serving Cell 1 Frequency Band": "LTE Secondary Serving Cell 1 Frequency Band Side A",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)": "LTE Secondary Serving Cell 1 Channel RSSI (dBm) Side A",
    "LTE Secondary Serving Cell 1 RSRP (dBm)": "LTE Secondary Serving Cell 1 RSRP (dBm) Side A",
    "LTE Secondary Serving Cell 1 RS SINR (dB)": "LTE Secondary Serving Cell 1 RS SINR (dB) Side A",
    "LTE Secondary Serving Cell 1 RSRQ (dB)": "LTE Secondary Serving Cell 1 RSRQ (dB) Side A",
    "LTE Neighbor Cell 1 PCI": "LTE Neighbor Cell 1 PCI Side A",
    "LTE Neighbor Cell 1 DL EARFCN": "LTE Neighbor Cell 1 DL EARFCN Side A",
    "LTE Neighbor Cell 1 RSRP": "LTE Neighbor Cell 1 RSRP Side A",
    "LTE Neighbor Cell 1 RSRQ": "LTE Neighbor Cell 1 RSRQ Side A",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)": "LTE Serving Cell DL Pathloss Carrier 1 (dB) Side A",
    "LTE MAC DL Throughput (kbps)": "LTE MAC DL Throughput (kbps) Side A",
    "LTE MAC DL Throughput Carrier 1 (kbps)": "LTE MAC DL Throughput Carrier 1 (kbps) Side A",
    "LTE MAC DL Throughput Carrier 2 (kbps)": "LTE MAC DL Throughput Carrier 2 (kbps) Side A",
    "LTE MAC DL Throughput Carrier 3 (kbps)": "LTE MAC DL Throughput Carrier 3 (kbps) Side A",
    "LTE MAC DL Throughput Carrier 4 (kbps)": "LTE MAC DL Throughput Carrier 4 (kbps) Side A",
    "LTE MAC UL Throughput (kbps)": "LTE MAC UL Throughput (kbps) Side A",
    "LTE MAC UL Throughput Carrier 1 (kbps)": "LTE MAC UL Throughput Carrier 1 (kbps) Side A",
    "LTE MAC UL Throughput Carrier 2 (kbps)": "LTE MAC UL Throughput Carrier 2 (kbps) Side A",
    "LTE MAC UL Throughput Carrier 3 (kbps)": "LTE MAC UL Throughput Carrier 3 (kbps) Side A",
    "LTE MAC UL Throughput Carrier 4 (kbps)": "LTE MAC UL Throughput Carrier 4 (kbps) Side A",
    "LTE PDSCH Modulation": "LTE PDSCH Modulation Side A",
    "LTE PDSCH MCS": "LTE PDSCH MCS Side A",
    "LTE PDSCH BLER (%)": "LTE PDSCH BLER (%) Side A",
    "LTE PDSCH Phy Throughput (kbps)": "LTE PDSCH Phy Throughput (kbps) Side A",
    "LTE PDSCH Phy Throughput Total (kbps)": "LTE PDSCH Phy Throughput Total (kbps) Side A",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)": "LTE PDSCH Phy Throughput Carrier 1 (kbps) Side A",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)": "LTE PDSCH Phy Throughput Carrier 2 (kbps) Side A",
    "LTE PUSCH Modulation ": "LTE PUSCH Modulation Side A",
    "LTE PUSCH MCS ": "LTE PUSCH MCS Side A",
    "PUSCH BLER (%)": "PUSCH BLER (%) Side A",
    "LTE UE TX Power - PUSCH (dBm) Carrier 1": "LTE UE TX Power - PUSCH (dBm) Carrier 1 Side A",
    "LTE UE TX Power - PUCCH (dBm) Carrier 1": "LTE UE TX Power - PUCCH (dBm) Carrier 1 Side A",
    "LTE PUSCH Phy Throughput (kbps)": "LTE PUSCH Phy Throughput (kbps) Side A",
    "LTE PUSCH Phy Throughput Total (kbps)": "LTE PUSCH Phy Throughput Total (kbps) Side A",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)": "LTE PUSCH Phy Throughput Carrier 1 (kbps) Side A",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)": "LTE PUSCH Phy Throughput Carrier 2 (kbps) Side A",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)": "LTE PUSCH Phy Throughput Carrier 3 (kbps) Side A",
    "PUSCH Phy Throughput Carrier 4 (kbps)": "PUSCH Phy Throughput Carrier 4 (kbps) Side A",
    "LTE RLC Throughput DL (Kbps)": "LTE RLC Throughput DL (Kbps) Side A",
    "LTE RLC Throughput UL (Kbps)": "LTE RLC Throughput UL (Kbps) Side A",
    "LTE Bearer Maximum Bitrate DL (kbit/s)": "LTE Bearer Maximum Bitrate DL (kbit/s) Side A",
    "LTE PDN Connection AMBR DL (kbps)": "LTE PDN Connection Side AMBR DL (kbps) Side A",
    "NR Serving Beam 1 Cell Identity": "NR Serving Beam 1 Cell Identity Side A",
    "NR Serving Beam 1 NRARFCN DL": "NR Serving Beam 1 NRARFCN DL Side A",
    "NR Serving Beam 1 Band": "NR Serving Beam 1 Band Side A",
    "NR Serving Beam 1 Bandwidth DL": "NR Serving Beam 1 Bandwidth DL Side A",
    "NR Serving Beam 1 Bandwidth UL": "NR Serving Beam 1 Bandwidth UL Side A",
    "NR Serving Beam 1 SSB Index": "NR Serving Beam 1 SSB Index Side A",
    "NR Serving Beam 1 Cell Type": "NR Serving Beam 1 Cell Type Side A",
    "NR Serving Beam 2 Cell Identity": "NR Serving Beam 2 Cell Identity Side A",
    "NR Serving Beam 2 NRARFCN DL": "NR Serving Beam 2 NRARFCN DL Side A",
    "NR Serving Beam 2 Band": "NR Serving Beam 2 Band Side A",
    "NR Serving Beam 2 Bandwidth DL": "NR Serving Beam 2 Bandwidth DL Side A",
    "NR Serving Beam 2 Bandwidth UL": "NR Serving Beam 2 Bandwidth UL Side A",
    "NR Serving Beam 2 SSB Index": "NR Serving Beam 2 SSB Index Side A",
    "NR Serving Beam 2 Cell Type": "NR Serving Beam 2 Cell Type Side A",
    "NR Serving Cell Identity Top #1": "NR Serving Cell Identity Top #1 Side A",
    "NR Serving Cell NRARFCN DL Top #1": "NR Serving Cell NRARFCN DL Top #1 Side A",
    "NR Serving Cell SS RSSI Top #1": "NR Serving Cell SS RSSI Top #1 Side A",
    "NR Serving Cell SS RSRP Top #1": "NR Serving Cell SS RSRP Top #1 Side A",
    "NR Serving Cell SS SINR Top #1": "NR Serving Cell SS SINR Top #1 Side A",
    "NR Serving Cell SS RSRQ Top #1": "NR Serving Cell SS RSRQ Top #1 Side A",
    "NR PCell SSB Serving Beam Index Top #1": "NR PCell SSB Serving Beam Index Top #1 Side A",
    "NR Neighbor Cell 1 Cell Identity": "NR Neighbor Cell 1 Cell Identity Side A",
    "NR Neighbor Cell 1 NRARFCN": "NR Neighbor Cell 1 NRARFCN Side A",
    "NR Neighbor Cell 1 SS RSRP (dBm)": "NR Neighbor Cell 1 SS RSRP (dBm) Side A",
    "NR Neighbor Cell 1 SS SINR (dB)": "NR Neighbor Cell 1 SS SINR (dB) Side A",
    "NR Neighbor Cell 1 SS RSRQ (dB)": "NR Neighbor Cell 1 SS RSRQ (dB) Side A",
    "NR Neighbor Cell 1 Best Beam Index": "NR Neighbor Cell 1 Best Beam Index Side A",
    "NR Neighbor Cell 1 Cell Type": "NR Neighbor Cell 1 Cell Type Side A",
    "NR Phy Throughput Multi-RAT DL (kbps)": "NR Phy Throughput Multi-RAT DL (kbps) Side A",
    "NR Phy Throughput Multi-RAT UL (kbps)": "NR Phy Throughput Multi-RAT UL (kbps) Side A",
    "NR PDSCH Phy Throughput Total (Kbps)": "NR PDSCH Phy Throughput Total (Kbps) Side A",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)": "NR Pcell PDSCH Scheduled Throughput (Mbps) Side A",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 1 (Kbps) Side A",
    "NR PDSCH Modulation Serving Beam 1": "NR PDSCH Modulation Serving Beam 1 Side A",
    "NR PDSCH MCS Serving Beam 1": "NR PDSCH MCS Serving Beam 1 Side A",
    "NR PDSCH BLER (%) Serving Beam 1": "NR PDSCH BLER (%) Serving Beam 1 Side A",
    "NR PDSCH CQI Serving Beam 1": "NR PDSCH CQI Serving Beam 1 Side A",
    "NR PDSCH RI Serving Beam 1": "NR PDSCH RI Serving Beam 1 Side A",
    "NR DL Pathloss Serving Beam 1": "NR DL Pathloss Serving Beam 1 Side A",
    "NR PUCCH Tx Power Serving Beam 1 (dBm) ": "NR PUCCH Tx Power Serving Beam 1 (dBm) Side A",
    "NR PUSCH Tx Power Serving Beam 1 (dBm) ": "NR PUSCH Tx Power Serving Beam 1 (dBm) Side A",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 2 (Kbps) Side A",
    "NR PDSCH Modulation Serving Beam 2": "NR PDSCH Modulation Serving Beam 2 Side A",
    "NR PDSCH MCS Serving Beam 2": "NR PDSCH MCS Serving Beam 2 Side A",
    "NR PDSCH BLER (%) Serving Beam 2": "NR PDSCH BLER (%) Serving Beam 2 Side A",
    "NR PDSCH CQI Serving Beam 2": "NR PDSCH CQI Serving Beam 2 Side A",
    "NR PDSCH RI Serving Beam 2": "NR PDSCH RI Serving Beam 2 Side A",
    "NR DL Pathloss Serving Beam 2": "NR DL Pathloss Serving Beam 2 Side A",
    "NR PUSCH Phy Throughput Total (kbps)": "NR PUSCH Phy Throughput Total (kbps) Side A",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)": "NR Pcell PUSCH Scheduled Throughput (Mbps) Side A",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 1 (Kbps) Side A",
    "NR PUSCH Modulation Serving Beam 1": "NR PUSCH Modulation Serving Beam 1 Side A",
    "NR PUSCH MCS Serving Beam 1": "NR PUSCH MCS Serving Beam 1 Side A",
    "NR PUSCH BLER (%) Serving Beam 1": "NR PUSCH BLER (%) Serving Beam 1 Side A",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 2 (Kbps) Side A",
    "NR PUSCH Modulation Serving Beam 2": "NR PUSCH Modulation Serving Beam 2 Side A",
    "NR PUSCH MCS Serving Beam 2": "NR PUSCH MCS Serving Beam 2 Side A",
    "NR PUSCH BLER (%) Serving Beam 2": "NR PUSCH BLER (%) Serving Beam 2 Side A",
    "NR MAC UL Throughput Total (kbps)": "NR MAC UL Throughput Total (kbps) Side A",
    "NR RLC DL Throughput Total (kbps)": "NR RLC DL Throughput Total (kbps) Side A",
    "NR RLC UL Throughput Total (kbps)": "NR RLC UL Throughput Total (kbps) Side A",
    "NR RLC UL Throughput (Kbps)": "NR RLC UL Throughput (Kbps) Side A",
    "RadioAccessTechnologyState": "Radio Side Access Technology State Side A",
    "FirmwareVersion": "FirmwareVersion Side A",
    "Qualifier": "Qualifier Side A",
    "Date": "Date",
    "Time": "Time",
    "VoiceStartTime_B": "VoiceStartTime Side B",
    "VoiceEndTime_B": "VoiceEndTime Side B",
    "Test Name_B": "Test Name Side B",
    "Type Mobility_B": "Type Mobility Side B",
    "Side_B": "Side B",
    "DeviceDescription_B": "DeviceDescription Side B",
    "Operator_B": "Operator Side B",
    "Country_B": "Country Side B",
    "Sequence_B": "Sequence B",
    "Latitude_B": "Start Latitude Side B",
    "Longitude_B": "Start Longitude Side B",
    "VoiceLogfileName_filled_B": "Logfile Name Side B",
    "EventName_B": "Event Name Side B",
    "IMEI_B": "IMEI Side B",
    "IMSI_B": "IMSI Side B",
    "MCC_B": "MCC Side B",
    "MNC_B": "MNC Side B",
    "TAC_B": "TAC Side B",
    "Technology_Detail_B": "Technology Detail Side B",
    "PhoneNumber_B": "Phone Number Side B",
    "Dialed Number_B": "Dialed Number Side B",
    "Call_Status_B": "Call Status Side B",
    "Call_Type_B": "Call Type Side B",
    "Call_Number_B": "Call Number Side B",
    "MO_Call_Domain_B": "MO Call Domain Side B",
    "MO_Call_Setup_Time_ms_B": "MO Call Setup Time (ms) Side B",
    "MO_Call_User_Setup_Time_ms_B": "MO Call User Setup Time (ms) Side B",
    "MOCallDropRate_B": "MO Call Drop Rate Side B",
    "MOCallSetupFailureRate_B": "MO Call Setup Failure Rate Side B",
    "MT_Call_Domain_B": "MT Call Domain Side B",
    "MT_Call_Setup_Time_ms_B": "MT Call Setup Time (ms) Side B",
    "MT_Call_User_Setup_Time_ms_B": "MT Call User Setup Time (ms) Side B",
    "MTCallDropRate_B": "MT Call Drop Rate Side B",
    "MTCallSetupFailureRate_B": "MT Call Setup Failure Rate Side B",
    "Call_Duration_B": "Call Duration Side B",
    "Call_Setup_Duration_B": "Call Setup Duration Side B",
    "Call_Setup_Time_sec_B": "Call Setup Time (sec) Side B",
    "Voice_Call_Setup_Time_sec_B": "Voice Call Setup Time (sec) Side B",
    "Voice_Call_Success_Rate_B": "Voice Call Success Rate Side B",
    "Voice_Call_Setup_Success_Rate_B": "Voice Call Setup Success Rate Side B",
    "Voice_Call_Setup_Failure_Rate_B": "Voice Call Setup Failure Rate Side B",
    "Voice_Call_Completion_Rate_B": "Voice Call Completion Rate Side B",
    "Voice_Dropped_Call_Rate_B": "Voice Dropped Call Rate Side B",
    "Voice_Speech_Quality_On_Call_Basis_B": "Voice Speech Quality On Call Basis Side B",
    "Call Drop Rate_B": "Call Drop Rate Side B",
    "Call Dropped Count_B": "Call Dropped Count Side B",
    "Call Dropped VoLTE Count_B": "Call Dropped VoLTE Count Side B",
    "Call Block Rate_B": "Call Block Rate Side B",
    "Call Blocked Count_B": "Call Blocked Count Side B",
    "Call Blocked VoLTE Count_B": "Call Blocked VoLTE Count Side B",
    "Call Success Count_B": "Call Success Count Side B",
    "Call Success Rate_B": "Call Success Rate Side B",
    "Call Success VoLTE Count_B": "Call Success VoLTE Count Side B",
    "Call Initiation_B": "Call Initiation Side B",
    "Call Attempt_B": "Call Attempt Side B",
    "Call Attempt Retry_B": "Call Attempt Retry Side B",
    "Call Setup_B": "Call Setup Side B",
    "Call Established_B": "Call Established Side B",
    "Call End_B": "Call End Side B",
    "Call_End_Initiator_B": "Call End Initiator Side B",
    "CallInitiationDelay_B": "Call Initiation Delay Side B",
    "CallInitiationFailureRate_B": "Call Initiation Failure Rate Side B",
    "CallInitiationSuccessRate_B": "Call Initiation Success Rate Side B",
    "Data Radio Bearer_B": "Data Radio Bearer Side B",
    "Multi RAT Connectivity Mode_B": "Multi RAT Connectivity Mode Side B",
    "RadioAccessTechnologyState_B": "Radio Side Bccess Technology State Side B",
    "Is_Multi_RAB_B": "Is Multi RAB Side B",
    "AQM_RAT_B": "AQM RAT Side B",
    "AQM Algorithm DL_B": "AQM Algorithm DL Side B",
    "AQM Audio Channel Type DL_B": "AQM Audio Channel Type DL Side B",
    "AQM Score_B": "AQM Score Side B",
    "AQM Score DL_B": "AQM Score DL Side B",
    "MOS Calculator Version Downlink_B": "MOS Calculator Version Downlink Side B",
    "Speech Codec_B": "Speech Codec Side B",
    "AMR_Codec_DL_B": "AMR Codec DL Side B",
    "AMR_Codec_UL_B": "AMR Codec UL Side B",
    "AMR Codec Name DL Top #1_B": "AMR Codec Name DL Top #1 Side B",
    "AMR Codec Usage DL Top #1_B": "AMR Codec Usage DL Top #1 Side B",
    "AMR Codec Name UL Top #1_B": "AMR Codec Name UL Top #1 Side B",
    "AMR Codec Usage UL Top #1_B": "AMR Codec Usage UL Top #1 Side B",
    "SQ_MOS_B": "SQ MOS Side B",
    "MOS Calculator Version Downlink_B": "MOS Calculator Version Downlink Side B",
    "AMR_Codec_DL_B": "AMR Codec DL Side B",
    "AMR_Codec_UL_B": "AMR Codec UL Side B",
    "MultiRABServiceType1_B": "Multi RAB Service Type 1 Side B",
    "MultiRABServiceType2_B": "Multi RAB Service Type 2 Side B",
    "AQMDownlinkCallQuality_B": "AQM Downlink Call Quality Side B",
    "AverageAQMDownlinkCallQuality_B": "Average Side BQM Downlink Call Quality Side B",
    "POLQA SWB Score DL_B": "POLQA SWB Score DL Side B",
    "POLQA Speech Codec_B": "POLQA Speech Codec Side B",
    "RTP Jitter Audio RFC3550 (ms)_B": "RTP Jitter Audio RFC3550 (ms) Side B",
    "RTP Lost Packets Rate Audio (%)_B": "RTP Lost Packets Rate Audio (%) Side B",
    "RTP Relative Packet Delay Audio (ms)_B": "RTP Relative Packet Delay Audio (ms) Side B",
    "CodecUsed_B": "Codec Used Side B",
    "ConsecutivePacketsLost_B": "Consecutive Packets Lost Side B",
    "FERCombinedPacketLoss_B": "FER Combined Packet Loss Side B",
    "InterarrivalJitter_B": "Inter Side Brrival Jitter Side B",
    "JitterBufferSizeIncrease_B": "Jitter Buffer Size Increase Side B",
    "JitterBufferUnderruns_B": "Jitter Buffer Under runs Side B",
    "MOSequenceNumberReceived_B": "MO Sequence Number Received Side B",
    "MOSequenceNumberSent_B": "MO Sequence Number Sent Side B",
    "NumberOfPacketsLost_B": "Number Of Packets Lost Side B",
    "PacketInterarrivalTime_B": "Packet Interarrival Time Side B",
    "PacketLossRatio_B": "Packet Loss Ratio Side B",
    "PayloadTypeAudio_B": "Payload Type Audio Side B",
    "RTPTimeGap_B": "RTP Time Gap Side B",
    "Is CSFB Call Attempt_B": "Is CSFB Call Attempt Side B",
    "Call Attempt CSFB_B": "Call Attempt CSFB Side B",
    "MO CSFB Call Abnormal Release_B": "MO CSFB Call Abnormal Release Side B",
    "MO CSFB Call Attempt_B": "MO CSFB Call Attempt Side B",
    "MO CSFB Call Dropped_B": "MO CSFB Call Dropped Side B",
    "MO CSFB Call MS Release (Normal Cause)_B": "MO CSFB Call MS Release (Normal Cause) Side B",
    "MO CSFB Call NW Release (Normal Cause)_B": "MO CSFB Call NW Release (Normal Cause) Side B",
    "MO CSFB Call On-Call @ EOF_B": "MO CSFB Call On-Call @ EOF Side B",
    "MO CSFB Call Setup Failure_B": "MO CSFB Call Setup Failure Side B",
    "MO CSFB Call Setup Failure - No Alerting_B": "MO CSFB Call Setup Failure - No Alerting Side B",
    "MO CSFB Call Setup Rejected_B": "MO CSFB Call Setup Rejected Side B",
    "MO CSFB Call Setup Success_B": "MO CSFB Call Setup Success Side B",
    "MT CSFB Call Abnormal Release_B": "MT CSFB Call Abnormal Release Side B",
    "MT CSFB Call Attempt_B": "MT CSFB Call Attempt Side B",
    "MT CSFB Call Dropped_B": "MT CSFB Call Dropped Side B",
    "MT CSFB Call MS Release (Normal Cause)_B": "MT CSFB Call MS Release (Normal Cause) Side B",
    "MT CSFB Call NW Release (Normal Cause)_B": "MT CSFB Call NW Release (Normal Cause) Side B",
    "MT CSFB Call On-Call @ EOF_B": "MT CSFB Call On-Call @ EOF Side B",
    "MT CSFB Call Setup Failure_B": "MT CSFB Call Setup Failure Side B",
    "MT CSFB Call Setup Rejected_B": "MT CSFB Call Setup Rejected Side B",
    "MT CSFB Call Setup Success_B": "MT CSFB Call Setup Success Side B",
    "LTE_MO_CSFB_Setup_Delay_ms_B": "LTE MO CSFB Setup Delay ms Side B",
    "LTE_MT_CSFB_Setup_Delay_ms_B": "LTE MT CSFB Setup Delay ms Side B",
    "LTE_PS_Data_Interrupt_Time_Due_to_CSFB_ms_B": "LTE PS Data Interrupt Time Due to CSFB ms Side B",
    "CSFB_Call_Setup_Time_sec_B": "CSFB Call Setup Time sec Side B",
    "MO_CSFB_Call_Setup_Time_ms_B": "MO CSFB Call Setup Time ms Side B",
    "MO_CSFB_Call_User_Setup_Time_ms_B": "MO CSFB Call User Setup Time ms Side B",
    "MT_CSFB_Call_Setup_Time_ms_B": "MT CSFB Call Setup Time ms Side B",
    "Reselection_Time_After_CSFB_Call_Idle_to_LTE_ms_B": "Reselection Time After CSFB Call Idle to LTE ms Side B",
    "Reselection_Time_After_CSFB_Call_SIB19_to_LTE_B": "Reselection Time After CSFB Call SIB19 to LTE Side B",
    "Voice_CSFB_Setup_Failure_Rate_B": "Voice CSFB Setup Failure Rate Side B",
    "Voice_CSFB_Setup_Success_Rate_B": "Voice CSFB Setup Success Rate Side B",
    "Call Attempt EPSFB_B": "Call Attempt EPSFB Side B",
    "Call Blocked EPSFB_B": "Call Blocked EPSFB Side B",
    "Call Established EPSFB_B": "Call Established EPSFB Side B",
    "Call Setup EPSFB_B": "Call Setup EPSFB Side B",
    "SRVCC_Handover_Interruption_Time_Control_Plane_B": "SRVCC Handover Interruption Time Control Plane Side B",
    "Reselection_Time_After_SRVCC_Call_Idle_to_LTE_B": "Reselection Time After SRVCC Call Idle to LTE Side B",
    "Reselection_Time_After_SRVCC_Call_SIB19_to_LTE_B": "Reselection Time After SRVCC Call SIB19 to LTE Side B",
    "SRVCC Handover_B": "SRVCC Handover Side B",
    "SRVCC Handover (During On-going Call)_B": "SRVCC Handover (During On-going Call) Side B",
    "SRVCC Handover (During Setup)_B": "SRVCC Handover (During Setup) Side B",
    "SRVCC Handover Failure_B": "SRVCC Handover Failure Side B",
    "SRVCCHandoverInterruptionTimeUserPlane_B": "SRVCC Handover Interruption Time User Plane Side B",
    "SRVCCUserPlaneDelay_B": "SRVCC User Plane Delay Side B",
    "SRVCCUserPlaneInterruptionTime_B": "SRVCC User Plane Interruption Time Side B",
    "LTE Cell Identity(eNB Part)_B": "LTE Cell Identity(eNB Part) Side B",
    "LTE Cell Identity(Cell Part)_B": "LTE Cell Identity(Cell Part) Side B",
    "LTE Serving Cell Identity_B": "LTE Serving Cell Identity Side B",
    "LTE Serving Cell DL EARFCN_B": "LTE Serving Cell DL EARFCN Side B",
    "LTE Serving Cell Frequency Band_B": "LTE Serving Cell Frequency Band Side B",
    "LTE Serving Cell Channel RSSI(dBm)_B": "LTE Serving Cell Channel RSSI(dBm) Side B",
    "LTE Serving Cell RSRP(dBm)_B": "LTE Serving Cell RSRP(dBm) Side B",
    "LTE Serving Cell RS SINR(dB)_B": "LTE Serving Cell RS SINR(dB) Side B",
    "LTE Serving Cell RSRQ (dB)_B": "LTE Serving Cell RSRQ (dB) Side B",
    "LTE_Serving_Cell_Count_Average_B": "LTE Serving Cell Count Side Bverage Side B",
    "LTE Secondary Serving Cell 1 Identity_B": "LTE Secondary Serving Cell 1 Identity Side B",
    "LTE Secondary Serving Cell 1 DL EARFCN_B": "LTE Secondary Serving Cell 1 DL EARFCN Side B",
    "LTE Secondary Serving Cell 1 Frequency Band_B": "LTE Secondary Serving Cell 1 Frequency Band Side B",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)_B": "LTE Secondary Serving Cell 1 Channel RSSI (dBm) Side B",
    "LTE Secondary Serving Cell 1 RSRP (dBm)_B": "LTE Secondary Serving Cell 1 RSRP (dBm) Side B",
    "LTE Secondary Serving Cell 1 RS SINR (dB)_B": "LTE Secondary Serving Cell 1 RS SINR (dB) Side B",
    "LTE Secondary Serving Cell 1 RSRQ (dB)_B": "LTE Secondary Serving Cell 1 RSRQ (dB) Side B",
    "LTE Neighbor Cell 1 PCI_B": "LTE Neighbor Cell 1 PCI Side B",
    "LTE Neighbor Cell 1 DL EARFCN_B": "LTE Neighbor Cell 1 DL EARFCN Side B",
    "LTE Neighbor Cell 1 RSRP_B": "LTE Neighbor Cell 1 RSRP Side B",
    "LTE Neighbor Cell 1 RSRQ_B": "LTE Neighbor Cell 1 RSRQ Side B",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)_B": "LTE Serving Cell DL Pathloss Carrier 1 (dB) Side B",
    "LTE MAC DL Throughput (kbps)_B": "LTE MAC DL Throughput (kbps) Side B",
    "LTE MAC DL Throughput Carrier 1 (kbps)_B": "LTE MAC DL Throughput Carrier 1 (kbps) Side B",
    "LTE MAC DL Throughput Carrier 2 (kbps)_B": "LTE MAC DL Throughput Carrier 2 (kbps) Side B",
    "LTE MAC DL Throughput Carrier 3 (kbps)_B": "LTE MAC DL Throughput Carrier 3 (kbps) Side B",
    "LTE MAC DL Throughput Carrier 4 (kbps)_B": "LTE MAC DL Throughput Carrier 4 (kbps) Side B",
    "LTE MAC UL Throughput (kbps)_B": "LTE MAC UL Throughput (kbps) Side B",
    "LTE MAC UL Throughput Carrier 1 (kbps)_B": "LTE MAC UL Throughput Carrier 1 (kbps) Side B",
    "LTE MAC UL Throughput Carrier 2 (kbps)_B": "LTE MAC UL Throughput Carrier 2 (kbps) Side B",
    "LTE MAC UL Throughput Carrier 3 (kbps)_B": "LTE MAC UL Throughput Carrier 3 (kbps) Side B",
    "LTE MAC UL Throughput Carrier 4 (kbps)_B": "LTE MAC UL Throughput Carrier 4 (kbps) Side B",
    "LTE PDSCH Modulation_B": "LTE PDSCH Modulation Side B",
    "LTE PDSCH MCS_B": "LTE PDSCH MCS Side B",
    "LTE PDSCH BLER (%)_B": "LTE PDSCH BLER (%) Side B",
    "LTE PDSCH Phy Throughput (kbps)_B": "LTE PDSCH Phy Throughput (kbps) Side B",
    "LTE PDSCH Phy Throughput Total (kbps)_B": "LTE PDSCH Phy Throughput Total (kbps) Side B",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)_B": "LTE PDSCH Phy Throughput Carrier 1 (kbps) Side B",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)_B": "LTE PDSCH Phy Throughput Carrier 2 (kbps) Side B",
    "LTE PUSCH Modulation _B": "LTE PUSCH Modulation Side B",
    "LTE PUSCH MCS _B": "LTE PUSCH MCS Side B",
    "PUSCH BLER (%)_B": "PUSCH BLER (%) Side B",
    "LTE UE TX Power - PUSCH (dBm) Carrier 1_B": "LTE UE TX Power - PUSCH (dBm) Carrier 1 Side B",
    "LTE UE TX Power - PUCCH (dBm) Carrier 1_B": "LTE UE TX Power - PUCCH (dBm) Carrier 1 Side B",
    "LTE PUSCH Phy Throughput (kbps)_B": "LTE PUSCH Phy Throughput (kbps) Side B",
    "LTE PUSCH Phy Throughput Total (kbps)_B": "LTE PUSCH Phy Throughput Total (kbps) Side B",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)_B": "LTE PUSCH Phy Throughput Carrier 1 (kbps) Side B",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)_B": "LTE PUSCH Phy Throughput Carrier 2 (kbps) Side B",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)_B": "LTE PUSCH Phy Throughput Carrier 3 (kbps) Side B",
    "PUSCH Phy Throughput Carrier 4 (kbps)_B": "PUSCH Phy Throughput Carrier 4 (kbps) Side B",
    "LTE RLC Throughput DL (Kbps)_B": "LTE RLC Throughput DL (Kbps) Side B",
    "LTE RLC Throughput UL (Kbps)_B": "LTE RLC Throughput UL (Kbps) Side B",
    "LTE Bearer Maximum Bitrate DL (kbit/s)_B": "LTE Bearer Maximum Bitrate DL (kbit/s) Side B",
    "LTE PDN Connection AMBR DL (kbps)_B": "LTE PDN Connection Side BMBR DL (kbps) Side B",
    "NR Serving Beam 1 Cell Identity_B": "NR Serving Beam 1 Cell Identity Side B",
    "NR Serving Beam 1 NRARFCN DL_B": "NR Serving Beam 1 NRARFCN DL Side B",
    "NR Serving Beam 1 Band_B": "NR Serving Beam 1 Band Side B",
    "NR Serving Beam 1 Bandwidth DL_B": "NR Serving Beam 1 Bandwidth DL Side B",
    "NR Serving Beam 1 Bandwidth UL_B": "NR Serving Beam 1 Bandwidth UL Side B",
    "NR Serving Beam 1 SSB Index_B": "NR Serving Beam 1 SSB Index Side B",
    "NR Serving Beam 1 Cell Type_B": "NR Serving Beam 1 Cell Type Side B",
    "NR Serving Beam 2 Cell Identity_B": "NR Serving Beam 2 Cell Identity Side B",
    "NR Serving Beam 2 NRARFCN DL_B": "NR Serving Beam 2 NRARFCN DL Side B",
    "NR Serving Beam 2 Band_B": "NR Serving Beam 2 Band Side B",
    "NR Serving Beam 2 Bandwidth DL_B": "NR Serving Beam 2 Bandwidth DL Side B",
    "NR Serving Beam 2 Bandwidth UL_B": "NR Serving Beam 2 Bandwidth UL Side B",
    "NR Serving Beam 2 SSB Index_B": "NR Serving Beam 2 SSB Index Side B",
    "NR Serving Beam 2 Cell Type_B": "NR Serving Beam 2 Cell Type Side B",
    "NR Serving Cell Identity Top #1_B": "NR Serving Cell Identity Top #1 Side B",
    "NR Serving Cell NRARFCN DL Top #1_B": "NR Serving Cell NRARFCN DL Top #1 Side B",
    "NR Serving Cell SS RSSI Top #1_B": "NR Serving Cell SS RSSI Top #1 Side B",
    "NR Serving Cell SS RSRP Top #1_B": "NR Serving Cell SS RSRP Top #1 Side B",
    "NR Serving Cell SS SINR Top #1_B": "NR Serving Cell SS SINR Top #1 Side B",
    "NR Serving Cell SS RSRQ Top #1_B": "NR Serving Cell SS RSRQ Top #1 Side B",
    "NR PCell SSB Serving Beam Index Top #1_B": "NR PCell SSB Serving Beam Index Top #1 Side B",
    "NR Neighbor Cell 1 Cell Identity_B": "NR Neighbor Cell 1 Cell Identity Side B",
    "NR Neighbor Cell 1 NRARFCN_B": "NR Neighbor Cell 1 NRARFCN Side B",
    "NR Neighbor Cell 1 SS RSRP (dBm)_B": "NR Neighbor Cell 1 SS RSRP (dBm) Side B",
    "NR Neighbor Cell 1 SS SINR (dB)_B": "NR Neighbor Cell 1 SS SINR (dB) Side B",
    "NR Neighbor Cell 1 SS RSRQ (dB)_B": "NR Neighbor Cell 1 SS RSRQ (dB) Side B",
    "NR Neighbor Cell 1 Best Beam Index_B": "NR Neighbor Cell 1 Best Beam Index Side B",
    "NR Neighbor Cell 1 Cell Type_B": "NR Neighbor Cell 1 Cell Type Side B",
    "NR Phy Throughput Multi-RAT DL (kbps)_B": "NR Phy Throughput Multi-RAT DL (kbps) Side B",
    "NR Phy Throughput Multi-RAT UL (kbps)_B": "NR Phy Throughput Multi-RAT UL (kbps) Side B",
    "NR PDSCH Phy Throughput Total (Kbps)_B": "NR PDSCH Phy Throughput Total (Kbps) Side B",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)_B": "NR Pcell PDSCH Scheduled Throughput (Mbps) Side B",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)_B": "NR PDSCH Phy Throughput Serving Beam 1 (Kbps) Side B",
    "NR PDSCH Modulation Serving Beam 1_B": "NR PDSCH Modulation Serving Beam 1 Side B",
    "NR PDSCH MCS Serving Beam 1_B": "NR PDSCH MCS Serving Beam 1 Side B",
    "NR PDSCH BLER (%) Serving Beam 1_B": "NR PDSCH BLER (%) Serving Beam 1 Side B",
    "NR PDSCH CQI Serving Beam 1_B": "NR PDSCH CQI Serving Beam 1 Side B",
    "NR PDSCH RI Serving Beam 1_B": "NR PDSCH RI Serving Beam 1 Side B",
    "NR DL Pathloss Serving Beam 1_B": "NR DL Pathloss Serving Beam 1 Side B",
    "NR PUCCH Tx Power Serving Beam 1 (dBm) _B": "NR PUCCH Tx Power Serving Beam 1 (dBm) Side B",
    "NR PUSCH Tx Power Serving Beam 1 (dBm) _B": "NR PUSCH Tx Power Serving Beam 1 (dBm) Side B",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)_B": "NR PDSCH Phy Throughput Serving Beam 2 (Kbps) Side B",
    "NR PDSCH Modulation Serving Beam 2_B": "NR PDSCH Modulation Serving Beam 2 Side B",
    "NR PDSCH MCS Serving Beam 2_B": "NR PDSCH MCS Serving Beam 2 Side B",
    "NR PDSCH BLER (%) Serving Beam 2_B": "NR PDSCH BLER (%) Serving Beam 2 Side B",
    "NR PDSCH CQI Serving Beam 2_B": "NR PDSCH CQI Serving Beam 2 Side B",
    "NR PDSCH RI Serving Beam 2_B": "NR PDSCH RI Serving Beam 2 Side B",
    "NR DL Pathloss Serving Beam 2_B": "NR DL Pathloss Serving Beam 2 Side B",
    "NR PUSCH Phy Throughput Total (kbps)_B": "NR PUSCH Phy Throughput Total (kbps) Side B",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)_B": "NR Pcell PUSCH Scheduled Throughput (Mbps) Side B",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)_B": "NR PUSCH Phy Throughput Serving Beam 1 (Kbps) Side B",
    "NR PUSCH Modulation Serving Beam 1_B": "NR PUSCH Modulation Serving Beam 1 Side B",
    "NR PUSCH MCS Serving Beam 1_B": "NR PUSCH MCS Serving Beam 1 Side B",
    "NR PUSCH BLER (%) Serving Beam 1_B": "NR PUSCH BLER (%) Serving Beam 1 Side B",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)_B": "NR PUSCH Phy Throughput Serving Beam 2 (Kbps) Side B",
    "NR PUSCH Modulation Serving Beam 2_B": "NR PUSCH Modulation Serving Beam 2 Side B",
    "NR PUSCH MCS Serving Beam 2_B": "NR PUSCH MCS Serving Beam 2 Side B",
    "NR PUSCH BLER (%) Serving Beam 2_B": "NR PUSCH BLER (%) Serving Beam 2 Side B",
    "NR MAC UL Throughput Total (kbps)_B": "NR MAC UL Throughput Total (kbps) Side B",
    "NR RLC DL Throughput Total (kbps)_B": "NR RLC DL Throughput Total (kbps) Side B",
    "NR RLC UL Throughput Total (kbps)_B": "NR RLC UL Throughput Total (kbps) Side B",
    "NR RLC UL Throughput (Kbps)_B": "NR RLC UL Throughput (Kbps) Side B",
    "RadioAccessTechnologyState_B": "Radio Side Bccess Technology State Side B",
    "FirmwareVersion_B": "FirmwareVersion Side B",
    "Qualifier_B": "Qualifier Side B",
    "End Latitude": "End Latitude Side A",
    "End Longitude": "End Longitude Side A",
    "End Latitude_B": "End Latitude Side B",
    "End Longitude_B": "End Longitude Side B"



}
VOICE_M2M_SCHEMA_GROUPS = {
    "VoiceM2M": [
        "Date",
        "Time",
        "Test_IDs",
        "Route Name",
        "Type of Mobility",
        "Test Name",
        "Operator",
        "MCC",
        "MNC",
        "Logfile Name Side A",
        "Sequence A",
        "Technology Detail Side A",
        "DeviceDescription Side A",
        "Latitude",
        "End Latitude Side A",
        "Longitude",
        "End Longitude Side A",
        "IMEI Side A",
        "IMSI Side A",
        "Event Name Side A",
        "Phone Number Side A",
        "Dialed Number Side A",
        "Call Status Side A",
        "Call Type Side A",
        "Call Number Side A",
        "MO Call Domain Side A",
        "MO Call Setup Time (ms) Side A",
        "MO Call User Setup Time (ms) Side A",
        "MO Call Drop Rate Side A",
        "MO Call Setup Failure Rate Side A",
        "MT Call Domain Side A",
        "MT Call Setup Time (ms) Side A",
        "MT Call User Setup Time (ms) Side A",
        "MT Call Drop Rate Side A",
        "MT Call Setup Failure Rate Side A",
        "Call Duration Side A",
        "Call Setup Duration Side A",
        "Call Setup Time (sec) Side A",
        "Voice Call Setup Time (sec) Side A",
        "Voice Call Success Rate Side A",
        "Voice Call Setup Success Rate Side A",
        "Voice Call Setup Failure Rate Side A",
        "Voice Call Completion Rate Side A",
        "Voice Dropped Call Rate Side A",
        "Voice Speech Quality On Call Basis Side A",
        "Call Drop Rate Side A",
        "Call Dropped Count Side A",
        "Call Dropped VoLTE Count Side A",
        "Call Block Rate Side A",
        "Call Blocked Count Side A",
        "Call Blocked VoLTE Count Side A",
        "Call Success Count Side A",
        "Call Success Rate Side A",
        "Call Success VoLTE Count Side A",
        "Call Initiation Side A",
        "Call Attempt Side A",
        "Call Attempt Retry Side A",
        "Call Setup Side A",
        "Call Established Side A",
        "Call End Side A",
        "Call End Initiator Side A",
        "Call Initiation Delay Side A",
        "Call Initiation Failure Rate Side A",
        "Call Initiation Success Rate Side A",
        "Data Radio Bearer Side A",
        "Multi RAT Connectivity Mode Side A",
        "Radio Side Access Technology State Side A",
        "Is Multi RAB Side A",
        "AQM RAT Side A",
        "AQM Algorithm DL Side A",
        "AQM Audio Channel Type DL Side A",
        "AQM Score Side A",
        "AQM Score DL Side A",
        "Speech Codec Side A",
        "AMR Codec DL Side A",
        "AMR Codec UL Side A",
        "AMR Codec Name DL Top #1 Side A",
        "AMR Codec Usage DL Top #1 Side A",
        "AMR Codec Name UL Top #1 Side A",
        "AMR Codec Usage UL Top #1 Side A",
        "SQ MOS Side A",
        "MOS Calculator Version Downlink Side A",
        "Multi RAB Service Type 1 Side A",
        "Multi RAB Service Type 2 Side A",
        "AQM Downlink Call Quality Side A",
        "Average Side AQM Downlink Call Quality Side A",
        "POLQA SWB Score DL Side A",
        "POLQA Speech Codec Side A",
        "RTP Jitter Audio RFC3550 (ms) Side A",
        "RTP Lost Packets Rate Audio (%) Side A",
        "RTP Relative Packet Delay Audio (ms) Side A",
        "Codec Used Side A",
        "Consecutive Packets Lost Side A",
        "FER Combined Packet Loss Side A",
        "Inter Side Arrival Jitter Side A",
        "Jitter Buffer Size Increase Side A",
        "Jitter Buffer Under runs Side A",
        "MO Sequence Number Received Side A",
        "MO Sequence Number Sent Side A",
        "Number Of Packets Lost Side A",
        "Packet Interarrival Time Side A",
        "Packet Loss Ratio Side A",
        "Payload Type Audio Side A",
        "RTP Time Gap Side A",
        "Is CSFB Call Attempt",
        "Call Attempt CSFB",
        "MO CSFB Call Abnormal Release Side A",
        "MO CSFB Call Attempt Side A",
        "MO CSFB Call Dropped Side A",
        "MO CSFB Call MS Release (Normal Cause) Side A",
        "MO CSFB Call NW Release (Normal Cause) Side A",
        "MO CSFB Call On-Call @ EOF Side A",
        "MO CSFB Call Setup Failure Side A",
        "MO CSFB Call Setup Failure - No Alerting Side A",
        "MO CSFB Call Setup Rejected Side A",
        "MO CSFB Call Setup Success Side A",
        "MT CSFB Call Abnormal Release Side A",
        "MT CSFB Call Attempt Side A",
        "MT CSFB Call Dropped Side A",
        "MT CSFB Call MS Release (Normal Cause) Side A",
        "MT CSFB Call NW Release (Normal Cause) Side A",
        "MT CSFB Call On-Call @ EOF Side A",
        "MT CSFB Call Setup Failure Side A",
        "MT CSFB Call Setup Rejected Side A",
        "MT CSFB Call Setup Success Side A",
        "LTE MO CSFB Setup Delay ms Side A",
        "LTE MT CSFB Setup Delay ms Side A",
        "LTE PS Data Interrupt Time Due to CSFB ms Side A",
        "CSFB Call Setup Time sec Side A",
        "MO CSFB Call Setup Time ms Side A",
        "MO CSFB Call User Setup Time ms Side A",
        "MT CSFB Call Setup Time ms Side A",
        "Reselection Time After CSFB Call Idle to LTE ms Side A",
        "Reselection Time After CSFB Call SIB19 to LTE Side A",
        "Voice CSFB Setup Failure Rate Side A",
        "Voice CSFB Setup Success Rate Side A",
        "Call Attempt EPSFB Side A",
        "Call Blocked EPSFB Side A",
        "Call Established EPSFB Side A",
        "Call Setup EPSFB Side A",
        "SRVCC Handover Interruption Time Control Plane Side A",
        "Reselection Time After SRVCC Call Idle to LTE Side A",
        "Reselection Time After SRVCC Call SIB19 to LTE Side A",
        "SRVCC Handover Side A",
        "SRVCC Handover (During On-going Call) Side A",
        "SRVCC Handover (During Setup) Side A",
        "SRVCC Handover Failure Side A",
        "SRVCC Handover Interruption Time User Plane Side A",
        "SRVCC User Plane Delay Side A",
        "SRVCC User Plane Interruption Time Side A",
        "LTE Cell Identity(eNB Part) Side A",
        "LTE Cell Identity(Cell Part) Side A",
        "LTE Serving Cell Identity Side A",
        "LTE Serving Cell DL EARFCN Side A",
        "LTE Serving Cell Frequency Band Side A",
        "LTE Serving Cell Channel RSSI(dBm) Side A",
        "LTE Serving Cell RSRP(dBm) Side A",
        "LTE Serving Cell RS SINR(dB) Side A",
        "LTE Serving Cell RSRQ (dB) Side A",
        "LTE Serving Cell Count Side Average Side A",
        "LTE Secondary Serving Cell 1 Identity Side A",
        "LTE Secondary Serving Cell 1 DL EARFCN Side A",
        "LTE Secondary Serving Cell 1 Frequency Band Side A",
        "LTE Secondary Serving Cell 1 Channel RSSI (dBm) Side A",
        "LTE Secondary Serving Cell 1 RSRP (dBm) Side A",
        "LTE Secondary Serving Cell 1 RS SINR (dB) Side A",
        "LTE Secondary Serving Cell 1 RSRQ (dB) Side A",
        "LTE Neighbor Cell 1 PCI Side A",
        "LTE Neighbor Cell 1 DL EARFCN Side A",
        "LTE Neighbor Cell 1 RSRP Side A",
        "LTE Neighbor Cell 1 RSRQ Side A",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB) Side A",
        "LTE MAC DL Throughput (kbps) Side A",
        "LTE MAC DL Throughput Carrier 1 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 2 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 3 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 4 (kbps) Side A",
        "LTE MAC UL Throughput (kbps) Side A",
        "LTE MAC UL Throughput Carrier 1 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 2 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 3 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 4 (kbps) Side A",
        "LTE PDSCH Modulation Side A",
        "LTE PDSCH MCS Side A",
        "LTE PDSCH BLER (%) Side A",
        "LTE PDSCH Phy Throughput (kbps) Side A",
        "LTE PDSCH Phy Throughput Total (kbps) Side A",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps) Side A",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps) Side A",
        "LTE PUSCH Modulation Side A",
        "LTE PUSCH MCS Side A",
        "PUSCH BLER (%) Side A",
        "LTE UE TX Power - PUSCH (dBm) Carrier 1 Side A",
        "LTE UE TX Power - PUCCH (dBm) Carrier 1 Side A",
        "LTE PUSCH Phy Throughput (kbps) Side A",
        "LTE PUSCH Phy Throughput Total (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps) Side A",
        "PUSCH Phy Throughput Carrier 4 (kbps) Side A",
        "LTE RLC Throughput DL (Kbps) Side A",
        "LTE RLC Throughput UL (Kbps) Side A",
        "LTE Bearer Maximum Bitrate DL (kbit/s) Side A",
        "LTE PDN Connection Side AMBR DL (kbps) Side A",
        "NR Serving Beam 1 Cell Identity Side A",
        "NR Serving Beam 1 NRARFCN DL Side A",
        "NR Serving Beam 1 Band Side A",
        "NR Serving Beam 1 Bandwidth DL Side A",
        "NR Serving Beam 1 Bandwidth UL Side A",
        "NR Serving Beam 1 SSB Index Side A",
        "NR Serving Beam 1 Cell Type Side A",
        "NR Serving Beam 2 Cell Identity Side A",
        "NR Serving Beam 2 NRARFCN DL Side A",
        "NR Serving Beam 2 Band Side A",
        "NR Serving Beam 2 Bandwidth DL Side A",
        "NR Serving Beam 2 Bandwidth UL Side A",
        "NR Serving Beam 2 SSB Index Side A",
        "NR Serving Beam 2 Cell Type Side A",
        "NR Serving Cell Identity Top #1 Side A",
        "NR Serving Cell NRARFCN DL Top #1 Side A",
        "NR Serving Cell SS RSSI Top #1 Side A",
        "NR Serving Cell SS RSRP Top #1 Side A",
        "NR Serving Cell SS SINR Top #1 Side A",
        "NR Serving Cell SS RSRQ Top #1 Side A",
        "NR PCell SSB Serving Beam Index Top #1 Side A",
        "NR Neighbor Cell 1 Cell Identity Side A",
        "NR Neighbor Cell 1 NRARFCN Side A",
        "NR Neighbor Cell 1 SS RSRP (dBm) Side A",
        "NR Neighbor Cell 1 SS SINR (dB) Side A",
        "NR Neighbor Cell 1 SS RSRQ (dB) Side A",
        "NR Neighbor Cell 1 Best Beam Index Side A",
        "NR Neighbor Cell 1 Cell Type Side A",
        "NR Phy Throughput Multi-RAT DL (kbps) Side A",
        "NR Phy Throughput Multi-RAT UL (kbps) Side A",
        "NR PDSCH Phy Throughput Total (Kbps) Side A",
        "NR Pcell PDSCH Scheduled Throughput (Mbps) Side A",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps) Side A",
        "NR PDSCH Modulation Serving Beam 1 Side A",
        "NR PDSCH MCS Serving Beam 1 Side A",
        "NR PDSCH BLER (%) Serving Beam 1 Side A",
        "NR PDSCH CQI Serving Beam 1 Side A",
        "NR PDSCH RI Serving Beam 1 Side A",
        "NR DL Pathloss Serving Beam 1 Side A",
        "NR PUCCH Tx Power Serving Beam 1 (dBm) Side A",
        "NR PUSCH Tx Power Serving Beam 1 (dBm) Side A",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps) Side A",
        "NR PDSCH Modulation Serving Beam 2 Side A",
        "NR PDSCH MCS Serving Beam 2 Side A",
        "NR PDSCH BLER (%) Serving Beam 2 Side A",
        "NR PDSCH CQI Serving Beam 2 Side A",
        "NR PDSCH RI Serving Beam 2 Side A",
        "NR DL Pathloss Serving Beam 2 Side A",
        "NR PUSCH Phy Throughput Total (kbps) Side A",
        "NR Pcell PUSCH Scheduled Throughput (Mbps) Side A",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps) Side A",
        "NR PUSCH Modulation Serving Beam 1 Side A",
        "NR PUSCH MCS Serving Beam 1 Side A",
        "NR PUSCH BLER (%) Serving Beam 1 Side A",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps) Side A",
        "NR PUSCH Modulation Serving Beam 2 Side A",
        "NR PUSCH MCS Serving Beam 2 Side A",
        "NR PUSCH BLER (%) Serving Beam 2 Side A",
        "NR MAC UL Throughput Total (kbps) Side A",
        "NR RLC DL Throughput Total (kbps) Side A",
        "NR RLC UL Throughput Total (kbps) Side A",
        "NR RLC UL Throughput (Kbps) Side A",
        "FirmwareVersion Side A",
        "Logfile Name Side B",
        "Sequence B",
        "Technology Detail Side B",
        "DeviceDescription Side B",
        "Start Latitude Side B",
        "End Latitude Side B",
        "Start Longitude Side B",
        "End Longitude Side B",
        "IMEI Side B",
        "IMSI Side B",
        "Event Name Side B",
        "Phone Number Side B",
        "Dialed Number Side B",
        "Call Status Side B",
        "Call Type Side B",
        "Call Number Side B",
        "MO Call Domain Side B",
        "MO Call Setup Time (ms) Side B",
        "MO Call User Setup Time (ms) Side B",
        "MO Call Drop Rate Side B",
        "MO Call Setup Failure Rate Side B",
        "MT Call Domain Side B",
        "MT Call Setup Time (ms) Side B",
        "MT Call User Setup Time (ms) Side B",
        "MT Call Drop Rate Side B",
        "MT Call Setup Failure Rate Side B",
        "Call Duration Side B",
        "Call Setup Duration Side B",
        "Call Setup Time (sec) Side B",
        "Voice Call Setup Time (sec) Side B",
        "Voice Call Success Rate Side B",
        "Voice Call Setup Success Rate Side B",
        "Voice Call Setup Failure Rate Side B",
        "Voice Call Completion Rate Side B",
        "Voice Dropped Call Rate Side B",
        "Voice Speech Quality On Call Basis Side B",
        "Call Drop Rate Side B",
        "Call Dropped Count Side B",
        "Call Dropped VoLTE Count Side B",
        "Call Block Rate Side B",
        "Call Blocked Count Side B",
        "Call Blocked VoLTE Count Side B",
        "Call Success Count Side B",
        "Call Success Rate Side B",
        "Call Success VoLTE Count Side B",
        "Call Initiation Side B",
        "Call Attempt Side B",
        "Call Attempt Retry Side B",
        "Call Setup Side B",
        "Call Established Side B",
        "Call End Side B",
        "Call End Initiator Side B",
        "Call Initiation Delay Side B",
        "Call Initiation Failure Rate Side B",
        "Call Initiation Success Rate Side B",
        "Data Radio Bearer Side B",
        "Multi RAT Connectivity Mode Side B",
        "Radio Side Bccess Technology State Side B",
        "Is Multi RAB Side B",
        "AQM RAT Side B",
        "AQM Algorithm DL Side B",
        "AQM Audio Channel Type DL Side B",
        "AQM Score Side B",
        "AQM Score DL Side B",
        "Speech Codec Side B",
        "AMR Codec DL Side B",
        "AMR Codec UL Side B",
        "AMR Codec Name DL Top #1 Side B",
        "AMR Codec Usage DL Top #1 Side B",
        "AMR Codec Name UL Top #1 Side B",
        "AMR Codec Usage UL Top #1 Side B",
        "SQ MOS Side B",
        "MOS Calculator Version Downlink Side B",
        "Multi RAB Service Type 1 Side B",
        "Multi RAB Service Type 2 Side B",
        "AQM Downlink Call Quality Side B",
        "Average Side BQM Downlink Call Quality Side B",
        "POLQA SWB Score DL Side B",
        "POLQA Speech Codec Side B",
        "RTP Jitter Audio RFC3550 (ms) Side B",
        "RTP Lost Packets Rate Audio (%) Side B",
        "RTP Relative Packet Delay Audio (ms) Side B",
        "Codec Used Side B",
        "Consecutive Packets Lost Side B",
        "FER Combined Packet Loss Side B",
        "Inter Side Brrival Jitter Side B",
        "Jitter Buffer Size Increase Side B",
        "Jitter Buffer Under runs Side B",
        "MO Sequence Number Received Side B",
        "MO Sequence Number Sent Side B",
        "Number Of Packets Lost Side B",
        "Packet Interarrival Time Side B",
        "Packet Loss Ratio Side B",
        "Payload Type Audio Side B",
        "RTP Time Gap Side B",
        "Is CSFB Call Attempt Side B",
        "Call Attempt CSFB Side B",
        "MO CSFB Call Abnormal Release Side B",
        "MO CSFB Call Attempt Side B",
        "MO CSFB Call Dropped Side B",
        "MO CSFB Call MS Release (Normal Cause) Side B",
        "MO CSFB Call NW Release (Normal Cause) Side B",
        "MO CSFB Call On-Call @ EOF Side B",
        "MO CSFB Call Setup Failure Side B",
        "MO CSFB Call Setup Failure - No Alerting Side B",
        "MO CSFB Call Setup Rejected Side B",
        "MO CSFB Call Setup Success Side B",
        "MT CSFB Call Abnormal Release Side B",
        "MT CSFB Call Attempt Side B",
        "MT CSFB Call Dropped Side B",
        "MT CSFB Call MS Release (Normal Cause) Side B",
        "MT CSFB Call NW Release (Normal Cause) Side B",
        "MT CSFB Call On-Call @ EOF Side B",
        "MT CSFB Call Setup Failure Side B",
        "MT CSFB Call Setup Rejected Side B",
        "MT CSFB Call Setup Success Side B",
        "LTE MO CSFB Setup Delay ms Side B",
        "LTE MT CSFB Setup Delay ms Side B",
        "LTE PS Data Interrupt Time Due to CSFB ms Side B",
        "CSFB Call Setup Time sec Side B",
        "MO CSFB Call Setup Time ms Side B",
        "MO CSFB Call User Setup Time ms Side B",
        "MT CSFB Call Setup Time ms Side B",
        "Reselection Time After CSFB Call Idle to LTE ms Side B",
        "Reselection Time After CSFB Call SIB19 to LTE Side B",
        "Voice CSFB Setup Failure Rate Side B",
        "Voice CSFB Setup Success Rate Side B",
        "Call Attempt EPSFB Side B",
        "Call Blocked EPSFB Side B",
        "Call Established EPSFB Side B",
        "Call Setup EPSFB Side B",
        "SRVCC Handover Interruption Time Control Plane Side B",
        "Reselection Time After SRVCC Call Idle to LTE Side B",
        "Reselection Time After SRVCC Call SIB19 to LTE Side B",
        "SRVCC Handover Side B",
        "SRVCC Handover (During On-going Call) Side B",
        "SRVCC Handover (During Setup) Side B",
        "SRVCC Handover Failure Side B",
        "SRVCC Handover Interruption Time User Plane Side B",
        "SRVCC User Plane Delay Side B",
        "SRVCC User Plane Interruption Time Side B",
        "LTE Cell Identity(eNB Part) Side B",
        "LTE Cell Identity(Cell Part) Side B",
        "LTE Serving Cell Identity Side B",
        "LTE Serving Cell DL EARFCN Side B",
        "LTE Serving Cell Frequency Band Side B",
        "LTE Serving Cell Channel RSSI(dBm) Side B",
        "LTE Serving Cell RSRP(dBm) Side B",
        "LTE Serving Cell RS SINR(dB) Side B",
        "LTE Serving Cell RSRQ (dB) Side B",
        "LTE Serving Cell Count Side Bverage Side B",
        "LTE Secondary Serving Cell 1 Identity Side B",
        "LTE Secondary Serving Cell 1 DL EARFCN Side B",
        "LTE Secondary Serving Cell 1 Frequency Band Side B",
        "LTE Secondary Serving Cell 1 Channel RSSI (dBm) Side B",
        "LTE Secondary Serving Cell 1 RSRP (dBm) Side B",
        "LTE Secondary Serving Cell 1 RS SINR (dB) Side B",
        "LTE Secondary Serving Cell 1 RSRQ (dB) Side B",
        "LTE Neighbor Cell 1 PCI Side B",
        "LTE Neighbor Cell 1 DL EARFCN Side B",
        "LTE Neighbor Cell 1 RSRP Side B",
        "LTE Neighbor Cell 1 RSRQ Side B",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB) Side B",
        "LTE MAC DL Throughput (kbps) Side B",
        "LTE MAC DL Throughput Carrier 1 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 2 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 3 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 4 (kbps) Side B",
        "LTE MAC UL Throughput (kbps) Side B",
        "LTE MAC UL Throughput Carrier 1 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 2 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 3 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 4 (kbps) Side B",
        "LTE PDSCH Modulation Side B",
        "LTE PDSCH MCS Side B",
        "LTE PDSCH BLER (%) Side B",
        "LTE PDSCH Phy Throughput (kbps) Side B",
        "LTE PDSCH Phy Throughput Total (kbps) Side B",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps) Side B",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps) Side B",
        "LTE PUSCH Modulation Side B",
        "LTE PUSCH MCS Side B",
        "PUSCH BLER (%) Side B",
        "LTE UE TX Power - PUSCH (dBm) Carrier 1 Side B",
        "LTE UE TX Power - PUCCH (dBm) Carrier 1 Side B",
        "LTE PUSCH Phy Throughput (kbps) Side B",
        "LTE PUSCH Phy Throughput Total (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps) Side B",
        "PUSCH Phy Throughput Carrier 4 (kbps) Side B",
        "LTE RLC Throughput DL (Kbps) Side B",
        "LTE RLC Throughput UL (Kbps) Side B",
        "LTE Bearer Maximum Bitrate DL (kbit/s) Side B",
        "LTE PDN Connection Side BMBR DL (kbps) Side B",
        "NR Serving Beam 1 Cell Identity Side B",
        "NR Serving Beam 1 NRARFCN DL Side B",
        "NR Serving Beam 1 Band Side B",
        "NR Serving Beam 1 Bandwidth DL Side B",
        "NR Serving Beam 1 Bandwidth UL Side B",
        "NR Serving Beam 1 SSB Index Side B",
        "NR Serving Beam 1 Cell Type Side B",
        "NR Serving Beam 2 Cell Identity Side B",
        "NR Serving Beam 2 NRARFCN DL Side B",
        "NR Serving Beam 2 Band Side B",
        "NR Serving Beam 2 Bandwidth DL Side B",
        "NR Serving Beam 2 Bandwidth UL Side B",
        "NR Serving Beam 2 SSB Index Side B",
        "NR Serving Beam 2 Cell Type Side B",
        "NR Serving Cell Identity Top #1 Side B",
        "NR Serving Cell NRARFCN DL Top #1 Side B",
        "NR Serving Cell SS RSSI Top #1 Side B",
        "NR Serving Cell SS RSRP Top #1 Side B",
        "NR Serving Cell SS SINR Top #1 Side B",
        "NR Serving Cell SS RSRQ Top #1 Side B",
        "NR PCell SSB Serving Beam Index Top #1 Side B",
        "NR Neighbor Cell 1 Cell Identity Side B",
        "NR Neighbor Cell 1 NRARFCN Side B",
        "NR Neighbor Cell 1 SS RSRP (dBm) Side B",
        "NR Neighbor Cell 1 SS SINR (dB) Side B",
        "NR Neighbor Cell 1 SS RSRQ (dB) Side B",
        "NR Neighbor Cell 1 Best Beam Index Side B",
        "NR Neighbor Cell 1 Cell Type Side B",
        "NR Phy Throughput Multi-RAT DL (kbps) Side B",
        "NR Phy Throughput Multi-RAT UL (kbps) Side B",
        "NR PDSCH Phy Throughput Total (Kbps) Side B",
        "NR Pcell PDSCH Scheduled Throughput (Mbps) Side B",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps) Side B",
        "NR PDSCH Modulation Serving Beam 1 Side B",
        "NR PDSCH MCS Serving Beam 1 Side B",
        "NR PDSCH BLER (%) Serving Beam 1 Side B",
        "NR PDSCH CQI Serving Beam 1 Side B",
        "NR PDSCH RI Serving Beam 1 Side B",
        "NR DL Pathloss Serving Beam 1 Side B",
        "NR PUCCH Tx Power Serving Beam 1 (dBm) Side B",
        "NR PUSCH Tx Power Serving Beam 1 (dBm) Side B",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps) Side B",
        "NR PDSCH Modulation Serving Beam 2 Side B",
        "NR PDSCH MCS Serving Beam 2 Side B",
        "NR PDSCH BLER (%) Serving Beam 2 Side B",
        "NR PDSCH CQI Serving Beam 2 Side B",
        "NR PDSCH RI Serving Beam 2 Side B",
        "NR DL Pathloss Serving Beam 2 Side B",
        "NR PUSCH Phy Throughput Total (kbps) Side B",
        "NR Pcell PUSCH Scheduled Throughput (Mbps) Side B",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps) Side B",
        "NR PUSCH Modulation Serving Beam 1 Side B",
        "NR PUSCH MCS Serving Beam 1 Side B",
        "NR PUSCH BLER (%) Serving Beam 1 Side B",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps) Side B",
        "NR PUSCH Modulation Serving Beam 2 Side B",
        "NR PUSCH MCS Serving Beam 2 Side B",
        "NR PUSCH BLER (%) Serving Beam 2 Side B",
        "NR MAC UL Throughput Total (kbps) Side B",
        "NR RLC DL Throughput Total (kbps) Side B",
        "NR RLC UL Throughput Total (kbps) Side B",
        "NR RLC UL Throughput (Kbps) Side B",
        "FirmwareVersion Side B",
        "Qualifier Side A",
        "Qualifier Side B"



   ]
}