import pandas as pd
from pathlib import Path
from datetime import datetime

# === Load Excel ===
input_folder = Path("/mnt/c/Users/User/Documents/Indra/geo/CDR/parsing/split/HTTPs/Input")
all_files = list(input_folder.glob("*.xlsx"))

df_list = []

for file_path in all_files:
    xls = pd.ExcelFile(file_path)
    df_sheet = xls.parse(xls.sheet_names[0])
    df_sheet["SourceFile"] = file_path.stem  # Optional: keep track of where each row came from
    df_list.append(df_sheet)

# Combine all into one DataFrame
df = pd.concat(df_list, ignore_index=True)

# === Step 1: Split 'Date Time' into 'Date' and 'Time'
df[['Date', 'Time']] = df['Date Time'].astype(str).str.split(' ', expand=True)
df.drop(columns=["Date Time"], inplace=True)  # Optional

# === Step 2: Rename columns globally
master_rename_map = {
    "Date Time": "Date",
    "Time": "Time",
    "Test Name": "Test Name",
    "Type Mobility": "Type of Mobility",
    "Operator": "Operator",
    "Country": "Route Name",
    "Sequence": "Sequence",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "MCC": "MCC",
    "MNC": "MNC",
    "Technology_Detail": "Session Start Technology",
    "DNS_Client": "DNS Client",
    "DNS_Domain_Name": "DNS Domain Name",
    "DNS_Server_Address": "DNS Server Address",
    "DNS_Resolved_Address": "DNS Resolved Address",
    "First DNS Request": "First DNS Request",
    "DNS_First_In_Session": "DNS First In Session",
    "DNS_Host_Name_Resolution_Failure_Ratio": "DNS Host Name Resolution Failure Ratio",
    "DNS_Host_Name_Resolution_Time_sec": "DNS Host Name Resolution Time (sec)",
    "DNS_Host_Name_Total_Resolution_Time_sec": "DNS Host Name Total Resolution Time (sec)",
    "DNS Resolution Success Ratio (%)": "DNS Resolution Success Ratio (%)",
    "TAC": "Session Start TAC",
    "HttpLogfileName": "Logfile Name",
    "HttpImsi": "IMSI",
    "HttpStartTime": "Session Start Time",
    "HttpStartLatitude": "Session Start Latitude",
    "HttpStartLongitude": "Session Start Longitude",
    "HttpStartMultiRATConnectivityMode": "Session Start MultiRAT",
    "First_DNS_Request_to_HTTP_Get_First_Chunk_Downloaded_ms": "First DNS Request to HTTP Get First Chunk Downloaded (ms)",
    "HttpDataRadioBearer": "Session Start Data Radio Bearer",
    "HttpDataTransferCutoff": "HTTP Data Transfer Cutoff",
    "HttpDataTransferTime": "HTTP Data Transfer Time",
    "HttpDirection": "HTTP Direction",
    "HttpErrorMessage": "HTTP Error Message",
    "HttpIPServiceAccessFailure": "HTTP IP Service Access Failure",
    "HttpIpServiceSetupTime": "HTTP IP Service Setup Time",
    "HttpMeanDataRate": "HTTP Mean Data Rate",
    "HttpServiceStatus": "HTTP Service Status",
    "HttpServiceBearer": "HTTP Service Bearer",
    "HTTP_Download_Service_Average_Throughput": "HTTP Download Service Average Throughput",
    "HTTP_Download_Session_Failure_Ratio": "HTTP Download Session Failure Ratio",
    "HTTP_Download_Session_Success_Ratio": "HTTP Download Session Success Ratio",
    "HTTP_Error_Cause": "HTTP Error Cause",
    "HTTP_Outcome": "HTTP Outcome",
    "HTTP_Technical_Browsing_Time_sec": "HTTP Technical Browsing Time (sec)",
    "HTTP_URL": "HTTP URL",
    "HTTP_User_Browsing_Time_sec": "HTTP User Browsing Time (sec)",
    "Seconds_Start_to_End_HTTP": "Seconds Start to End HTTP",
    "HTTP_Download_Average_Throughput": "HTTP Download Average Throughput",
    "HTTP Data Transfer Cutoff Ratio (%)": "HTTP Data Transfer Cutoff Ratio (%)",
    "HTTP Download Throughput (kbps)": "HTTP Download Throughput (kbps)",
    "HTTP_Download_Data_Transfer_Failure_Ratio_Method_A": "HTTP Download Data Transfer Failure Ratio Method A",
    "HTTP_Download_Data_Transfer_Success_Ratio_Method_A": "HTTP Download Data Transfer Success Ratio Method A",
    "HTTP_Download_Data_Transfer_Time_sec_Method_A": "HTTP Download Data Transfer Time (sec) Method A",
    "HTTP_Download_IP_Service_Access_Failure_Ratio_Method_A": "HTTP Download IP Service Access Failure Ratio Method A",
    "HTTP_Download_IP_Service_Setup_Success_Ratio_Method_A": "HTTP Download IP Service Setup Success Ratio Method A",
    "HTTP_Download_IP_Service_Setup_Time_sec_Method_A": "HTTP Download IP Service Setup Time (sec) Method A",
    "HTTP_Download_Mean_Data_Rate_kbps_Method_A": "HTTP Download Mean Data Rate kbps Method A",
    "HTTP_Download_Transfer_Start_Delay_Method_A": "HTTP Download Transfer Start Delay Method A",
    "HTTP_Download_Data_Transfer_Failure_Ratio_Method_B": "HTTP Download Data Transfer Failure Ratio Method B",
    "HTTP_Download_Data_Transfer_Success_Ratio_Method_B": "HTTP Download Data Transfer Success Ratio Method B",
    "HTTP_Download_Data_Transfer_Time_sec_Method_B": "HTTP Download Data Transfer Time (sec) Method B",
    "HTTP_Download_IP_Service_Access_Failure_Ratio_Method_B": "HTTP Download IP Service Access Failure Ratio Method B",
    "HTTP_Download_IP_Service_Setup_Success_Ratio_Method_B": "HTTP Download IP Service Setup Success Ratio Method B",
    "HTTP_Download_IP_Service_Setup_Time_sec_Method_B": "HTTP Download IP Service Setup Time (sec) Method B",
    "HTTP_Download_Mean_Data_Rate_kbps_Method_B": "HTTP Download Mean Data Rate kbps Method B",
    "HTTP_Post_Outcome": "HTTP Post Outcome",
    "Seconds_Start_to_End_HTTP_Post": "Seconds Start to End HTTP Post",
    "HTTP_Upload_Average_Throughput": "HTTP Upload Average Throughput",
    "First_DNS_Request_to_HTTP_Post_First_Chunk_Uploaded_ms": "First DNS Request to HTTP Post First Chunk Uploaded (ms)",
    "HTTP_Upload_Session_Failure_Ratio": "HTTP Upload Session Failure Ratio",
    "HTTP_Upload_Session_Success_Ratio": "HTTP Upload Session Success Ratio",
    "HTTP_Upload_Data_Transfer_Failure_Ratio_Method_A": "HTTP Upload Data Transfer Failure Ratio Method A",
    "HTTP_Upload_Data_Transfer_Success_Ratio_Method_A": "HTTP Upload Data Transfer Success Ratio Method A",
    "HTTP_Upload_Data_Transfer_Time_sec_Method_A": "HTTP Upload Data Transfer Time (sec) Method A",
    "HTTP_Upload_IP_Service_Access_Failure_Ratio_Method_A": "HTTP Upload IP Service Access Failure Ratio Method A",
    "HTTP_Upload_IP_Service_Setup_Success_Ratio_Method_A": "HTTP Upload IP Service Setup Success Ratio Method A",
    "HTTP_Upload_IP_Service_Setup_Time_sec_Method_A": "HTTP Upload IP Service Setup Time (sec) Method A",
    "HTTP_Upload_Mean_Data_Rate_kbps_Method_A": "HTTP Upload Mean Data Rate kbps Method A",
    "HTTP_Upload_Data_Transfer_Failure_Ratio_Method_B": "HTTP Upload Data Transfer Failure Ratio Method B",
    "HTTP_Upload_Data_Transfer_Success_Ratio_Method_B": "HTTP Upload Data Transfer Success Ratio Method B",
    "HTTP_Upload_Data_Transfer_Time_sec_Method_B": "HTTP Upload Data Transfer Time (sec) Method B",
    "HTTP_Upload_IP_Service_Access_Failure_Ratio_Method_B": "HTTP Upload IP Service Access Failure Ratio Method B",
    "HTTP_Upload_IP_Service_Setup_Success_Ratio_Method_B": "HTTP Upload IP Service Setup Success Ratio Method B",
    "HTTP_Upload_IP_Service_Setup_Time_sec_Method_B": "HTTP Upload IP Service Setup Time (sec) Method B",
    "HTTP_Upload_Mean_Data_Rate_kbps_Method_B": "HTTP Upload Mean Data Rate kbps Method B",
    "HttpEndTime": "Session End Time",
    "HttpEndMultiRATConnectivityMode": "Session End MultiRAT",
    "HttpEndLatitude": "Session End Latitude",
    "HttpEndLongitude": "Session End Longitude",
    "IP_Interruption_Time_ms": "IP Interruption Time (ms)",
    "TCP_Handshake_Time_sec": "TCP Handshake Time (sec)",
    "TLSHandshakeFailureRatio (%)": "TLS Handshake Failure Ratio (%)",
    "ThroughputCountOver1MBit": "Throughput Count Over 1MBit",
    "ThroughputCountOver3MBit": "Throughput Count Over 3MBit",
    "ThroughputPercentageOver3MBit": "ThroughputPercentageOver3MBit",
    "IEBrowseDownloadTime(ms)": "IE Browse Download Time (ms)",
    "IEBrowsePageSize(Bytes)": "IE Browse Page Size (Bytes)",
    "LTE Cell Identity(eNB Part)": "LTE Cell Identity(eNB Part)",
    "LTE Cell Identity(Cell Part)": "LTE Cell Identity(Cell Part)",
    "LTE Serving Cell Identity": "LTE Serving Cell Identity",
    "LTE Serving Cell DL EARFCN": "LTE Serving Cell DL EARFCN",
    "LTE Serving Cell Frequency Band": "LTE Serving Cell Frequency Band",
    "LTE Serving Cell Channel RSSI(dBm)": "LTE Serving Cell Channel RSSI(dBm)",
    "LTE Serving Cell RSRP(dBm)": "LTE Serving Cell RSRP(dBm)",
    "LTE Serving Cell RS SINR(dB)": "LTE Serving Cell RS SINR(dB)",
    "LTE Serving Cell RSRQ (dB)": "LTE Serving Cell RSRQ (dB)",
    "LTE_Serving_Cell_Count_Average": "LTE Serving Cell Count Average",
    "LTE Secondary Serving Cell 1 Identity": "LTE secondary Serving Cell 1 Identity",
    "LTE Secondary Serving Cell 1 DL EARFCN": "LTE secondary Serving Cell 1 DL EARFCN",
    "LTE Secondary Serving Cell 1 Frequency Band": "LTE secondary Serving Cell 1 Frequency Band",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)": "LTE secondary Serving Cell 1 Channel RSSI (dBm)",
    "LTE Secondary Serving Cell 1 RSRP (dBm)": "LTE secondary Serving Cell 1 RSRP (dBm)",
    "LTE Secondary Serving Cell 1 RS SINR (dB)": "LTE secondary Serving Cell 1 RS SINR (dB)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)": "LTE secondary Serving Cell 1 RSRQ (dB)",
    "LTE Neighbor Cell 1 PCI": "LTE Neighbor Cell 1 PCI",
    "LTE Neighbor Cell 1 DL EARFCN": "LTE Neighbor Cell 1 DL EARFCN",
    "LTE Neighbor Cell 1 RSRP": "LTE Neighbor Cell 1 RSRP",
    "LTE Neighbor Cell 1 RSRQ": "LTE Neighbor Cell 1 RSRQ",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)": "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "LTE MAC DL Throughput (kbps)": "LTE MAC DL Throughput (kbps)",
    "LTE MAC DL Throughput Carrier 1 (kbps)": "LTE MAC DL Throughput Carrier 1 (kbps)",
    "LTE MAC DL Throughput Carrier 2 (kbps)": "LTE MAC DL Throughput Carrier 2 (kbps)",
    "LTE MAC DL Throughput Carrier 3 (kbps)": "LTE MAC DL Throughput Carrier 3 (kbps)",
    "LTE MAC DL Throughput Carrier 4 (kbps)": "LTE MAC DL Throughput Carrier 4 (kbps)",
    "LTE MAC UL Throughput (kbps)": "LTE MAC UL Throughput (kbps)",
    "LTE MAC UL Throughput Carrier 1 (kbps)": "LTE MAC UL Throughput Carrier 1 (kbps)",
    "LTE MAC UL Throughput Carrier 2 (kbps)": "LTE MAC UL Throughput Carrier 2 (kbps)",
    "LTE MAC UL Throughput Carrier 3 (kbps)": "LTE MAC UL Throughput Carrier 3 (kbps)",
    "LTE MAC UL Throughput Carrier 4 (kbps)": "LTE MAC UL Throughput Carrier 4 (kbps)",
    "LTE PDSCH Modulation": "LTE PDSCH Modulation",
    "LTE PDSCH MCS": "LTE PDSCH MCS",
    "LTE PDSCH BLER (%)": "LTE PDSCH BLER (%)",
    "LTE PDSCH Phy Throughput (kbps)": "LTE PDSCH Phy Throughput (kbps)",
    "LTE PDSCH Phy Throughput Total (kbps)": "LTE PDSCH Phy Throughput Total (kbps)",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)": "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)": "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)": "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)": "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
    "LTE PUSCH Modulation ": "LTE PUSCH Modulation",
    "LTE PUSCH MCS ": "LTE PUSCH MCS",
    "PUSCH BLER (%)": "PUSCH BLER (%)",
    "LTE PUSCH Phy Throughput (kbps)": "LTE PUSCH Phy Throughput (kbps)",
    "LTE PUSCH Phy Throughput Total (kbps)": "LTE PUSCH Phy Throughput Total (kbps)",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)": "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)": "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)": "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Phy Throughput Carrier 4 (kbps)": "PUSCH Phy Throughput Carrier 4 (kbps)",
    "LTE RLC Throughput DL (Kbps)": "LTE RLC Throughput DL (Kbps)",
    "LTE RLC Throughput UL (Kbps)": "LTE RLC Throughput UL (Kbps)",
    "NR Serving Beam 1 Cell Identity": "NR Serving Beam 1 Cell Identity",
    "NR Serving Beam 1 NRARFCN DL": "NR Serving Beam 1 NRARFCN DL",
    "NR Serving Beam 1 Band": "NR Serving Beam 1 Band",
    "NR Serving Beam 1 Bandwidth DL": "NR Serving Beam 1 Bandwidth DL",
    "NR Serving Beam 1 Bandwidth UL": "NR Serving Beam 1 Bandwidth UL",
    "NR Serving Beam 1 SSB Index": "NR Serving Beam 1 SSB Index",
    "NR Serving Beam 1 Cell Type": "NR Serving Beam 1 Cell Type",
    "NR Serving Beam 1 GSCN": "NR Serving Beam 1 GSCN",
    "NR Serving Beam 2 Cell Identity": "NR Serving Beam 2 Cell Identity",
    "NR Serving Beam 2 NRARFCN DL": "NR Serving Beam 2 NRARFCN DL",
    "NR Serving Beam 2 Band": "NR Serving Beam 2 Band",
    "NR Serving Beam 2 Bandwidth DL": "NR Serving Beam 2 Bandwidth DL",
    "NR Serving Beam 2 Bandwidth UL": "NR Serving Beam 2 Bandwidth UL",
    "NR Serving Beam 2 SSB Index": "NR Serving Beam 2 SSB Index",
    "NR Serving Beam 2 Cell Type": "NR Serving Beam 2 Cell Type",
    "NR Serving Beam 2 GSCN": "NR Serving Beam 2 GSCN",
    "NR Serving Cell Identity Top #1": "NR Serving Cell Identity Top #1",
    "NR Serving Cell NRARFCN DL Top #1": "NR Serving Cell NRARFCN DL Top #1",
    "NR Serving Cell SS RSSI Top #1": "NR Serving Cell SS RSSI Top #1",
    "NR Serving Cell SS RSRP Top #1": "NR Serving Cell SS RSRP Top #1",
    "NR Serving Cell SS SINR Top #1": "NR Serving Cell SS SINR Top #1",
    "NR Serving Cell SS RSRQ Top #1": "NR Serving Cell SS RSRQ Top #1",
    "NR PCell SSB Serving Beam Index Top #1": "NR PCell SSB Serving Beam Index Top #1",
    "NR Neighbor Cell 1 Cell Identity": "NR Neighbor Cell 1 Cell Identity",
    "NR Neighbor Cell 1 NRARFCN": "NR Neighbor Cell 1 NRARFCN",
    "NR Neighbor Cell 1 SS RSRP (dBm)": "NR Neighbor Cell 1 SS RSRP (dBm)",
    "NR Neighbor Cell 1 SS SINR (dB)": "NR Neighbor Cell 1 SS SINR (dB)",
    "NR Neighbor Cell 1 SS RSRQ (dB)": "NR Neighbor Cell 1 SS RSRQ (dB)",
    "NR Neighbor Cell 1 Best Beam Index": "NR Neighbor Cell 1 Best Beam Index",
    "NR Neighbor Cell 1 Cell Type": "NR Neighbor Cell 1 Cell Type",
    "NR Phy Throughput Multi-RAT DL (kbps)": "NR Phy Throughput Multi-RAT DL (kbps)",
    "NR Phy Throughput Multi-RAT UL (kbps)": "NR Phy Throughput Multi-RAT UL (kbps)",
    "NR PDSCH Phy Throughput Total (Kbps)": "NR PDSCH Phy Throughput Total (Kbps)",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)": "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PDSCH Modulation Serving Beam 1": "NR PDSCH Modulation Serving Beam 1",
    "NR PDSCH MCS Serving Beam 1": "NR PDSCH MCS Serving Beam 1",
    "NR PDSCH BLER (%) Serving Beam 1": "NR PDSCH BLER (%) Serving Beam 1",
    "NR PDSCH CQI Serving Beam 1": "NR PDSCH CQI Serving Beam 1",
    "NR PDSCH RI Serving Beam 1": "NR PDSCH RI Serving Beam 1",
    "NR DL Pathloss Serving Beam 1": "NR DL Pathloss Serving Beam 1",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PDSCH Modulation Serving Beam 2": "NR PDSCH Modulation Serving Beam 2",
    "NR PDSCH MCS Serving Beam 2": "NR PDSCH MCS Serving Beam 2",
    "NR PDSCH BLER (%) Serving Beam 2": "NR PDSCH BLER (%) Serving Beam 2",
    "NR PDSCH CQI Serving Beam 2": "NR PDSCH CQI Serving Beam 2",
    "NR PDSCH RI Serving Beam 2": "NR PDSCH RI Serving Beam 2",
    "NR DL Pathloss Serving Beam 2": "NR DL Pathloss Serving Beam 2",
    "NR PUSCH Phy Throughput Total (kbps)": "NR PUSCH Phy Throughput Total (kbps)",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)": "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PUSCH Modulation Serving Beam 1": "NR PUSCH Modulation Serving Beam 1",
    "NR PUSCH MCS Serving Beam 1": "NR PUSCH MCS Serving Beam 1",
    "NR PUSCH BLER (%) Serving Beam 1": "NR PUSCH BLER (%) Serving Beam 1",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PUSCH Modulation Serving Beam 2": "NR PUSCH Modulation Serving Beam 2",
    "NR PUSCH MCS Serving Beam 2": "NR PUSCH MCS Serving Beam 2",
    "NR PUSCH BLER (%) Serving Beam 2": "NR PUSCH BLER (%) Serving Beam 2",
    "NR MAC DL Throughput Total (kbps)": "NR MAC DL Throughput Total (kbps)",
    "NR MAC UL Throughput Total (kbps)": "NR MAC UL Throughput Total (kbps)",
    "NR RLC DL Throughput Total (kbps)": "NR RLC DL Throughput Total (kbps)",
    "NR RLC UL Throughput Total (kbps)": "NR RLC UL Throughput Total (kbps)",
    "NR RLC DL Throughput (Kbps)": "NR RLC DL Throughput (Kbps)",
    "NR RLC UL Throughput (Kbps)": "NR RLC UL Throughput (Kbps)",
    "NR BWP Center NR-ARFCN DL Serving Beam 1": "NR BWP Center NR-ARFCN DL Serving Beam 1",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 1": "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
    "NR BWP ID DL Serving Beam 1": "NR BWP ID DL Serving Beam 1",
    "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)": "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1": "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 1": "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Subcarrier Spacing DL Serving Beam 1": "NR BWP Subcarrier Spacing DL Serving Beam 1",
    "NR BWPs Configured Count DL serving Beam 1": "NR BWPs Configured Count DL serving Beam 1",
    "NR BWP Center NR-ARFCN DL Serving Beam 2": "NR BWP Center NR-ARFCN DL Serving Beam 2",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 2": "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
    "NR BWP ID DL Serving Beam 2": "NR BWP ID DL Serving Beam 2",
    "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)": "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2": "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 2": "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Subcarrier Spacing DL Serving Beam 2": "NR BWP Subcarrier Spacing DL Serving Beam 2",
    "NR BWPs Configured Count DL serving Beam 2": "NR BWPs Configured Count DL serving Beam 2",
    "NR BWP Center NR-ARFCN UL Serving Beam 1": "NR BWP Center NR-ARFCN UL Serving Beam 1",
    "NR BWP Bandwidth UL Serving Beam 1 (Mhz)": "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
    "NR BWP ID UL Serving Beam 1": "NR BWP ID UL Serving Beam 1",
    "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)": "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1": "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 1": "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Subcarrier Spacing UL Serving Beam 1": "NR BWP Subcarrier Spacing UL Serving Beam 1",
    "NR BWPs Configured Count UL Serving Beam 1": "NR BWPs Configured Count UL Serving Beam 1",
    "NR BWP Center NR-ARFCN UL Serving Beam 2": "NR BWP Center NR-ARFCN UL Serving Beam 2",
    "NR BWP Bandwidth UL Serving Beam 2 (Mhz)": "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
    "NR BWP ID UL Serving Beam 2": "NR BWP ID UL Serving Beam 2",
    "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)": "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2": "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 2": "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Subcarrier Spacing UL Serving Beam 2": "NR BWP Subcarrier Spacing UL Serving Beam 2",
    "NR BWPs Configured Count UL Serving Beam 2": "NR BWPs Configured Count UL Serving Beam 2",
    "RadioAccessTechnologyState": "RadioAccessTechnologyState",
    "MR-DC Cell 1 SINR (dB)": "MR-DC Cell 1 SINR (dB)",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1": "PDSCH Average RBs per Allocated Slot Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1": "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
    "PDSCH BWP ID Serving Beam 1": "PDSCH BWP ID Serving Beam 1",
    "PDSCH RB Allocation Count Serving Beam 1": "PDSCH RB Allocation Count Serving Beam 1",
    "PDSCH RB Allocation Count per TB Serving Beam 1": "PDSCH RB Allocation Count per TB Serving Beam 1",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)": "PDSCH RB Allocation Usage Serving Beam 1 (%)",
    "PDSCH RBG Size Serving Beam 1": "PDSCH RBG Size Serving Beam 1",
    "PDSCH Slot Allocation Count Serving Beam 1": "PDSCH Slot Allocation Count Serving Beam 1",
    "PDSCH Slot Allocation Count per TB Serving Beam 1": "PDSCH Slot Allocation Count per TB Serving Beam 1",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)": "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)": "PDSCH Slot Allocation Total Serving Beam 1 (%)",
    "PDSCH Slot Utilization Serving Beam 1 (%)": "PDSCH Slot Utilization Serving Beam 1 (%)",
    "PDSCH RB Dist Current Count Serving Beam 1": "PDSCH RB Dist Current Count Serving Beam 1",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1": "PDSCH RB Utillization Dist Current Count Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2": "PDSCH Average RBs per Allocated Slot Serving Beam 2",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2": "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
    "PDSCH BWP ID Serving Beam 2": "PDSCH BWP ID Serving Beam 2",
    "PDSCH RB Allocation Count Serving Beam 2": "PDSCH RB Allocation Count Serving Beam 2",
    "PDSCH RB Allocation Count per TB Serving Beam 2": "PDSCH RB Allocation Count per TB Serving Beam 2",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)": "PDSCH RB Allocation Usage Serving Beam 2 (%)",
    "PDSCH RBG Size Serving Beam 2": "PDSCH RBG Size Serving Beam 2",
    "PDSCH Slot Allocation Count Serving Beam 2": "PDSCH Slot Allocation Count Serving Beam 2",
    "PDSCH Slot Allocation Count per TB Serving Beam 2": "PDSCH Slot Allocation Count per TB Serving Beam 2",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)": "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)": "PDSCH Slot Allocation Total Serving Beam 2 (%)",
    "PDSCH Slot Utilization Serving Beam 2 (%)": "PDSCH Slot Utilization Serving Beam 2 (%)",
    "PDSCH RB Dist Current Count Serving Beam 2": "PDSCH RB Dist Current Count Serving Beam 2",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2": "PDSCH RB Utillization Dist Current Count Serving Beam 2",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1": "PUSCH Average RBs per Allocated Slot Serving Beam 1",
    "PUSCH BWP ID Serving Beam 1": "PUSCH BWP ID Serving Beam 1",
    "PUSCH RB Allocation Count Serving Beam 1": "PUSCH RB Allocation Count Serving Beam 1",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)": "PUSCH RB Allocation Usage Serving Beam 1 (%)",
    "PUSCH RBG Size Serving Beam 1": "PUSCH RBG Size Serving Beam 1",
    "PUSCH Slot Allocation Count Serving Beam 1": "PUSCH Slot Allocation Count Serving Beam 1",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)": "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)": "PUSCH Slot Allocation Total Serving Beam 1 (%)",
    "PUSCH Slot Utilization Serving Beam 1 (%)": "PUSCH Slot Utilization Serving Beam 1 (%)",
    "PUSCH RB Dist Current Count Serving Beam 1": "PUSCH RB Dist Current Count Serving Beam 1",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1": "PUSCH RB Utillization Dist Current Count Serving Beam 1",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2": "PUSCH Average RBs per Allocated Slot Serving Beam 2",
    "PUSCH BWP ID Serving Beam 2": "PUSCH BWP ID Serving Beam 2",
    "PUSCH RB Allocation Count Serving Beam 2": "PUSCH RB Allocation Count Serving Beam 2",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)": "PUSCH RB Allocation Usage Serving Beam 2 (%)",
    "PUSCH RBG Size Serving Beam 2": "PUSCH RBG Size Serving Beam 2",
    "PUSCH Slot Allocation Count Serving Beam 2": "PUSCH Slot Allocation Count Serving Beam 2",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)": "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)": "PUSCH Slot Allocation Total Serving Beam 2 (%)",
    "PUSCH Slot Utilization Serving Beam 2 (%)": "PUSCH Slot Utilization Serving Beam 2 (%)",
    "PUSCH RB Dist Current Count Serving Beam 2": "PUSCH RB Dist Current Count Serving Beam 2",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2": "PUSCH RB Utillization Dist Current Count Serving Beam 2",
    "Radio Common Throughput DL (kbps)": "Radio Common Throughput DL (kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)": "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)": "LTE PDN Connection AMBR DL (kbps)",
    "FirmwareVersion": "FirmwareVersion",
    "Qualifier": "Qualifier",
    "Time to Transfer 1000 kB": "Time to Transfer 1000 kB",
    "Overall Session Time (s) DNS Request to first 1000kb": "Overall Session Time (s) DNS Request to first 1000kb"


}
df.rename(columns=master_rename_map, inplace=True)



# === Step 3: Define schema groups
schema_groups = {
    "UL": [
        "Date",
        "Time",
        "Test Name",
        "Sequence",
        "Logfile Name",
        "Route Name",
        "Operator",
        "MNC",
        "IMSI",
        "Longitude",
        "Latitude",
        "Type of Mobility",
        "Session Start Time",
        "Session Start Latitude",
        "Session Start Longitude",
        "Session Start Technology",
        "Session Start Data Radio Bearer",
        "Session Start MultiRAT",
        "Session Start TAC",
        "DNS Client",
        "DNS Domain Name",
        "DNS Server Address",
        "DNS Resolved Address",
        "First DNS Request",
        "DNS First In Session",
        "DNS Host Name Resolution Failure Ratio",
        "DNS Host Name Resolution Time (sec)",
        "DNS Host Name Total Resolution Time (sec)",
        "DNS Resolution Success Ratio (%)",
        "HTTP Data Transfer Cutoff",
        "HTTP Data Transfer Time",
        "HTTP Direction",
        "HTTP Error Message",
        "HTTP IP Service Access Failure",
        "HTTP IP Service Setup Time",
        "HTTP Mean Data Rate",
        "HTTP Service Status",
        "HTTP Service Bearer",
        "HTTP URL",
        "HTTP Post Outcome",
        "Seconds Start to End HTTP Post",
        "HTTP Upload Average Throughput",
        "First DNS Request to HTTP Post First Chunk Uploaded (ms)",
        "HTTP Upload Session Failure Ratio",
        "HTTP Upload Session Success Ratio",
        "HTTP Upload Data Transfer Failure Ratio Method A",
        "HTTP Upload Data Transfer Success Ratio Method A",
        "HTTP Upload Data Transfer Time (sec) Method A",
        "HTTP Upload IP Service Access Failure Ratio Method A",
        "HTTP Upload IP Service Setup Success Ratio Method A",
        "HTTP Upload IP Service Setup Time (sec) Method A",
        "HTTP Upload Mean Data Rate kbps Method A",
        "HTTP Upload Data Transfer Failure Ratio Method B",
        "HTTP Upload Data Transfer Success Ratio Method B",
        "HTTP Upload Data Transfer Time (sec) Method B",
        "HTTP Upload IP Service Access Failure Ratio Method B",
        "HTTP Upload IP Service Setup Success Ratio Method B",
        "HTTP Upload IP Service Setup Time (sec) Method B",
        "HTTP Upload Mean Data Rate kbps Method B",
        "IP Interruption Time (ms)",
        "TCP Handshake Time (sec)",
        "TLS Handshake Failure Ratio (%)",
        "Throughput Count Over 1MBit",
        "Throughput Count Over 3MBit",
        "ThroughputPercentageOver3MBit",
        "IE Browse Download Time (ms)",
        "IE Browse Page Size (Bytes)",
        "Session End Time",
        "Session End MultiRAT",
        "Session End Latitude",
        "Session End Longitude",
        "LTE Cell Identity(eNB Part)",
        "LTE Cell Identity(Cell Part)",
        "LTE Serving Cell Identity",
        "LTE Serving Cell DL EARFCN",
        "LTE Serving Cell Frequency Band",
        "LTE Serving Cell Channel RSSI(dBm)",
        "LTE Serving Cell RSRP(dBm)",
        "LTE Serving Cell RS SINR(dB)",
        "LTE Serving Cell RSRQ (dB)",
        "LTE Serving Cell Count Average",
        "LTE secondary Serving Cell 1 Identity",
        "LTE secondary Serving Cell 1 DL EARFCN",
        "LTE secondary Serving Cell 1 Frequency Band",
        "LTE secondary Serving Cell 1 Channel RSSI (dBm)",
        "LTE secondary Serving Cell 1 RSRP (dBm)",
        "LTE secondary Serving Cell 1 RS SINR (dB)",
        "LTE secondary Serving Cell 1 RSRQ (dB)",
        "LTE Neighbor Cell 1 PCI",
        "LTE Neighbor Cell 1 DL EARFCN",
        "LTE Neighbor Cell 1 RSRP",
        "LTE Neighbor Cell 1 RSRQ",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
        "LTE MAC DL Throughput (kbps)",
        "LTE MAC DL Throughput Carrier 1 (kbps)",
        "LTE MAC DL Throughput Carrier 2 (kbps)",
        "LTE MAC DL Throughput Carrier 3 (kbps)",
        "LTE MAC DL Throughput Carrier 4 (kbps)",
        "LTE MAC UL Throughput (kbps)",
        "LTE MAC UL Throughput Carrier 1 (kbps)",
        "LTE MAC UL Throughput Carrier 2 (kbps)",
        "LTE MAC UL Throughput Carrier 3 (kbps)",
        "LTE MAC UL Throughput Carrier 4 (kbps)",
        "LTE PDSCH Modulation",
        "LTE PDSCH MCS",
        "LTE PDSCH BLER (%)",
        "LTE PDSCH Phy Throughput (kbps)",
        "LTE PDSCH Phy Throughput Total (kbps)",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
        "LTE PUSCH Modulation",
        "LTE PUSCH MCS",
        "PUSCH BLER (%)",
        "LTE PUSCH Phy Throughput (kbps)",
        "LTE PUSCH Phy Throughput Total (kbps)",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
        "PUSCH Phy Throughput Carrier 4 (kbps)",
        "LTE RLC Throughput DL (Kbps)",
        "LTE RLC Throughput UL (Kbps)",
        "LTE Bearer Maximum Bitrate DL (kbit/s)",
        "LTE PDN Connection AMBR DL (kbps)",
        "NR Serving Beam 1 Cell Identity",
        "NR Serving Beam 1 NRARFCN DL",
        "NR Serving Beam 1 Band",
        "NR Serving Beam 1 Bandwidth DL",
        "NR Serving Beam 1 Bandwidth UL",
        "NR Serving Beam 1 SSB Index",
        "NR Serving Beam 1 Cell Type",
        "NR Serving Beam 1 GSCN",
        "NR Serving Beam 2 Cell Identity",
        "NR Serving Beam 2 NRARFCN DL",
        "NR Serving Beam 2 Band",
        "NR Serving Beam 2 Bandwidth DL",
        "NR Serving Beam 2 Bandwidth UL",
        "NR Serving Beam 2 SSB Index",
        "NR Serving Beam 2 Cell Type",
        "NR Serving Beam 2 GSCN",
        "NR Serving Cell Identity Top #1",
        "NR Serving Cell NRARFCN DL Top #1",
        "NR Serving Cell SS RSSI Top #1",
        "NR Serving Cell SS RSRP Top #1",
        "NR Serving Cell SS SINR Top #1",
        "NR Serving Cell SS RSRQ Top #1",
        "NR PCell SSB Serving Beam Index Top #1",
        "NR Neighbor Cell 1 Cell Identity",
        "NR Neighbor Cell 1 NRARFCN",
        "NR Neighbor Cell 1 SS RSRP (dBm)",
        "NR Neighbor Cell 1 SS SINR (dB)",
        "NR Neighbor Cell 1 SS RSRQ (dB)",
        "NR Neighbor Cell 1 Best Beam Index",
        "NR Neighbor Cell 1 Cell Type",
        "NR Phy Throughput Multi-RAT DL (kbps)",
        "NR Phy Throughput Multi-RAT UL (kbps)",
        "NR PDSCH Phy Throughput Total (Kbps)",
        "NR Pcell PDSCH Scheduled Throughput (Mbps)",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PDSCH Modulation Serving Beam 1",
        "NR PDSCH MCS Serving Beam 1",
        "NR PDSCH BLER (%) Serving Beam 1",
        "NR PDSCH CQI Serving Beam 1",
        "NR PDSCH RI Serving Beam 1",
        "NR DL Pathloss Serving Beam 1",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PDSCH Modulation Serving Beam 2",
        "NR PDSCH MCS Serving Beam 2",
        "NR PDSCH BLER (%) Serving Beam 2",
        "NR PDSCH CQI Serving Beam 2",
        "NR PDSCH RI Serving Beam 2",
        "NR DL Pathloss Serving Beam 2",
        "NR PUSCH Phy Throughput Total (kbps)",
        "NR Pcell PUSCH Scheduled Throughput (Mbps)",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PUSCH Modulation Serving Beam 1",
        "NR PUSCH MCS Serving Beam 1",
        "NR PUSCH BLER (%) Serving Beam 1",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PUSCH Modulation Serving Beam 2",
        "NR PUSCH MCS Serving Beam 2",
        "NR PUSCH BLER (%) Serving Beam 2",
        "NR MAC DL Throughput Total (kbps)",
        "NR MAC UL Throughput Total (kbps)",
        "NR RLC DL Throughput Total (kbps)",
        "NR RLC UL Throughput Total (kbps)",
        "NR RLC DL Throughput (Kbps)",
        "NR RLC UL Throughput (Kbps)",
        "NR BWP Center NR-ARFCN DL Serving Beam 1",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
        "NR BWP ID DL Serving Beam 1",
        "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Subcarrier Spacing DL Serving Beam 1",
        "NR BWPs Configured Count DL serving Beam 1",
        "NR BWP Center NR-ARFCN DL Serving Beam 2",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
        "NR BWP ID DL Serving Beam 2",
        "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Subcarrier Spacing DL Serving Beam 2",
        "NR BWPs Configured Count DL serving Beam 2",
        "NR BWP Center NR-ARFCN UL Serving Beam 1",
        "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
        "NR BWP ID UL Serving Beam 1",
        "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Subcarrier Spacing UL Serving Beam 1",
        "NR BWPs Configured Count UL Serving Beam 1",
        "NR BWP Center NR-ARFCN UL Serving Beam 2",
        "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
        "NR BWP ID UL Serving Beam 2",
        "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Subcarrier Spacing UL Serving Beam 2",
        "NR BWPs Configured Count UL Serving Beam 2",
        "RadioAccessTechnologyState",
        "MR-DC Cell 1 SINR (dB)",
        "PDSCH Average RBs per Allocated Slot Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
        "PDSCH BWP ID Serving Beam 1",
        "PDSCH RB Allocation Count Serving Beam 1",
        "PDSCH RB Allocation Count per TB Serving Beam 1",
        "PDSCH RB Allocation Usage Serving Beam 1 (%)",
        "PDSCH RBG Size Serving Beam 1",
        "PDSCH Slot Allocation Count Serving Beam 1",
        "PDSCH Slot Allocation Count per TB Serving Beam 1",
        "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PDSCH Slot Allocation Total Serving Beam 1 (%)",
        "PDSCH Slot Utilization Serving Beam 1 (%)",
        "PDSCH RB Dist Current Count Serving Beam 1",
        "PDSCH RB Utillization Dist Current Count Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot Serving Beam 2",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
        "PDSCH BWP ID Serving Beam 2",
        "PDSCH RB Allocation Count Serving Beam 2",
        "PDSCH RB Allocation Count per TB Serving Beam 2",
        "PDSCH RB Allocation Usage Serving Beam 2 (%)",
        "PDSCH RBG Size Serving Beam 2",
        "PDSCH Slot Allocation Count Serving Beam 2",
        "PDSCH Slot Allocation Count per TB Serving Beam 2",
        "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PDSCH Slot Allocation Total Serving Beam 2 (%)",
        "PDSCH Slot Utilization Serving Beam 2 (%)",
        "PDSCH RB Dist Current Count Serving Beam 2",
        "PDSCH RB Utillization Dist Current Count Serving Beam 2",
        "PUSCH Average RBs per Allocated Slot Serving Beam 1",
        "PUSCH BWP ID Serving Beam 1",
        "PUSCH RB Allocation Count Serving Beam 1",
        "PUSCH RB Allocation Usage Serving Beam 1 (%)",
        "PUSCH RBG Size Serving Beam 1",
        "PUSCH Slot Allocation Count Serving Beam 1",
        "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PUSCH Slot Allocation Total Serving Beam 1 (%)",
        "PUSCH Slot Utilization Serving Beam 1 (%)",
        "PUSCH RB Dist Current Count Serving Beam 1",
        "PUSCH RB Utillization Dist Current Count Serving Beam 1",
        "PUSCH Average RBs per Allocated Slot Serving Beam 2",
        "PUSCH BWP ID Serving Beam 2",
        "PUSCH RB Allocation Count Serving Beam 2",
        "PUSCH RB Allocation Usage Serving Beam 2 (%)",
        "PUSCH RBG Size Serving Beam 2",
        "PUSCH Slot Allocation Count Serving Beam 2",
        "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PUSCH Slot Allocation Total Serving Beam 2 (%)",
        "PUSCH Slot Utilization Serving Beam 2 (%)",
        "PUSCH RB Dist Current Count Serving Beam 2",
        "PUSCH RB Utillization Dist Current Count Serving Beam 2",
        "Radio Common Throughput DL (kbps)",
        "FirmwareVersion",
        "Qualifier"


    ],
    "DL": [
        "Date",
        "Time",
        "Test Name",
        "Sequence",
        "Logfile Name",
        "Route Name",
        "Operator",
        "MNC",
        "IMSI",
        "Longitude",
        "Latitude",
        "Type of Mobility",
        "Session Start Time",
        "Session Start Latitude",
        "Session Start Longitude",
        "Session Start Technology",
        "Session Start Data Radio Bearer",
        "Session Start MultiRAT",
        "Session Start TAC",
        "DNS Client",
        "DNS Domain Name",
        "DNS Server Address",
        "DNS Resolved Address",
        "First DNS Request",
        "DNS First In Session",
        "DNS Host Name Resolution Failure Ratio",
        "DNS Host Name Resolution Time (sec)",
        "DNS Host Name Total Resolution Time (sec)",
        "DNS Resolution Success Ratio (%)",
        "First DNS Request to HTTP Get First Chunk Downloaded (ms)",
        "HTTP Data Transfer Cutoff",
        "HTTP Data Transfer Time",
        "HTTP Direction",
        "HTTP Error Message",
        "HTTP IP Service Access Failure",
        "HTTP IP Service Setup Time",
        "HTTP Mean Data Rate",
        "HTTP Service Status",
        "HTTP Service Bearer",
        "HTTP Download Service Average Throughput",
        "HTTP Download Session Failure Ratio",
        "HTTP Download Session Success Ratio",
        "HTTP Error Cause",
        "HTTP Outcome",
        "HTTP URL",
        "Seconds Start to End HTTP",
        "HTTP Download Average Throughput",
        "HTTP Data Transfer Cutoff Ratio (%)",
        "HTTP Download Throughput (kbps)",
        "HTTP Download Data Transfer Failure Ratio Method A",
        "HTTP Download Data Transfer Success Ratio Method A",
        "HTTP Download Data Transfer Time (sec) Method A",
        "HTTP Download IP Service Access Failure Ratio Method A",
        "HTTP Download IP Service Setup Success Ratio Method A",
        "HTTP Download IP Service Setup Time (sec) Method A",
        "HTTP Download Mean Data Rate kbps Method A",
        "HTTP Download Transfer Start Delay Method A",
        "HTTP Download Data Transfer Failure Ratio Method B",
        "HTTP Download Data Transfer Success Ratio Method B",
        "HTTP Download Data Transfer Time (sec) Method B",
        "HTTP Download IP Service Access Failure Ratio Method B",
        "HTTP Download IP Service Setup Success Ratio Method B",
        "HTTP Download IP Service Setup Time (sec) Method B",
        "HTTP Download Mean Data Rate kbps Method B",
        "IP Interruption Time (ms)",
        "TCP Handshake Time (sec)",
        "TLS Handshake Failure Ratio (%)",
        "Throughput Count Over 1MBit",
        "Throughput Count Over 3MBit",
        "ThroughputPercentageOver3MBit",
        "IE Browse Download Time (ms)",
        "IE Browse Page Size (Bytes)",
        "Session End Time",
        "Session End MultiRAT",
        "Session End Latitude",
        "Session End Longitude",
        "LTE Cell Identity(eNB Part)",
        "LTE Cell Identity(Cell Part)",
        "LTE Serving Cell Identity",
        "LTE Serving Cell DL EARFCN",
        "LTE Serving Cell Frequency Band",
        "LTE Serving Cell Channel RSSI(dBm)",
        "LTE Serving Cell RSRP(dBm)",
        "LTE Serving Cell RS SINR(dB)",
        "LTE Serving Cell RSRQ (dB)",
        "LTE Serving Cell Count Average",
        "LTE secondary Serving Cell 1 Identity",
        "LTE secondary Serving Cell 1 DL EARFCN",
        "LTE secondary Serving Cell 1 Frequency Band",
        "LTE secondary Serving Cell 1 Channel RSSI (dBm)",
        "LTE secondary Serving Cell 1 RSRP (dBm)",
        "LTE secondary Serving Cell 1 RS SINR (dB)",
        "LTE secondary Serving Cell 1 RSRQ (dB)",
        "LTE Neighbor Cell 1 PCI",
        "LTE Neighbor Cell 1 DL EARFCN",
        "LTE Neighbor Cell 1 RSRP",
        "LTE Neighbor Cell 1 RSRQ",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
        "LTE MAC DL Throughput (kbps)",
        "LTE MAC DL Throughput Carrier 1 (kbps)",
        "LTE MAC DL Throughput Carrier 2 (kbps)",
        "LTE MAC DL Throughput Carrier 3 (kbps)",
        "LTE MAC DL Throughput Carrier 4 (kbps)",
        "LTE MAC UL Throughput (kbps)",
        "LTE MAC UL Throughput Carrier 1 (kbps)",
        "LTE MAC UL Throughput Carrier 2 (kbps)",
        "LTE MAC UL Throughput Carrier 3 (kbps)",
        "LTE MAC UL Throughput Carrier 4 (kbps)",
        "LTE PDSCH Modulation",
        "LTE PDSCH MCS",
        "LTE PDSCH BLER (%)",
        "LTE PDSCH Phy Throughput (kbps)",
        "LTE PDSCH Phy Throughput Total (kbps)",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
        "LTE PUSCH Modulation",
        "LTE PUSCH MCS",
        "PUSCH BLER (%)",
        "LTE PUSCH Phy Throughput (kbps)",
        "LTE PUSCH Phy Throughput Total (kbps)",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
        "PUSCH Phy Throughput Carrier 4 (kbps)",
        "LTE RLC Throughput DL (Kbps)",
        "LTE RLC Throughput UL (Kbps)",
        "LTE Bearer Maximum Bitrate DL (kbit/s)",
        "LTE PDN Connection AMBR DL (kbps)",
        "NR Serving Beam 1 Cell Identity",
        "NR Serving Beam 1 NRARFCN DL",
        "NR Serving Beam 1 Band",
        "NR Serving Beam 1 Bandwidth DL",
        "NR Serving Beam 1 Bandwidth UL",
        "NR Serving Beam 1 SSB Index",
        "NR Serving Beam 1 Cell Type",
        "NR Serving Beam 1 GSCN",
        "NR Serving Beam 2 Cell Identity",
        "NR Serving Beam 2 NRARFCN DL",
        "NR Serving Beam 2 Band",
        "NR Serving Beam 2 Bandwidth DL",
        "NR Serving Beam 2 Bandwidth UL",
        "NR Serving Beam 2 SSB Index",
        "NR Serving Beam 2 Cell Type",
        "NR Serving Beam 2 GSCN",
        "NR Serving Cell Identity Top #1",
        "NR Serving Cell NRARFCN DL Top #1",
        "NR Serving Cell SS RSSI Top #1",
        "NR Serving Cell SS RSRP Top #1",
        "NR Serving Cell SS SINR Top #1",
        "NR Serving Cell SS RSRQ Top #1",
        "NR PCell SSB Serving Beam Index Top #1",
        "NR Neighbor Cell 1 Cell Identity",
        "NR Neighbor Cell 1 NRARFCN",
        "NR Neighbor Cell 1 SS RSRP (dBm)",
        "NR Neighbor Cell 1 SS SINR (dB)",
        "NR Neighbor Cell 1 SS RSRQ (dB)",
        "NR Neighbor Cell 1 Best Beam Index",
        "NR Neighbor Cell 1 Cell Type",
        "NR Phy Throughput Multi-RAT DL (kbps)",
        "NR Phy Throughput Multi-RAT UL (kbps)",
        "NR PDSCH Phy Throughput Total (Kbps)",
        "NR Pcell PDSCH Scheduled Throughput (Mbps)",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PDSCH Modulation Serving Beam 1",
        "NR PDSCH MCS Serving Beam 1",
        "NR PDSCH BLER (%) Serving Beam 1",
        "NR PDSCH CQI Serving Beam 1",
        "NR PDSCH RI Serving Beam 1",
        "NR DL Pathloss Serving Beam 1",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PDSCH Modulation Serving Beam 2",
        "NR PDSCH MCS Serving Beam 2",
        "NR PDSCH BLER (%) Serving Beam 2",
        "NR PDSCH CQI Serving Beam 2",
        "NR PDSCH RI Serving Beam 2",
        "NR DL Pathloss Serving Beam 2",
        "NR PUSCH Phy Throughput Total (kbps)",
        "NR Pcell PUSCH Scheduled Throughput (Mbps)",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PUSCH Modulation Serving Beam 1",
        "NR PUSCH MCS Serving Beam 1",
        "NR PUSCH BLER (%) Serving Beam 1",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PUSCH Modulation Serving Beam 2",
        "NR PUSCH MCS Serving Beam 2",
        "NR PUSCH BLER (%) Serving Beam 2",
        "NR MAC DL Throughput Total (kbps)",
        "NR MAC UL Throughput Total (kbps)",
        "NR RLC DL Throughput Total (kbps)",
        "NR RLC UL Throughput Total (kbps)",
        "NR RLC DL Throughput (Kbps)",
        "NR RLC UL Throughput (Kbps)",
        "NR BWP Center NR-ARFCN DL Serving Beam 1",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
        "NR BWP ID DL Serving Beam 1",
        "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Subcarrier Spacing DL Serving Beam 1",
        "NR BWPs Configured Count DL serving Beam 1",
        "NR BWP Center NR-ARFCN DL Serving Beam 2",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
        "NR BWP ID DL Serving Beam 2",
        "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Subcarrier Spacing DL Serving Beam 2",
        "NR BWPs Configured Count DL serving Beam 2",
        "NR BWP Center NR-ARFCN UL Serving Beam 1",
        "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
        "NR BWP ID UL Serving Beam 1",
        "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Subcarrier Spacing UL Serving Beam 1",
        "NR BWPs Configured Count UL Serving Beam 1",
        "NR BWP Center NR-ARFCN UL Serving Beam 2",
        "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
        "NR BWP ID UL Serving Beam 2",
        "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Subcarrier Spacing UL Serving Beam 2",
        "NR BWPs Configured Count UL Serving Beam 2",
        "RadioAccessTechnologyState",
        "MR-DC Cell 1 SINR (dB)",
        "PDSCH Average RBs per Allocated Slot Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
        "PDSCH BWP ID Serving Beam 1",
        "PDSCH RB Allocation Count Serving Beam 1",
        "PDSCH RB Allocation Count per TB Serving Beam 1",
        "PDSCH RB Allocation Usage Serving Beam 1 (%)",
        "PDSCH RBG Size Serving Beam 1",
        "PDSCH Slot Allocation Count Serving Beam 1",
        "PDSCH Slot Allocation Count per TB Serving Beam 1",
        "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PDSCH Slot Allocation Total Serving Beam 1 (%)",
        "PDSCH Slot Utilization Serving Beam 1 (%)",
        "PDSCH RB Dist Current Count Serving Beam 1",
        "PDSCH RB Utillization Dist Current Count Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot Serving Beam 2",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
        "PDSCH BWP ID Serving Beam 2",
        "PDSCH RB Allocation Count Serving Beam 2",
        "PDSCH RB Allocation Count per TB Serving Beam 2",
        "PDSCH RB Allocation Usage Serving Beam 2 (%)",
        "PDSCH RBG Size Serving Beam 2",
        "PDSCH Slot Allocation Count Serving Beam 2",
        "PDSCH Slot Allocation Count per TB Serving Beam 2",
        "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PDSCH Slot Allocation Total Serving Beam 2 (%)",
        "PDSCH Slot Utilization Serving Beam 2 (%)",
        "PDSCH RB Dist Current Count Serving Beam 2",
        "PDSCH RB Utillization Dist Current Count Serving Beam 2",
        "PUSCH Average RBs per Allocated Slot Serving Beam 1",
        "PUSCH BWP ID Serving Beam 1",
        "PUSCH RB Allocation Count Serving Beam 1",
        "PUSCH RB Allocation Usage Serving Beam 1 (%)",
        "PUSCH RBG Size Serving Beam 1",
        "PUSCH Slot Allocation Count Serving Beam 1",
        "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PUSCH Slot Allocation Total Serving Beam 1 (%)",
        "PUSCH Slot Utilization Serving Beam 1 (%)",
        "PUSCH RB Dist Current Count Serving Beam 1",
        "PUSCH RB Utillization Dist Current Count Serving Beam 1",
        "PUSCH Average RBs per Allocated Slot Serving Beam 2",
        "PUSCH BWP ID Serving Beam 2",
        "PUSCH RB Allocation Count Serving Beam 2",
        "PUSCH RB Allocation Usage Serving Beam 2 (%)",
        "PUSCH RBG Size Serving Beam 2",
        "PUSCH Slot Allocation Count Serving Beam 2",
        "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PUSCH Slot Allocation Total Serving Beam 2 (%)",
        "PUSCH Slot Utilization Serving Beam 2 (%)",
        "PUSCH RB Dist Current Count Serving Beam 2",
        "PUSCH RB Utillization Dist Current Count Serving Beam 2",
        "Radio Common Throughput DL (kbps)",
        "FirmwareVersion",
        "Qualifier"




    ],
    "BROWSING": [
        "Date",
        "Time",
        "Test Name",
        "Sequence",
        "Logfile Name",
        "Route Name",
        "Operator",
        "MNC",
        "IMSI",
        "Longitude",
        "Latitude",
        "Type of Mobility",
        "Session Start Time",
        "Session Start Latitude",
        "Session Start Longitude",
        "Session Start Technology",
        "Session Start Data Radio Bearer",
        "Session Start MultiRAT",
        "Session Start TAC",
        "DNS Client",
        "DNS Domain Name",
        "DNS Server Address",
        "DNS Resolved Address",
        "First DNS Request",
        "DNS First In Session",
        "DNS Host Name Resolution Failure Ratio",
        "DNS Host Name Resolution Time (sec)",
        "DNS Host Name Total Resolution Time (sec)",
        "DNS Resolution Success Ratio (%)",
        "First DNS Request to HTTP Get First Chunk Downloaded (ms)",
        "HTTP Data Transfer Cutoff",
        "HTTP Data Transfer Time",
        "HTTP Direction",
        "HTTP Error Message",
        "HTTP IP Service Access Failure",
        "HTTP IP Service Setup Time",
        "HTTP Mean Data Rate",
        "HTTP Service Status",
        "HTTP Service Bearer",
        "HTTP Download Service Average Throughput",
        "HTTP Download Session Failure Ratio",
        "HTTP Download Session Success Ratio",
        "HTTP Error Cause",
        "HTTP Outcome",
        "HTTP Technical Browsing Time (sec)",
        "HTTP URL",
        "HTTP User Browsing Time (sec)",
        "Seconds Start to End HTTP",
        "HTTP Download Average Throughput",
        "HTTP Data Transfer Cutoff Ratio (%)",
        "HTTP Download Throughput (kbps)",
        "HTTP Download Data Transfer Failure Ratio Method A",
        "HTTP Download Data Transfer Success Ratio Method A",
        "HTTP Download Data Transfer Time (sec) Method A",
        "HTTP Download IP Service Access Failure Ratio Method A",
        "HTTP Download IP Service Setup Success Ratio Method A",
        "HTTP Download IP Service Setup Time (sec) Method A",
        "HTTP Download Mean Data Rate kbps Method A",
        "HTTP Download Transfer Start Delay Method A",
        "HTTP Download Data Transfer Failure Ratio Method B",
        "HTTP Download Data Transfer Success Ratio Method B",
        "HTTP Download Data Transfer Time (sec) Method B",
        "HTTP Download IP Service Access Failure Ratio Method B",
        "HTTP Download IP Service Setup Success Ratio Method B",
        "HTTP Download IP Service Setup Time (sec) Method B",
        "HTTP Download Mean Data Rate kbps Method B",
        "IP Interruption Time (ms)",
        "TCP Handshake Time (sec)",
        "TLS Handshake Failure Ratio (%)",
        "Throughput Count Over 1MBit",
        "Throughput Count Over 3MBit",
        "ThroughputPercentageOver3MBit",
        "IE Browse Download Time (ms)",
        "IE Browse Page Size (Bytes)",
        "Session End Time",
        "Session End MultiRAT",
        "Session End Latitude",
        "Session End Longitude",
        "LTE Cell Identity(eNB Part)",
        "LTE Cell Identity(Cell Part)",
        "LTE Serving Cell Identity",
        "LTE Serving Cell DL EARFCN",
        "LTE Serving Cell Frequency Band",
        "LTE Serving Cell Channel RSSI(dBm)",
        "LTE Serving Cell RSRP(dBm)",
        "LTE Serving Cell RS SINR(dB)",
        "LTE Serving Cell RSRQ (dB)",
        "LTE Serving Cell Count Average",
        "LTE secondary Serving Cell 1 Identity",
        "LTE secondary Serving Cell 1 DL EARFCN",
        "LTE secondary Serving Cell 1 Frequency Band",
        "LTE secondary Serving Cell 1 Channel RSSI (dBm)",
        "LTE secondary Serving Cell 1 RSRP (dBm)",
        "LTE secondary Serving Cell 1 RS SINR (dB)",
        "LTE secondary Serving Cell 1 RSRQ (dB)",
        "LTE Neighbor Cell 1 PCI",
        "LTE Neighbor Cell 1 DL EARFCN",
        "LTE Neighbor Cell 1 RSRP",
        "LTE Neighbor Cell 1 RSRQ",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
        "LTE MAC DL Throughput (kbps)",
        "LTE MAC DL Throughput Carrier 1 (kbps)",
        "LTE MAC DL Throughput Carrier 2 (kbps)",
        "LTE MAC DL Throughput Carrier 3 (kbps)",
        "LTE MAC DL Throughput Carrier 4 (kbps)",
        "LTE MAC UL Throughput (kbps)",
        "LTE MAC UL Throughput Carrier 1 (kbps)",
        "LTE MAC UL Throughput Carrier 2 (kbps)",
        "LTE MAC UL Throughput Carrier 3 (kbps)",
        "LTE MAC UL Throughput Carrier 4 (kbps)",
        "LTE PDSCH Modulation",
        "LTE PDSCH MCS",
        "LTE PDSCH BLER (%)",
        "LTE PDSCH Phy Throughput (kbps)",
        "LTE PDSCH Phy Throughput Total (kbps)",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
        "LTE PUSCH Modulation",
        "LTE PUSCH MCS",
        "PUSCH BLER (%)",
        "LTE PUSCH Phy Throughput (kbps)",
        "LTE PUSCH Phy Throughput Total (kbps)",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
        "PUSCH Phy Throughput Carrier 4 (kbps)",
        "LTE RLC Throughput DL (Kbps)",
        "LTE RLC Throughput UL (Kbps)",
        "LTE Bearer Maximum Bitrate DL (kbit/s)",
        "LTE PDN Connection AMBR DL (kbps)",
        "NR Serving Beam 1 Cell Identity",
        "NR Serving Beam 1 NRARFCN DL",
        "NR Serving Beam 1 Band",
        "NR Serving Beam 1 Bandwidth DL",
        "NR Serving Beam 1 Bandwidth UL",
        "NR Serving Beam 1 SSB Index",
        "NR Serving Beam 1 Cell Type",
        "NR Serving Beam 1 GSCN",
        "NR Serving Beam 2 Cell Identity",
        "NR Serving Beam 2 NRARFCN DL",
        "NR Serving Beam 2 Band",
        "NR Serving Beam 2 Bandwidth DL",
        "NR Serving Beam 2 Bandwidth UL",
        "NR Serving Beam 2 SSB Index",
        "NR Serving Beam 2 Cell Type",
        "NR Serving Beam 2 GSCN",
        "NR Serving Cell Identity Top #1",
        "NR Serving Cell NRARFCN DL Top #1",
        "NR Serving Cell SS RSSI Top #1",
        "NR Serving Cell SS RSRP Top #1",
        "NR Serving Cell SS SINR Top #1",
        "NR Serving Cell SS RSRQ Top #1",
        "NR PCell SSB Serving Beam Index Top #1",
        "NR Neighbor Cell 1 Cell Identity",
        "NR Neighbor Cell 1 NRARFCN",
        "NR Neighbor Cell 1 SS RSRP (dBm)",
        "NR Neighbor Cell 1 SS SINR (dB)",
        "NR Neighbor Cell 1 SS RSRQ (dB)",
        "NR Neighbor Cell 1 Best Beam Index",
        "NR Neighbor Cell 1 Cell Type",
        "NR Phy Throughput Multi-RAT DL (kbps)",
        "NR Phy Throughput Multi-RAT UL (kbps)",
        "NR PDSCH Phy Throughput Total (Kbps)",
        "NR Pcell PDSCH Scheduled Throughput (Mbps)",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PDSCH Modulation Serving Beam 1",
        "NR PDSCH MCS Serving Beam 1",
        "NR PDSCH BLER (%) Serving Beam 1",
        "NR PDSCH CQI Serving Beam 1",
        "NR PDSCH RI Serving Beam 1",
        "NR DL Pathloss Serving Beam 1",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PDSCH Modulation Serving Beam 2",
        "NR PDSCH MCS Serving Beam 2",
        "NR PDSCH BLER (%) Serving Beam 2",
        "NR PDSCH CQI Serving Beam 2",
        "NR PDSCH RI Serving Beam 2",
        "NR DL Pathloss Serving Beam 2",
        "NR PUSCH Phy Throughput Total (kbps)",
        "NR Pcell PUSCH Scheduled Throughput (Mbps)",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PUSCH Modulation Serving Beam 1",
        "NR PUSCH MCS Serving Beam 1",
        "NR PUSCH BLER (%) Serving Beam 1",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PUSCH Modulation Serving Beam 2",
        "NR PUSCH MCS Serving Beam 2",
        "NR PUSCH BLER (%) Serving Beam 2",
        "NR MAC DL Throughput Total (kbps)",
        "NR MAC UL Throughput Total (kbps)",
        "NR RLC DL Throughput Total (kbps)",
        "NR RLC UL Throughput Total (kbps)",
        "NR RLC DL Throughput (Kbps)",
        "NR RLC UL Throughput (Kbps)",
        "NR BWP Center NR-ARFCN DL Serving Beam 1",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
        "NR BWP ID DL Serving Beam 1",
        "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Subcarrier Spacing DL Serving Beam 1",
        "NR BWPs Configured Count DL serving Beam 1",
        "NR BWP Center NR-ARFCN DL Serving Beam 2",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
        "NR BWP ID DL Serving Beam 2",
        "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Subcarrier Spacing DL Serving Beam 2",
        "NR BWPs Configured Count DL serving Beam 2",
        "NR BWP Center NR-ARFCN UL Serving Beam 1",
        "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
        "NR BWP ID UL Serving Beam 1",
        "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Subcarrier Spacing UL Serving Beam 1",
        "NR BWPs Configured Count UL Serving Beam 1",
        "NR BWP Center NR-ARFCN UL Serving Beam 2",
        "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
        "NR BWP ID UL Serving Beam 2",
        "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Subcarrier Spacing UL Serving Beam 2",
        "NR BWPs Configured Count UL Serving Beam 2",
        "RadioAccessTechnologyState",
        "MR-DC Cell 1 SINR (dB)",
        "PDSCH Average RBs per Allocated Slot Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
        "PDSCH BWP ID Serving Beam 1",
        "PDSCH RB Allocation Count Serving Beam 1",
        "PDSCH RB Allocation Count per TB Serving Beam 1",
        "PDSCH RB Allocation Usage Serving Beam 1 (%)",
        "PDSCH RBG Size Serving Beam 1",
        "PDSCH Slot Allocation Count Serving Beam 1",
        "PDSCH Slot Allocation Count per TB Serving Beam 1",
        "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PDSCH Slot Allocation Total Serving Beam 1 (%)",
        "PDSCH Slot Utilization Serving Beam 1 (%)",
        "PDSCH RB Dist Current Count Serving Beam 1",
        "PDSCH RB Utillization Dist Current Count Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot Serving Beam 2",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
        "PDSCH BWP ID Serving Beam 2",
        "PDSCH RB Allocation Count Serving Beam 2",
        "PDSCH RB Allocation Count per TB Serving Beam 2",
        "PDSCH RB Allocation Usage Serving Beam 2 (%)",
        "PDSCH RBG Size Serving Beam 2",
        "PDSCH Slot Allocation Count Serving Beam 2",
        "PDSCH Slot Allocation Count per TB Serving Beam 2",
        "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PDSCH Slot Allocation Total Serving Beam 2 (%)",
        "PDSCH Slot Utilization Serving Beam 2 (%)",
        "PDSCH RB Dist Current Count Serving Beam 2",
        "PDSCH RB Utillization Dist Current Count Serving Beam 2",
        "PUSCH Average RBs per Allocated Slot Serving Beam 1",
        "PUSCH BWP ID Serving Beam 1",
        "PUSCH RB Allocation Count Serving Beam 1",
        "PUSCH RB Allocation Usage Serving Beam 1 (%)",
        "PUSCH RBG Size Serving Beam 1",
        "PUSCH Slot Allocation Count Serving Beam 1",
        "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PUSCH Slot Allocation Total Serving Beam 1 (%)",
        "PUSCH Slot Utilization Serving Beam 1 (%)",
        "PUSCH RB Dist Current Count Serving Beam 1",
        "PUSCH RB Utillization Dist Current Count Serving Beam 1",
        "PUSCH Average RBs per Allocated Slot Serving Beam 2",
        "PUSCH BWP ID Serving Beam 2",
        "PUSCH RB Allocation Count Serving Beam 2",
        "PUSCH RB Allocation Usage Serving Beam 2 (%)",
        "PUSCH RBG Size Serving Beam 2",
        "PUSCH Slot Allocation Count Serving Beam 2",
        "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PUSCH Slot Allocation Total Serving Beam 2 (%)",
        "PUSCH Slot Utilization Serving Beam 2 (%)",
        "PUSCH RB Dist Current Count Serving Beam 2",
        "PUSCH RB Utillization Dist Current Count Serving Beam 2",
        "Radio Common Throughput DL (kbps)",
        "FirmwareVersion",
        "Qualifier",
        "Time to Transfer 1000 kB",
        "Overall Session Time (s) DNS Request to first 1000kb"


    ]
}

# === Step 4: Map each test name to schema group
testname_to_group = {
    "HTTP FDFS UL": "UL",
    "HTTP FDTT UL": "UL",
    "HTTP FDFS DL": "DL",
    "HTTP FDTT DL": "DL",
    "HTTP BROWSING LIVE": "BROWSING",
    "HTTP BROSWING STATIC": "BROWSING"
}



# === Function to generate Test_IDs column ===
def generate_test_ids(df):
    test_name_codes = {
        "HTTP FDFS DL": 5,
        "HTTP FDFS UL": 6,
        "HTTP FDTT DL": 7,
        "HTTP FDTT UL": 8,
        "HTTP BROWSING LIVE": 9,
        "HTTP BROSWING STATIC": 10
    }

    operator_codes = {
        "Vodafone DE": 1,
        "Telefonica DE": 2,
        "Deutsche Telekom": 3
    }

    df = df.copy()
    df["Test_IDs"] = None

    for (test_name, operator), group in df.groupby(["Test Name", "Operator"]):
        test_code = test_name_codes.get(test_name, 0)
        operator_code = operator_codes.get(operator, 0)

        for i, idx in enumerate(group.index, start=1):
            seq = f"{i:04d}"
            df.at[idx, "Test_IDs"] = f"{test_code}{operator_code}{seq}"

    return df

df = generate_test_ids(df)



# === Step 5: Setup output & log
output_dir = Path("/mnt/c/Users/User/Documents/Indra/geo/CDR/parsing/split/HTTPs/Output2")
output_dir.mkdir(exist_ok=True)
log_path = output_dir / "log.txt"


# === Step 6: Loop and export (one sheet per test_name)
for test_name, test_group in df.groupby("Test Name"):
    group_key = testname_to_group.get(test_name)
    if not group_key:
        continue

    selected_columns = schema_groups[group_key] + ["Test_IDs"]
    
    # Force Test_IDs to 3rd position
    if "Test_IDs" in selected_columns:
        selected_columns.remove("Test_IDs")
        selected_columns.insert(2, "Test_IDs")
    
    # Filter columns
    filtered_group = test_group[selected_columns]

    # === Get info for filename
    first_row = test_group.iloc[0]
    raw_date = pd.to_datetime(first_row.get("Date", pd.NaT), errors='coerce')
    date_str = raw_date.strftime("%Y%m%d") if not pd.isna(raw_date) else "UnknownDate"
    country = str(first_row.get("Route Name", "UnknownCountry")).replace(" ", "_")
    safe_test_name = test_name.replace("/", "-").replace("\\", "-").replace(":", "-").replace(" ", "_")

    output_file_name = f"{date_str}_{country}_BM_CDRData_{safe_test_name}.xlsx"
    file_path = output_dir / output_file_name

    # === Save all rows to a single sheet
    with pd.ExcelWriter(file_path, engine="xlsxwriter") as writer:
        filtered_group.to_excel(writer, sheet_name="AllData", index=False)

    # === Log
    msg = f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] ✅ Saved: {output_file_name} using schema: {group_key}"
    print(msg)
    with open(log_path, "a") as log_file:
        log_file.write(msg + "\n")


