import pandas as pd
from pathlib import Path
from datetime import datetime


# === Load Excel ===
input_folder = Path("/mnt/c/Users/User/Documents/Indra/geo/CDR/parsing/split/Video_Chat/Input")
all_files = list(input_folder.glob("*.xlsx"))

df_list = []

for file_path in all_files:
    xls = pd.ExcelFile(file_path)
    df_sheet = xls.parse(xls.sheet_names[0])
    df_sheet["SourceFile"] = file_path.stem  # Optional: keep track of where each row came from
    df_list.append(df_sheet)

# Combine all into one DataFrame
df = pd.concat(df_list, ignore_index=True)

date_split = df['Date Time'].astype(str).str.split(' ', expand=True)
date_split.columns = ['Date', 'Time']
df = pd.concat([df.drop(columns=['Date Time']), date_split], axis=1)



# === Step 2: Rename columns globally
master_rename_map = {
    "Date Time": "Date",
    "Time": "Time",
    "TWAMP Address": "TWAMP Address",
    "TWAMP Start Time": "Session Start Time",
    "TWAMP End Time": "Session End Time",
    "Test Name": "Test Name",
    "Type Mobility": "Type of Mobility",
    "Operator": "Operator",
    "Country": "Route Name",
    "Sequence": "Sequence",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "Logfile Name": "Logfile Name",
    "IMEI": "IMEI",
    "IMSI": "IMSI",
    "MCC": "MCC",
    "MNC": "MNC",
    "Technology_Detail": "Session Start Technology",
    "Multi RAT Connectivity Mode": "Session Start MultiRAT",
    "RadioAccessTechnologyState": "RadioAccessTechnologyState",
    "TWAMP Start Sessions": "TWAMP Start Sessions",
    "TWAMP Stop Session": "TWAMP Stop Session",
    "TWAMP Operation Start": "TWAMP Operation Start",
    "TWAMP Operation End": "TWAMP Operation End",
    "TWAMP Operation Attempt": "TWAMP Operation Attempt",
    "TWAMP Operation Error": "TWAMP Operation Error",
    "TWAMP Operation Success": "TWAMP Operation Success",
    "TWAMP_Chunk_Interactivity_Score": "TWAMP Chunk Interactivity Score",
    "TWAMP_Packet_Delay_Variation_Median_ms": "TWAMP Packet Delay Variation Median ms",
    "TWAMP_Chunk_Jitter_Average_ms": "TWAMP Chunk Jitter Average ms",
    "TWAMP_Chunk_Jitter_Max_ms": "TWAMP Chunk Jitter Max ms",
    "TWAMP_Chunk_Jitter_Median_ms": "TWAMP Chunk Jitter Median ms",
    "TWAMP_Chunk_Jitter_Min_ms": "TWAMP Chunk Jitter Min ms",
    "TWAMP_Chunk_Jitter_Standard_Deviation_ms": "TWAMP Chunk Jitter Standard Deviation ms",
    "TWAMP_Chunk_Jitter_Variance_ms": "TWAMP Chunk Jitter Variance ms",
    "TWAMP_Jitter_Average_ms": "TWAMP Jitter Average ms",
    "TWAMP_Jitter_Max_ms": "TWAMP Jitter Max ms",
    "TWAMP_Jitter_Median_ms": "TWAMP Jitter Median ms",
    "TWAMP_Jitter_Min_ms": "TWAMP Jitter Min ms",
    "TWAMP_Jitter_Standard_Deviation_ms": "TWAMP Jitter Standard Deviation ms",
    "TWAMP_Jitter_Variance_ms": "TWAMP Jitter Variance ms",
    "TWAMP_Latency_Score": "TWAMP Latency Score",
    "TWAMP_Chunk_Packet_Loss": "TWAMP Chunk Packet Loss",
    "TWAMP_Packet_Loss": "TWAMP Packet Loss",
    "TWAMP_Packet_Loss_Score": "TWAMP Packet Loss Score",
    "TWAMP_Overall_Session_Packet_Loss": "TWAMP Overall Session Packet Loss",
    "TWAMP_Chunk_Rtt_Average_ms": "TWAMP Chunk Rtt Average ms",
    "TWAMP_Chunk_Rtt_Max_ms": "TWAMP Chunk Rtt Max ms",
    "TWAMP_Chunk_Rtt_Median_ms": "TWAMP Chunk Rtt Median ms",
    "TWAMP_Chunk_Rtt_Min_ms": "TWAMP Chunk Rtt Min ms",
    "TWAMP_Chunk_Rtt_Standard_Deviation_ms": "TWAMP Chunk Rtt Standard Deviation ms",
    "TWAMP_Chunk_Rtt_Variance_ms": "TWAMP Chunk Rtt Variance ms",
    "TWAMP_Overall_Session_Rtt_Average_ms": "TWAMP Overall Session Rtt Average ms",
    "TWAMP_Overall_Session_Rtt_Max_ms": "TWAMP Overall Session Rtt Max ms",
    "TWAMP_Overall_Session_Rtt_Median_ms": "TWAMP Overall Session Rtt Median ms",
    "TWAMP_Overall_Session_Rtt_Min_ms": "TWAMP Overall Session Rtt Min ms",
    "TWAMP_Overall_Session_Rtt_Standard_Deviation_ms": "TWAMP Overall Session Rtt Standard Deviation ms",
    "TWAMP_Overall_Session_Rtt_Variance_ms": "TWAMP Overall Session Rtt Variance ms",
    "TWAMP_Rtt_Average_ms": "TWAMP Rtt Average ms",
    "TWAMP_Rtt_Max_ms": "TWAMP Rtt Max ms",
    "TWAMP_Rtt_Median_ms": "TWAMP Rtt Median ms",
    "TWAMP_Rtt_Min_ms": "TWAMP Rtt Min ms",
    "TWAMP_Rtt_Standard_Deviation_ms": "TWAMP Rtt Standard Deviation ms",
    "TWAMP_Rtt_Variance_ms": "TWAMP Rtt Variance ms",
    "TWAMP_Interactivity_Score": "TWAMP Interactivity Score",
    "LTE Cell Identity(eNB Part)": "LTE Cell Identity(eNB Part)",
    "LTE Cell Identity(Cell Part)": "LTE Cell Identity(Cell Part)",
    "LTE Serving Cell Identity": "LTE Serving Cell Identity",
    "LTE Serving Cell DL EARFCN": "LTE Serving Cell DL EARFCN",
    "LTE Serving Cell Frequency Band": "LTE Serving Cell Frequency Band",
    "LTE Serving Cell Channel RSSI(dBm)": "LTE Serving Cell Channel RSSI(dBm)",
    "LTE Serving Cell RSRP(dBm)": "LTE Serving Cell RSRP(dBm)",
    "LTE Serving Cell RS SINR(dB)": "LTE Serving Cell RS SINR(dB)",
    "LTE Serving Cell RSRQ (dB)": "LTE Serving Cell RSRQ (dB)",
    "LTE_Serving_Cell_Count_Average": "LTE Serving Cell Count Average",
    "LTE Secondary Serving Cell 1 Identity": "LTE Secondary Serving Cell 1 Identity",
    "LTE Secondary Serving Cell 1 DL EARFCN": "LTE Secondary Serving Cell 1 DL EARFCN",
    "LTE Secondary Serving Cell 1 Frequency Band": "LTE Secondary Serving Cell 1 Frequency Band",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)": "LTE Secondary Serving Cell 1 Channel RSSI (dBm)",
    "LTE Secondary Serving Cell 1 RSRP (dBm)": "LTE Secondary Serving Cell 1 RSRP (dBm)",
    "LTE Secondary Serving Cell 1 RS SINR (dB)": "LTE Secondary Serving Cell 1 RS SINR (dB)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)": "LTE Secondary Serving Cell 1 RSRQ (dB)",
    "LTE Neighbor Cell 1 PCI": "LTE Neighbor Cell 1 PCI",
    "LTE Neighbor Cell 1 DL EARFCN": "LTE Neighbor Cell 1 DL EARFCN",
    "LTE Neighbor Cell 1 RSRP": "LTE Neighbor Cell 1 RSRP",
    "LTE Neighbor Cell 1 RSRQ": "LTE Neighbor Cell 1 RSRQ",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)": "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "LTE MAC DL Throughput (kbps)": "LTE MAC DL Throughput (kbps)",
    "LTE MAC DL Throughput Carrier 1 (kbps)": "LTE MAC DL Throughput Carrier 1 (kbps)",
    "LTE MAC DL Throughput Carrier 2 (kbps)": "LTE MAC DL Throughput Carrier 2 (kbps)",
    "LTE MAC DL Throughput Carrier 3 (kbps)": "LTE MAC DL Throughput Carrier 3 (kbps)",
    "LTE MAC DL Throughput Carrier 4 (kbps)": "LTE MAC DL Throughput Carrier 4 (kbps)",
    "LTE MAC UL Throughput (kbps)": "LTE MAC UL Throughput (kbps)",
    "LTE MAC UL Throughput Carrier 1 (kbps)": "LTE MAC UL Throughput Carrier 1 (kbps)",
    "LTE MAC UL Throughput Carrier 2 (kbps)": "LTE MAC UL Throughput Carrier 2 (kbps)",
    "LTE MAC UL Throughput Carrier 3 (kbps)": "LTE MAC UL Throughput Carrier 3 (kbps)",
    "LTE MAC UL Throughput Carrier 4 (kbps)": "LTE MAC UL Throughput Carrier 4 (kbps)",
    "LTE PDSCH Modulation": "LTE PDSCH Modulation",
    "LTE PDSCH MCS": "LTE PDSCH MCS",
    "LTE PDSCH BLER (%)": "LTE PDSCH BLER (%)",
    "LTE PDSCH Phy Throughput (kbps)": "LTE PDSCH Phy Throughput (kbps)",
    "LTE PDSCH Phy Throughput Total (kbps)": "LTE PDSCH Phy Throughput Total (kbps)",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)": "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)": "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)": "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)": "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
    "LTE PUSCH Modulation ": "LTE PUSCH Modulation ",
    "LTE PUSCH MCS ": "LTE PUSCH MCS ",
    "PUSCH BLER (%)": "PUSCH BLER (%)",
    "LTE PUSCH Phy Throughput (kbps)": "LTE PUSCH Phy Throughput (kbps)",
    "LTE PUSCH Phy Throughput Total (kbps)": "LTE PUSCH Phy Throughput Total (kbps)",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)": "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)": "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)": "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Phy Throughput Carrier 4 (kbps)": "PUSCH Phy Throughput Carrier 4 (kbps)",
    "LTE RLC Throughput DL (Kbps)": "LTE RLC Throughput DL (Kbps)",
    "LTE RLC Throughput UL (Kbps)": "LTE RLC Throughput UL (Kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)": "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)": "LTE PDN Connection AMBR DL (kbps)",
    "NR Serving Beam 1 Cell Identity": "NR Serving Beam 1 Cell Identity",
    "NR Serving Beam 1 NRARFCN DL": "NR Serving Beam 1 NRARFCN DL",
    "NR Serving Beam 1 Band": "NR Serving Beam 1 Band",
    "NR Serving Beam 1 Bandwidth DL": "NR Serving Beam 1 Bandwidth DL",
    "NR Serving Beam 1 Bandwidth UL": "NR Serving Beam 1 Bandwidth UL",
    "NR Serving Beam 1 SSB Index": "NR Serving Beam 1 SSB Index",
    "NR Serving Beam 1 Cell Type": "NR Serving Beam 1 Cell Type",
    "NR Serving Beam 1 GSCN": "NR Serving Beam 1 GSCN",
    "NR Serving Beam 2 Cell Identity": "NR Serving Beam 2 Cell Identity",
    "NR Serving Beam 2 NRARFCN DL": "NR Serving Beam 2 NRARFCN DL",
    "NR Serving Beam 2 Band": "NR Serving Beam 2 Band",
    "NR Serving Beam 2 Bandwidth DL": "NR Serving Beam 2 Bandwidth DL",
    "NR Serving Beam 2 Bandwidth UL": "NR Serving Beam 2 Bandwidth UL",
    "NR Serving Beam 2 SSB Index": "NR Serving Beam 2 SSB Index",
    "NR Serving Beam 2 Cell Type": "NR Serving Beam 2 Cell Type",
    "NR Serving Beam 2 GSCN": "NR Serving Beam 2 GSCN",
    "NR Serving Cell Identity Top #1": "NR Serving Cell Identity Top #1",
    "NR Serving Cell NRARFCN DL Top #1": "NR Serving Cell NRARFCN DL Top #1",
    "NR Serving Cell SS RSSI Top #1": "NR Serving Cell SS RSSI Top #1",
    "NR Serving Cell SS RSRP Top #1": "NR Serving Cell SS RSRP Top #1",
    "NR Serving Cell SS SINR Top #1": "NR Serving Cell SS SINR Top #1",
    "NR Serving Cell SS RSRQ Top #1": "NR Serving Cell SS RSRQ Top #1",
    "NR PCell SSB Serving Beam Index Top #1": "NR PCell SSB Serving Beam Index Top #1",
    "NR Neighbor Cell 1 Cell Identity": "NR Neighbor Cell 1 Cell Identity",
    "NR Neighbor Cell 1 NRARFCN": "NR Neighbor Cell 1 NRARFCN",
    "NR Neighbor Cell 1 SS RSRP (dBm)": "NR Neighbor Cell 1 SS RSRP (dBm)",
    "NR Neighbor Cell 1 SS SINR (dB)": "NR Neighbor Cell 1 SS SINR (dB)",
    "NR Neighbor Cell 1 SS RSRQ (dB)": "NR Neighbor Cell 1 SS RSRQ (dB)",
    "NR Neighbor Cell 1 Best Beam Index": "NR Neighbor Cell 1 Best Beam Index",
    "NR Neighbor Cell 1 Cell Type": "NR Neighbor Cell 1 Cell Type",
    "NR Phy Throughput Multi-RAT DL (kbps)": "NR Phy Throughput Multi-RAT DL (kbps)",
    "NR Phy Throughput Multi-RAT UL (kbps)": "NR Phy Throughput Multi-RAT UL (kbps)",
    "NR PDSCH Phy Throughput Total (Kbps)": "NR PDSCH Phy Throughput Total (Kbps)",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)": "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PDSCH Modulation Serving Beam 1": "NR PDSCH Modulation Serving Beam 1",
    "NR PDSCH MCS Serving Beam 1": "NR PDSCH MCS Serving Beam 1",
    "NR PDSCH BLER (%) Serving Beam 1": "NR PDSCH BLER (%) Serving Beam 1",
    "NR PDSCH CQI Serving Beam 1": "NR PDSCH CQI Serving Beam 1",
    "NR PDSCH RI Serving Beam 1": "NR PDSCH RI Serving Beam 1",
    "NR DL Pathloss Serving Beam 1": "NR DL Pathloss Serving Beam 1",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PDSCH Modulation Serving Beam 2": "NR PDSCH Modulation Serving Beam 2",
    "NR PDSCH MCS Serving Beam 2": "NR PDSCH MCS Serving Beam 2",
    "NR PDSCH BLER (%) Serving Beam 2": "NR PDSCH BLER (%) Serving Beam 2",
    "NR PDSCH CQI Serving Beam 2": "NR PDSCH CQI Serving Beam 2",
    "NR PDSCH RI Serving Beam 2": "NR PDSCH RI Serving Beam 2",
    "NR DL Pathloss Serving Beam 2": "NR DL Pathloss Serving Beam 2",
    "NR PUSCH Phy Throughput Total (kbps)": "NR PUSCH Phy Throughput Total (kbps)",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)": "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PUSCH Modulation Serving Beam 1": "NR PUSCH Modulation Serving Beam 1",
    "NR PUSCH MCS Serving Beam 1": "NR PUSCH MCS Serving Beam 1",
    "NR PUSCH BLER (%) Serving Beam 1": "NR PUSCH BLER (%) Serving Beam 1",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PUSCH Modulation Serving Beam 2": "NR PUSCH Modulation Serving Beam 2",
    "NR PUSCH MCS Serving Beam 2": "NR PUSCH MCS Serving Beam 2",
    "NR PUSCH BLER (%) Serving Beam 2": "NR PUSCH BLER (%) Serving Beam 2",
    "NR MAC DL Throughput Total (kbps)": "NR MAC DL Throughput Total (kbps)",
    "NR MAC UL Throughput Total (kbps)": "NR MAC UL Throughput Total (kbps)",
    "NR RLC DL Throughput Total (kbps)": "NR RLC DL Throughput Total (kbps)",
    "NR RLC UL Throughput Total (kbps)": "NR RLC UL Throughput Total (kbps)",
    "NR RLC DL Throughput (Kbps)": "NR RLC DL Throughput (Kbps)",
    "NR RLC UL Throughput (Kbps)": "NR RLC UL Throughput (Kbps)",
    "NR BWP Center NR-ARFCN DL Serving Beam 1": "NR BWP Center NR-ARFCN DL Serving Beam 1",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 1": "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
    "NR BWP ID DL Serving Beam 1": "NR BWP ID DL Serving Beam 1",
    "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)": "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1": "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 1": "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Subcarrier Spacing DL Serving Beam 1": "NR BWP Subcarrier Spacing DL Serving Beam 1",
    "NR BWPs Configured Count DL serving Beam 1": "NR BWPs Configured Count DL serving Beam 1",
    "NR BWP Center NR-ARFCN DL Serving Beam 2": "NR BWP Center NR-ARFCN DL Serving Beam 2",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 2": "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
    "NR BWP ID DL Serving Beam 2": "NR BWP ID DL Serving Beam 2",
    "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)": "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2": "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 2": "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Subcarrier Spacing DL Serving Beam 2": "NR BWP Subcarrier Spacing DL Serving Beam 2",
    "NR BWPs Configured Count DL serving Beam 2": "NR BWPs Configured Count DL serving Beam 2",
    "NR BWP Center NR-ARFCN UL Serving Beam 1": "NR BWP Center NR-ARFCN UL Serving Beam 1",
    "NR BWP Bandwidth UL Serving Beam 1 (Mhz)": "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
    "NR BWP ID UL Serving Beam 1": "NR BWP ID UL Serving Beam 1",
    "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)": "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1": "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 1": "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Subcarrier Spacing UL Serving Beam 1": "NR BWP Subcarrier Spacing UL Serving Beam 1",
    "NR BWPs Configured Count UL Serving Beam 1": "NR BWPs Configured Count UL Serving Beam 1",
    "NR BWP Center NR-ARFCN UL Serving Beam 2": "NR BWP Center NR-ARFCN UL Serving Beam 2",
    "NR BWP Bandwidth UL Serving Beam 2 (Mhz)": "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
    "NR BWP ID UL Serving Beam 2": "NR BWP ID UL Serving Beam 2",
    "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)": "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2": "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 2": "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Subcarrier Spacing UL Serving Beam 2": "NR BWP Subcarrier Spacing UL Serving Beam 2",
    "NR BWPs Configured Count UL Serving Beam 2": "NR BWPs Configured Count UL Serving Beam 2",
    "RadioAccessTechnologyState": "RadioAccessTechnologyState",
    "MR-DC Cell 1 SINR (dB)": "MR-DC Cell 1 SINR (dB)",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1": "PDSCH Average RBs per Allocated Slot Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1": "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
    "PDSCH BWP ID Serving Beam 1": "PDSCH BWP ID Serving Beam 1",
    "PDSCH RB Allocation Count Serving Beam 1": "PDSCH RB Allocation Count Serving Beam 1",
    "PDSCH RB Allocation Count per TB Serving Beam 1": "PDSCH RB Allocation Count per TB Serving Beam 1",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)": "PDSCH RB Allocation Usage Serving Beam 1 (%)",
    "PDSCH RBG Size Serving Beam 1": "PDSCH RBG Size Serving Beam 1",
    "PDSCH Slot Allocation Count Serving Beam 1": "PDSCH Slot Allocation Count Serving Beam 1",
    "PDSCH Slot Allocation Count per TB Serving Beam 1": "PDSCH Slot Allocation Count per TB Serving Beam 1",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)": "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)": "PDSCH Slot Allocation Total Serving Beam 1 (%)",
    "PDSCH Slot Utilization Serving Beam 1 (%)": "PDSCH Slot Utilization Serving Beam 1 (%)",
    "PDSCH RB Dist Current Count Serving Beam 1": "PDSCH RB Dist Current Count Serving Beam 1",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1": "PDSCH RB Utillization Dist Current Count Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2": "PDSCH Average RBs per Allocated Slot Serving Beam 2",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2": "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
    "PDSCH BWP ID Serving Beam 2": "PDSCH BWP ID Serving Beam 2",
    "PDSCH RB Allocation Count Serving Beam 2": "PDSCH RB Allocation Count Serving Beam 2",
    "PDSCH RB Allocation Count per TB Serving Beam 2": "PDSCH RB Allocation Count per TB Serving Beam 2",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)": "PDSCH RB Allocation Usage Serving Beam 2 (%)",
    "PDSCH RBG Size Serving Beam 2": "PDSCH RBG Size Serving Beam 2",
    "PDSCH Slot Allocation Count Serving Beam 2": "PDSCH Slot Allocation Count Serving Beam 2",
    "PDSCH Slot Allocation Count per TB Serving Beam 2": "PDSCH Slot Allocation Count per TB Serving Beam 2",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)": "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)": "PDSCH Slot Allocation Total Serving Beam 2 (%)",
    "PDSCH Slot Utilization Serving Beam 2 (%)": "PDSCH Slot Utilization Serving Beam 2 (%)",
    "PDSCH RB Dist Current Count Serving Beam 2": "PDSCH RB Dist Current Count Serving Beam 2",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2": "PDSCH RB Utillization Dist Current Count Serving Beam 2",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1": "PUSCH Average RBs per Allocated Slot Serving Beam 1",
    "PUSCH BWP ID Serving Beam 1": "PUSCH BWP ID Serving Beam 1",
    "PUSCH RB Allocation Count Serving Beam 1": "PUSCH RB Allocation Count Serving Beam 1",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)": "PUSCH RB Allocation Usage Serving Beam 1 (%)",
    "PUSCH RBG Size Serving Beam 1": "PUSCH RBG Size Serving Beam 1",
    "PUSCH Slot Allocation Count Serving Beam 1": "PUSCH Slot Allocation Count Serving Beam 1",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)": "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)": "PUSCH Slot Allocation Total Serving Beam 1 (%)",
    "PUSCH Slot Utilization Serving Beam 1 (%)": "PUSCH Slot Utilization Serving Beam 1 (%)",
    "PUSCH RB Dist Current Count Serving Beam 1": "PUSCH RB Dist Current Count Serving Beam 1",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1": "PUSCH RB Utillization Dist Current Count Serving Beam 1",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2": "PUSCH Average RBs per Allocated Slot Serving Beam 2",
    "PUSCH BWP ID Serving Beam 2": "PUSCH BWP ID Serving Beam 2",
    "PUSCH RB Allocation Count Serving Beam 2": "PUSCH RB Allocation Count Serving Beam 2",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)": "PUSCH RB Allocation Usage Serving Beam 2 (%)",
    "PUSCH RBG Size Serving Beam 2": "PUSCH RBG Size Serving Beam 2",
    "PUSCH Slot Allocation Count Serving Beam 2": "PUSCH Slot Allocation Count Serving Beam 2",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)": "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)": "PUSCH Slot Allocation Total Serving Beam 2 (%)",
    "PUSCH Slot Utilization Serving Beam 2 (%)": "PUSCH Slot Utilization Serving Beam 2 (%)",
    "PUSCH RB Dist Current Count Serving Beam 2": "PUSCH RB Dist Current Count Serving Beam 2",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2": "PUSCH RB Utillization Dist Current Count Serving Beam 2",
    "Radio Common Throughput DL (kbps)": "Radio Common Throughput DL (kbps)",
    "FirmwareVersion": "FirmwareVersion",
    "Qualifier": "Qualifier",
    "TWAMP_Packet_Delay_Variation_Score": "TWAMP Packet Delay Variation Score",
    "TWAMP_Packet_Delay_Variation_Standard_Deviation": "TWAMP Packet Delay Variation Standard Deviation",
    "end_latitude": "End Latitude",
    "end_longitude": "End Longitude"



}
df.rename(columns=master_rename_map, inplace=True)



# === Step 3: Define schema groups
schema_groups = {
    "VideoChat": [
        "Date",
        "Time",
        "Test Name",
        "Sequence",
        "Logfile Name",
        "Route Name",
        "Operator",
        "Type of Mobility",
        "IMEI",
        "IMSI",
        "MCC",
        "MNC",
        "Session Start Time",
        "Latitude",
        "Longitude",
        "Session End Time",
        "End Latitude",
        "End Longitude",
        "Session Start Technology",
        "Session Start MultiRAT",
        "TWAMP Address",
        "TWAMP Start Sessions",
        "TWAMP Operation Start",
        "TWAMP Operation Attempt",
        "TWAMP Operation Error",
        "TWAMP Operation Success",
        "TWAMP Interactivity Score",
        "TWAMP Chunk Interactivity Score",
        "TWAMP Packet Delay Variation Median ms",
        "TWAMP Packet Delay Variation Score",
        "TWAMP Packet Delay Variation Standard Deviation",
        "TWAMP Chunk Jitter Average ms",
        "TWAMP Chunk Jitter Max ms",
        "TWAMP Chunk Jitter Median ms",
        "TWAMP Chunk Jitter Min ms",
        "TWAMP Chunk Jitter Standard Deviation ms",
        "TWAMP Chunk Jitter Variance ms",
        "TWAMP Jitter Average ms",
        "TWAMP Jitter Max ms",
        "TWAMP Jitter Median ms",
        "TWAMP Jitter Min ms",
        "TWAMP Jitter Standard Deviation ms",
        "TWAMP Jitter Variance ms",
        "TWAMP Latency Score",
        "TWAMP Chunk Packet Loss",
        "TWAMP Packet Loss",
        "TWAMP Packet Loss Score",
        "TWAMP Overall Session Packet Loss",
        "TWAMP Chunk Rtt Average ms",
        "TWAMP Chunk Rtt Max ms",
        "TWAMP Chunk Rtt Median ms",
        "TWAMP Chunk Rtt Min ms",
        "TWAMP Chunk Rtt Standard Deviation ms",
        "TWAMP Chunk Rtt Variance ms",
        "TWAMP Overall Session Rtt Average ms",
        "TWAMP Overall Session Rtt Max ms",
        "TWAMP Overall Session Rtt Median ms",
        "TWAMP Overall Session Rtt Min ms",
        "TWAMP Overall Session Rtt Standard Deviation ms",
        "TWAMP Overall Session Rtt Variance ms",
        "TWAMP Rtt Average ms",
        "TWAMP Rtt Max ms",
        "TWAMP Rtt Median ms",
        "TWAMP Rtt Min ms",
        "TWAMP Rtt Standard Deviation ms",
        "TWAMP Rtt Variance ms",
        "TWAMP Stop Session",
        "TWAMP Operation End",
        "LTE Cell Identity(eNB Part)",
        "LTE Cell Identity(Cell Part)",
        "LTE Serving Cell Identity",
        "LTE Serving Cell DL EARFCN",
        "LTE Serving Cell Frequency Band",
        "LTE Serving Cell Channel RSSI(dBm)",
        "LTE Serving Cell RSRP(dBm)",
        "LTE Serving Cell RS SINR(dB)",
        "LTE Serving Cell RSRQ (dB)",
        "LTE Serving Cell Count Average",
        "LTE Secondary Serving Cell 1 Identity",
        "LTE Secondary Serving Cell 1 DL EARFCN",
        "LTE Secondary Serving Cell 1 Frequency Band",
        "LTE Secondary Serving Cell 1 Channel RSSI (dBm)",
        "LTE Secondary Serving Cell 1 RSRP (dBm)",
        "LTE Secondary Serving Cell 1 RS SINR (dB)",
        "LTE Secondary Serving Cell 1 RSRQ (dB)",
        "LTE Neighbor Cell 1 PCI",
        "LTE Neighbor Cell 1 DL EARFCN",
        "LTE Neighbor Cell 1 RSRP",
        "LTE Neighbor Cell 1 RSRQ",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
        "LTE MAC DL Throughput (kbps)",
        "LTE MAC DL Throughput Carrier 1 (kbps)",
        "LTE MAC DL Throughput Carrier 2 (kbps)",
        "LTE MAC DL Throughput Carrier 3 (kbps)",
        "LTE MAC DL Throughput Carrier 4 (kbps)",
        "LTE MAC UL Throughput (kbps)",
        "LTE MAC UL Throughput Carrier 1 (kbps)",
        "LTE MAC UL Throughput Carrier 2 (kbps)",
        "LTE MAC UL Throughput Carrier 3 (kbps)",
        "LTE MAC UL Throughput Carrier 4 (kbps)",
        "LTE PDSCH Modulation",
        "LTE PDSCH MCS",
        "LTE PDSCH BLER (%)",
        "LTE PDSCH Phy Throughput (kbps)",
        "LTE PDSCH Phy Throughput Total (kbps)",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
        "LTE PUSCH Modulation ",
        "LTE PUSCH MCS ",
        "PUSCH BLER (%)",
        "LTE PUSCH Phy Throughput (kbps)",
        "LTE PUSCH Phy Throughput Total (kbps)",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
        "PUSCH Phy Throughput Carrier 4 (kbps)",
        "LTE RLC Throughput DL (Kbps)",
        "LTE RLC Throughput UL (Kbps)",
        "LTE Bearer Maximum Bitrate DL (kbit/s)",
        "LTE PDN Connection AMBR DL (kbps)",
        "NR Serving Beam 1 Cell Identity",
        "NR Serving Beam 1 NRARFCN DL",
        "NR Serving Beam 1 Band",
        "NR Serving Beam 1 Bandwidth DL",
        "NR Serving Beam 1 Bandwidth UL",
        "NR Serving Beam 1 SSB Index",
        "NR Serving Beam 1 Cell Type",
        "NR Serving Beam 1 GSCN",
        "NR Serving Beam 2 Cell Identity",
        "NR Serving Beam 2 NRARFCN DL",
        "NR Serving Beam 2 Band",
        "NR Serving Beam 2 Bandwidth DL",
        "NR Serving Beam 2 Bandwidth UL",
        "NR Serving Beam 2 SSB Index",
        "NR Serving Beam 2 Cell Type",
        "NR Serving Beam 2 GSCN",
        "NR Serving Cell Identity Top #1",
        "NR Serving Cell NRARFCN DL Top #1",
        "NR Serving Cell SS RSSI Top #1",
        "NR Serving Cell SS RSRP Top #1",
        "NR Serving Cell SS SINR Top #1",
        "NR Serving Cell SS RSRQ Top #1",
        "NR PCell SSB Serving Beam Index Top #1",
        "NR Neighbor Cell 1 Cell Identity",
        "NR Neighbor Cell 1 NRARFCN",
        "NR Neighbor Cell 1 SS RSRP (dBm)",
        "NR Neighbor Cell 1 SS SINR (dB)",
        "NR Neighbor Cell 1 SS RSRQ (dB)",
        "NR Neighbor Cell 1 Best Beam Index",
        "NR Neighbor Cell 1 Cell Type",
        "NR Phy Throughput Multi-RAT DL (kbps)",
        "NR Phy Throughput Multi-RAT UL (kbps)",
        "NR PDSCH Phy Throughput Total (Kbps)",
        "NR Pcell PDSCH Scheduled Throughput (Mbps)",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PDSCH Modulation Serving Beam 1",
        "NR PDSCH MCS Serving Beam 1",
        "NR PDSCH BLER (%) Serving Beam 1",
        "NR PDSCH CQI Serving Beam 1",
        "NR PDSCH RI Serving Beam 1",
        "NR DL Pathloss Serving Beam 1",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PDSCH Modulation Serving Beam 2",
        "NR PDSCH MCS Serving Beam 2",
        "NR PDSCH BLER (%) Serving Beam 2",
        "NR PDSCH CQI Serving Beam 2",
        "NR PDSCH RI Serving Beam 2",
        "NR DL Pathloss Serving Beam 2",
        "NR PUSCH Phy Throughput Total (kbps)",
        "NR Pcell PUSCH Scheduled Throughput (Mbps)",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PUSCH Modulation Serving Beam 1",
        "NR PUSCH MCS Serving Beam 1",
        "NR PUSCH BLER (%) Serving Beam 1",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PUSCH Modulation Serving Beam 2",
        "NR PUSCH MCS Serving Beam 2",
        "NR PUSCH BLER (%) Serving Beam 2",
        "NR MAC DL Throughput Total (kbps)",
        "NR MAC UL Throughput Total (kbps)",
        "NR RLC DL Throughput Total (kbps)",
        "NR RLC UL Throughput Total (kbps)",
        "NR RLC DL Throughput (Kbps)",
        "NR RLC UL Throughput (Kbps)",
        "NR BWP Center NR-ARFCN DL Serving Beam 1",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
        "NR BWP ID DL Serving Beam 1",
        "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Subcarrier Spacing DL Serving Beam 1",
        "NR BWPs Configured Count DL serving Beam 1",
        "NR BWP Center NR-ARFCN DL Serving Beam 2",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
        "NR BWP ID DL Serving Beam 2",
        "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Subcarrier Spacing DL Serving Beam 2",
        "NR BWPs Configured Count DL serving Beam 2",
        "NR BWP Center NR-ARFCN UL Serving Beam 1",
        "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
        "NR BWP ID UL Serving Beam 1",
        "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Subcarrier Spacing UL Serving Beam 1",
        "NR BWPs Configured Count UL Serving Beam 1",
        "NR BWP Center NR-ARFCN UL Serving Beam 2",
        "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
        "NR BWP ID UL Serving Beam 2",
        "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Subcarrier Spacing UL Serving Beam 2",
        "NR BWPs Configured Count UL Serving Beam 2",
        "RadioAccessTechnologyState",
        "MR-DC Cell 1 SINR (dB)",
        "PDSCH Average RBs per Allocated Slot Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
        "PDSCH BWP ID Serving Beam 1",
        "PDSCH RB Allocation Count Serving Beam 1",
        "PDSCH RB Allocation Count per TB Serving Beam 1",
        "PDSCH RB Allocation Usage Serving Beam 1 (%)",
        "PDSCH RBG Size Serving Beam 1",
        "PDSCH Slot Allocation Count Serving Beam 1",
        "PDSCH Slot Allocation Count per TB Serving Beam 1",
        "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PDSCH Slot Allocation Total Serving Beam 1 (%)",
        "PDSCH Slot Utilization Serving Beam 1 (%)",
        "PDSCH RB Dist Current Count Serving Beam 1",
        "PDSCH RB Utillization Dist Current Count Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot Serving Beam 2",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
        "PDSCH BWP ID Serving Beam 2",
        "PDSCH RB Allocation Count Serving Beam 2",
        "PDSCH RB Allocation Count per TB Serving Beam 2",
        "PDSCH RB Allocation Usage Serving Beam 2 (%)",
        "PDSCH RBG Size Serving Beam 2",
        "PDSCH Slot Allocation Count Serving Beam 2",
        "PDSCH Slot Allocation Count per TB Serving Beam 2",
        "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PDSCH Slot Allocation Total Serving Beam 2 (%)",
        "PDSCH Slot Utilization Serving Beam 2 (%)",
        "PDSCH RB Dist Current Count Serving Beam 2",
        "PDSCH RB Utillization Dist Current Count Serving Beam 2",
        "PUSCH Average RBs per Allocated Slot Serving Beam 1",
        "PUSCH BWP ID Serving Beam 1",
        "PUSCH RB Allocation Count Serving Beam 1",
        "PUSCH RB Allocation Usage Serving Beam 1 (%)",
        "PUSCH RBG Size Serving Beam 1",
        "PUSCH Slot Allocation Count Serving Beam 1",
        "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PUSCH Slot Allocation Total Serving Beam 1 (%)",
        "PUSCH Slot Utilization Serving Beam 1 (%)",
        "PUSCH RB Dist Current Count Serving Beam 1",
        "PUSCH RB Utillization Dist Current Count Serving Beam 1",
        "PUSCH Average RBs per Allocated Slot Serving Beam 2",
        "PUSCH BWP ID Serving Beam 2",
        "PUSCH RB Allocation Count Serving Beam 2",
        "PUSCH RB Allocation Usage Serving Beam 2 (%)",
        "PUSCH RBG Size Serving Beam 2",
        "PUSCH Slot Allocation Count Serving Beam 2",
        "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PUSCH Slot Allocation Total Serving Beam 2 (%)",
        "PUSCH Slot Utilization Serving Beam 2 (%)",
        "PUSCH RB Dist Current Count Serving Beam 2",
        "PUSCH RB Utillization Dist Current Count Serving Beam 2",
        "Radio Common Throughput DL (kbps)",
        "FirmwareVersion",
        "Qualifier"


 

   ]
}

# === Step 4: Map each test name to schema group
testname_to_group = {
    "Data_VideoChat": "VideoChat",
   
    
    
}



# === Function to generate Test_IDs column ===
def generate_test_ids(df):
    test_name_codes = {
        "HTTP FDFS DL": 5,
        "HTTP FDFS UL": 6,
        "HTTP FDTT DL": 7,
        "HTTP FDTT UL": 8,
        "HTTP BROWSING LIVE": 9,
        "HTTP BROSWING STATIC": 10,
        "YoutubeVOD": 11,
        "YoutubeLIVE": 11,
        "Ping 800": 14,
        "Ping 40": 14,
        "DNS": 15,
        "Data_VideoChat": 13

    }

    operator_codes = {
        "Vodafone DE": 1,
        "Telefonica DE": 2,
        "Deutsche Telekom": 3
    }

    df = df.copy()
    df["Test_IDs"] = None

    for (test_name, operator), group in df.groupby(["Test Name", "Operator"]):
        test_code = test_name_codes.get(test_name, 0)
        operator_code = operator_codes.get(operator, 0)

        for i, idx in enumerate(group.index, start=1):
            seq = f"{i:04d}"
            df.at[idx, "Test_IDs"] = f"{test_code}{operator_code}{seq}"

    return df

df = generate_test_ids(df)



# === Step 5: Setup output & log
output_dir = Path("/mnt/c/Users/User/Documents/Indra/geo/CDR/parsing/split/Video_Chat/Output2")
output_dir.mkdir(exist_ok=True)
log_path = output_dir / "log.txt"





# === Step 6: Prepare metadata and filename ===
first_row = df.iloc[0]
raw_date = pd.to_datetime(first_row.get("Date", pd.NaT), errors='coerce')
date_str = raw_date.strftime("%Y%m%d") if not pd.isna(raw_date) else "UnknownDate"
country = str(first_row.get("Route Name", "UnknownCountry")).replace(" ", "_")
test_name = str(first_row.get("Test Name", "UnknownTest")).replace("/", "-").replace("\\", "-").replace(":", "-").replace(" ", "_")

group_key = testname_to_group.get(test_name)
if not group_key:
    group_key = "VideoChat"  # fallback default

selected_columns = schema_groups[group_key] + ["Test_IDs"]
if "Test_IDs" in selected_columns:
    selected_columns.remove("Test_IDs")
    selected_columns.insert(2, "Test_IDs")

# === Final file path
output_file_name = f"{date_str}_{country}_BM_CDRData_VideoChat.xlsx"
file_path = output_dir / output_file_name

# === Filter and write to one sheet only
filtered_df = df[selected_columns]

with pd.ExcelWriter(file_path, engine="xlsxwriter") as writer:
    filtered_df.to_excel(writer, sheet_name="AllData", index=False)

# === Logging
msg = f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] ✅ Saved: {output_file_name} with all data in one sheet"
print(msg)
with open(log_path, "a") as log_file:
    log_file.write(msg + "\n")

