import pandas as pd
from pathlib import Path
from datetime import datetime


# === Load Excel ===
input_folder = Path("/mnt/c/Users/User/Documents/Indra/geo/CDR/parsing/split/Voice_OTT/Input")
all_files = list(input_folder.glob("*.xlsx"))

df_list = []

for file_path in all_files:
    xls = pd.ExcelFile(file_path)
    df_sheet = xls.parse(xls.sheet_names[0])
    df_sheet["SourceFile"] = file_path.stem  # Optional: keep track of where each row came from
    df_list.append(df_sheet)

# Combine all into one DataFrame
df = pd.concat(df_list, ignore_index=True)

date_split = df['Date Time'].astype(str).str.split(' ', expand=True)
date_split.columns = ['Date', 'Time']
df = pd.concat([df.drop(columns=['Date Time']), date_split], axis=1)

df = pd.concat([
    df,
    df[["Latitude"]].rename(columns={"Latitude": "End Latitude"})
], axis=1)

df = pd.concat([
    df,
    df[["Longitude"]].rename(columns={"Longitude": "End Longitude"})
], axis=1)

# Separate rows for Side A and Side B
side_a_df = df[df['Side'] == 'Side A'].reset_index(drop=True)
side_b_df = df[df['Side'] == 'Side B'].reset_index(drop=True)



# Merge Side A and Side B on 'Test Id' and 'index_id'
merged_df = pd.merge(
    side_a_df,
    side_b_df,
    on='Pair_ID',
    how='left',
    suffixes=('', '_B')
)

master_rename_map = {
        "VoiceStartTime": "VoiceStartTime Side A",
        "VoiceEndTime": "VoiceEndTime Side A",
        "Test Name": "Test Name",
        "Type Mobility": "Type of Mobility",
        "DeviceDescription": "DeviceDescription A",
        "VoiceLogfileName": "Logfile Name Side A",
        "Operator": "Operator",
        "Country": "Route Name",
        "Sequence": "Sequence A",
        "Latitude": "Latitude",
        "Longitude": "Longitude",
        "EventName": "Event Name Side A",
        "IMEI": "IMEI Side A",
        "IMSI": "IMSI Side A",
        "MCC": "MCC",
        "MNC": "MNC",
        "TAC": "TAC A",
        "Technology_Detail": "Technology Detail A",
        "PhoneNumber": "Phone Number A",
        "Dialed Number": "Dialed Number A",
        "Call_Status": "Call Status A",
        "Call_Type": "Call Type A",
        "Call_Number": "Call Number A",
        "MO_Call_Domain": "MO Call Domain A",
        "MO_Call_Setup_Time_ms": "MO Call Setup Time (ms) A",
        "MO_Call_User_Setup_Time_ms": "MO Call User Setup Time (ms) A",
        "MOCallDropRate": "MO Call Drop Rate A",
        "MOCallSetupFailureRate": "MO Call Setup Failure Rate A",
        "MT_Call_Domain": "MT Call Domain A",
        "MT_Call_Setup_Time_ms": "MT Call Setup Time (ms) A",
        "MT_Call_User_Setup_Time_ms": "MT Call User Setup Time (ms) A",
        "MTCallDropRate": "MT Call Drop Rate A",
        "MTCallSetupFailureRate": "MT Call Setup Failure Rate A",
        "Call_Duration": "Call Duration A",
        "Call_Setup_Duration": "Call Setup Duration A",
        "Call_Setup_Time_sec": "Call Setup Time (sec) A",
        "Voice_Call_Setup_Time_sec": "Voice Call Setup Time (sec) A",
        "Voice_Call_Success_Rate": "Voice Call Success Rate A",
        "Voice_Call_Setup_Success_Rate": "Voice Call Setup Success Rate A",
        "Voice_Call_Setup_Failure_Rate": "Voice Call Setup Failure Rate A",
        "Voice_Call_Completion_Rate": "Voice Call Completion Rate A",
        "Voice_Dropped_Call_Rate": "Voice Dropped Call Rate A",
        "Voice_Speech_Quality_On_Call_Basis": "Voice Speech Quality On Call Basis A",
        "Call Drop Rate": "Call Drop Rate A",
        "Call Dropped Count": "Call Dropped Count A",
        "Call Dropped VoLTE Count": "Call Dropped VoLTE Count A",
        "Call Block Rate": "Call Block Rate A",
        "Call Blocked Count": "Call Blocked Count A",
        "Call Blocked VoLTE Count": "Call Blocked VoLTE Count A",
        "Call Success Count": "Call Success Count A",
        "Call Success Rate": "Call Success Rate A",
        "Call Success VoLTE Count": "Call Success VoLTE Count A",
        "Call Initiation": "Call Initiation A",
        "Call Attempt": "Call Attempt A",
        "Call Attempt Retry": "Call Attempt Retry A",
        "Call Setup": "Call Setup A",
        "Call Established": "Call Established A",
        "Call End": "Call End A",
        "Call_End_Initiator": "Call End Initiator A",
        "CallInitiationDelay": "Call Initiation Delay A",
        "CallInitiationFailureRate": "Call Initiation Failure Rate A",
        "CallInitiationSuccessRate": "Call Initiation Success Rate A",
        "Data Radio Bearer": "Data Radio Bearer A",
        "Multi RAT Connectivity Mode": "Multi RAT Connectivity Mode A",
        "RadioAccessTechnologyState": "Radio Access Technology State A",
        "Is_Multi_RAB": "Is Multi RAB A",
        "AQM_RAT": "AQM RAT A",
        "AQM Algorithm DL": "AQM Algorithm DL A",
        "AQM Audio Channel Type DL": "AQM Audio Channel Type DL A",
        "AQM Score": "AQM Score A",
        "AQM Score DL": "AQM Score DL A",
        "MOS Calculator Version Downlink": "MOS Calculator Version Downlink A",
        "Speech Codec": "Speech Codec A",
        "AMR_Codec_DL": "AMR Codec DL A",
        "AMR_Codec_UL": "AMR Codec UL A",
        "AMR Codec Name DL Top #1": "AMR Codec Name DL Top #1 A",
        "AMR Codec Usage DL Top #1": "AMR Codec Usage DL Top #1 A",
        "AMR Codec Name UL Top #1": "AMR Codec Name UL Top #1 A",
        "AMR Codec Usage UL Top #1": "AMR Codec Usage UL Top #1 A",
        "SQ_MOS": "SQ MOS A",
        "MOS Calculator Version Downlink": "MOS Calculator Version Downlink A",
        "AMR_Codec_DL": "AMR Codec DL A",
        "AMR_Codec_UL": "AMR Codec UL A",
        "MultiRABServiceType1": "Multi RAB Service Type 1 A",
        "MultiRABServiceType2": "Multi RAB Service Type 2 A",
        "AQMDownlinkCallQuality": "AQM Downlink Call Quality A",
        "AverageAQMDownlinkCallQuality": "Average AQM Downlink Call Quality A",
        "POLQA SWB Score DL": "POLQA SWB Score DL A",
        "POLQA Speech Codec": "POLQA Speech Codec A",
        "RTP Jitter Audio RFC3550 (ms)": "RTP Jitter Audio RFC3550 (ms) A",
        "RTP Lost Packets Rate Audio (%)": "RTP Lost Packets Rate Audio (%) A",
        "RTP Relative Packet Delay Audio (ms)": "RTP Relative Packet Delay Audio (ms) A",
        "CodecUsed": "Codec Used A",
        "ConsecutivePacketsLost": "Consecutive Packets Lost A",
        "FERCombinedPacketLoss": "FER Combined Packet Loss A",
        "InterarrivalJitter": "Inter arrival Jitter A",
        "JitterBufferSizeIncrease": "Jitter Buffer Size Increase A",
        "JitterBufferUnderruns": "Jitter Buffer Under runs A",
        "MOSequenceNumberReceived": "MO Sequence Number Received A",
        "MOSequenceNumberSent": "MO Sequence Number Sent A",
        "NumberOfPacketsLost": "Number Of Packets Lost A",
        "PacketInterarrivalTime": "Packet Interarrival Time A",
        "PacketLossRatio": "Packet Loss Ratio A",
        "PayloadTypeAudio": "Payload Type Audio A",
        "RTPTimeGap": "RTP Time Gap A",
        "LTE Cell Identity(eNB Part)": "LTE Cell Identity(eNB Part) Side A",
        "LTE Cell Identity(Cell Part)": "LTE Cell Identity(Cell Part) Side A",
        "LTE Serving Cell Identity": "LTE Serving Cell Identity Side A",
        "LTE Serving Cell DL EARFCN": "LTE Serving Cell DL EARFCN Side A",
        "LTE Serving Cell Frequency Band": "LTE Serving Cell Frequency Band Side A",
        "LTE Serving Cell Channel RSSI(dBm)": "LTE Serving Cell Channel RSSI(dBm) Side A",
        "LTE Serving Cell RSRP(dBm)": "LTE Serving Cell RSRP(dBm) Side A",
        "LTE Serving Cell RS SINR(dB)": "LTE Serving Cell RS SINR(dB) Side A",
        "LTE Serving Cell RSRQ (dB)": "LTE Serving Cell RSRQ (dB) Side A",
        "LTE_Serving_Cell_Count_Average": "LTE Serving Cell Count Side Average Side A",
        "LTE Secondary Serving Cell 1 Identity": "LTE Secondary Serving Cell 1 Identity Side A",
        "LTE Secondary Serving Cell 1 DL EARFCN": "LTE Secondary Serving Cell 1 DL EARFCN Side A",
        "LTE Secondary Serving Cell 1 Frequency Band": "LTE Secondary Serving Cell 1 Frequency Band Side A",
        "LTE Secondary Serving Cell 1 Channel RSSI (dBm)": "LTE Secondary Serving Cell 1 Channel RSSI (dBm) Side A",
        "LTE Secondary Serving Cell 1 RSRP (dBm)": "LTE Secondary Serving Cell 1 RSRP (dBm) Side A",
        "LTE Secondary Serving Cell 1 RS SINR (dB)": "LTE Secondary Serving Cell 1 RS SINR (dB) Side A",
        "LTE Secondary Serving Cell 1 RSRQ (dB)": "LTE Secondary Serving Cell 1 RSRQ (dB) Side A",
        "LTE Neighbor Cell 1 PCI": "LTE Neighbor Cell 1 PCI Side A",
        "LTE Neighbor Cell 1 DL EARFCN": "LTE Neighbor Cell 1 DL EARFCN Side A",
        "LTE Neighbor Cell 1 RSRP": "LTE Neighbor Cell 1 RSRP Side A",
        "LTE Neighbor Cell 1 RSRQ": "LTE Neighbor Cell 1 RSRQ Side A",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB)": "LTE Serving Cell DL Pathloss Carrier 1 (dB) Side A",
        "LTE MAC DL Throughput (kbps)": "LTE MAC DL Throughput (kbps) Side A",
        "LTE MAC DL Throughput Carrier 1 (kbps)": "LTE MAC DL Throughput Carrier 1 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 2 (kbps)": "LTE MAC DL Throughput Carrier 2 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 3 (kbps)": "LTE MAC DL Throughput Carrier 3 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 4 (kbps)": "LTE MAC DL Throughput Carrier 4 (kbps) Side A",
        "LTE MAC UL Throughput (kbps)": "LTE MAC UL Throughput (kbps) Side A",
        "LTE MAC UL Throughput Carrier 1 (kbps)": "LTE MAC UL Throughput Carrier 1 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 2 (kbps)": "LTE MAC UL Throughput Carrier 2 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 3 (kbps)": "LTE MAC UL Throughput Carrier 3 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 4 (kbps)": "LTE MAC UL Throughput Carrier 4 (kbps) Side A",
        "LTE PDSCH Modulation": "LTE PDSCH Modulation Side A",
        "LTE PDSCH MCS": "LTE PDSCH MCS Side A",
        "LTE PDSCH BLER (%)": "LTE PDSCH BLER (%) Side A",
        "LTE PDSCH Phy Throughput (kbps)": "LTE PDSCH Phy Throughput (kbps) Side A",
        "LTE PDSCH Phy Throughput Total (kbps)": "LTE PDSCH Phy Throughput Total (kbps) Side A",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps)": "LTE PDSCH Phy Throughput Carrier 1 (kbps) Side A",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps)": "LTE PDSCH Phy Throughput Carrier 2 (kbps) Side A",
        "LTE PUSCH Modulation ": "LTE PUSCH Modulation Side A",
        "LTE PUSCH MCS ": "LTE PUSCH MCS Side A",
        "PUSCH BLER (%)": "PUSCH BLER (%) Side A",
        "LTE UE TX Power - PUSCH (dBm) Carrier 1": "LTE UE TX Power - PUSCH (dBm) Carrier 1 Side A",
        "LTE UE TX Power - PUCCH (dBm) Carrier 1": "LTE UE TX Power - PUCCH (dBm) Carrier 1 Side A",
        "LTE PUSCH Phy Throughput (kbps)": "LTE PUSCH Phy Throughput (kbps) Side A",
        "LTE PUSCH Phy Throughput Total (kbps)": "LTE PUSCH Phy Throughput Total (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps)": "LTE PUSCH Phy Throughput Carrier 1 (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps)": "LTE PUSCH Phy Throughput Carrier 2 (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps)": "LTE PUSCH Phy Throughput Carrier 3 (kbps) Side A",
        "PUSCH Phy Throughput Carrier 4 (kbps)": "PUSCH Phy Throughput Carrier 4 (kbps) Side A",
        "LTE RLC Throughput DL (Kbps)": "LTE RLC Throughput DL (Kbps) Side A",
        "LTE RLC Throughput UL (Kbps)": "LTE RLC Throughput UL (Kbps) Side A",
        "LTE Bearer Maximum Bitrate DL (kbit/s)": "LTE Bearer Maximum Bitrate DL (kbit/s) Side A",
        "LTE PDN Connection AMBR DL (kbps)": "LTE PDN Connection Side AMBR DL (kbps) Side A",
        "NR Serving Beam 1 Cell Identity": "NR Serving Beam 1 Cell Identity Side A",
        "NR Serving Beam 1 NRARFCN DL": "NR Serving Beam 1 NRARFCN DL Side A",
        "NR Serving Beam 1 Band": "NR Serving Beam 1 Band Side A",
        "NR Serving Beam 1 Bandwidth DL": "NR Serving Beam 1 Bandwidth DL Side A",
        "NR Serving Beam 1 Bandwidth UL": "NR Serving Beam 1 Bandwidth UL Side A",
        "NR Serving Beam 1 SSB Index": "NR Serving Beam 1 SSB Index Side A",
        "NR Serving Beam 1 Cell Type": "NR Serving Beam 1 Cell Type Side A",
        "NR Serving Beam 2 Cell Identity": "NR Serving Beam 2 Cell Identity Side A",
        "NR Serving Beam 2 NRARFCN DL": "NR Serving Beam 2 NRARFCN DL Side A",
        "NR Serving Beam 2 Band": "NR Serving Beam 2 Band Side A",
        "NR Serving Beam 2 Bandwidth DL": "NR Serving Beam 2 Bandwidth DL Side A",
        "NR Serving Beam 2 Bandwidth UL": "NR Serving Beam 2 Bandwidth UL Side A",
        "NR Serving Beam 2 SSB Index": "NR Serving Beam 2 SSB Index Side A",
        "NR Serving Beam 2 Cell Type": "NR Serving Beam 2 Cell Type Side A",
        "NR Serving Cell Identity Top #1": "NR Serving Cell Identity Top #1 Side A",
        "NR Serving Cell NRARFCN DL Top #1": "NR Serving Cell NRARFCN DL Top #1 Side A",
        "NR Serving Cell SS RSSI Top #1": "NR Serving Cell SS RSSI Top #1 Side A",
        "NR Serving Cell SS RSRP Top #1": "NR Serving Cell SS RSRP Top #1 Side A",
        "NR Serving Cell SS SINR Top #1": "NR Serving Cell SS SINR Top #1 Side A",
        "NR Serving Cell SS RSRQ Top #1": "NR Serving Cell SS RSRQ Top #1 Side A",
        "NR PCell SSB Serving Beam Index Top #1": "NR PCell SSB Serving Beam Index Top #1 Side A",
        "NR Neighbor Cell 1 Cell Identity": "NR Neighbor Cell 1 Cell Identity Side A",
        "NR Neighbor Cell 1 NRARFCN": "NR Neighbor Cell 1 NRARFCN Side A",
        "NR Neighbor Cell 1 SS RSRP (dBm)": "NR Neighbor Cell 1 SS RSRP (dBm) Side A",
        "NR Neighbor Cell 1 SS SINR (dB)": "NR Neighbor Cell 1 SS SINR (dB) Side A",
        "NR Neighbor Cell 1 SS RSRQ (dB)": "NR Neighbor Cell 1 SS RSRQ (dB) Side A",
        "NR Neighbor Cell 1 Best Beam Index": "NR Neighbor Cell 1 Best Beam Index Side A",
        "NR Neighbor Cell 1 Cell Type": "NR Neighbor Cell 1 Cell Type Side A",
        "NR Phy Throughput Multi-RAT DL (kbps)": "NR Phy Throughput Multi-RAT DL (kbps) Side A",
        "NR Phy Throughput Multi-RAT UL (kbps)": "NR Phy Throughput Multi-RAT UL (kbps) Side A",
        "NR PDSCH Phy Throughput Total (Kbps)": "NR PDSCH Phy Throughput Total (Kbps) Side A",
        "NR Pcell PDSCH Scheduled Throughput (Mbps)": "NR Pcell PDSCH Scheduled Throughput (Mbps) Side A",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 1 (Kbps) Side A",
        "NR PDSCH Modulation Serving Beam 1": "NR PDSCH Modulation Serving Beam 1 Side A",
        "NR PDSCH MCS Serving Beam 1": "NR PDSCH MCS Serving Beam 1 Side A",
        "NR PDSCH BLER (%) Serving Beam 1": "NR PDSCH BLER (%) Serving Beam 1 Side A",
        "NR PDSCH CQI Serving Beam 1": "NR PDSCH CQI Serving Beam 1 Side A",
        "NR PDSCH RI Serving Beam 1": "NR PDSCH RI Serving Beam 1 Side A",
        "NR DL Pathloss Serving Beam 1": "NR DL Pathloss Serving Beam 1 Side A",
        "NR PUCCH Tx Power Serving Beam 1 (dBm) ": "NR PUCCH Tx Power Serving Beam 1 (dBm) Side A",
        "NR PUSCH Tx Power Serving Beam 1 (dBm) ": "NR PUSCH Tx Power Serving Beam 1 (dBm) Side A",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 2 (Kbps) Side A",
        "NR PDSCH Modulation Serving Beam 2": "NR PDSCH Modulation Serving Beam 2 Side A",
        "NR PDSCH MCS Serving Beam 2": "NR PDSCH MCS Serving Beam 2 Side A",
        "NR PDSCH BLER (%) Serving Beam 2": "NR PDSCH BLER (%) Serving Beam 2 Side A",
        "NR PDSCH CQI Serving Beam 2": "NR PDSCH CQI Serving Beam 2 Side A",
        "NR PDSCH RI Serving Beam 2": "NR PDSCH RI Serving Beam 2 Side A",
        "NR DL Pathloss Serving Beam 2": "NR DL Pathloss Serving Beam 2 Side A",
        "NR PUSCH Phy Throughput Total (kbps)": "NR PUSCH Phy Throughput Total (kbps) Side A",
        "NR Pcell PUSCH Scheduled Throughput (Mbps)": "NR Pcell PUSCH Scheduled Throughput (Mbps) Side A",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 1 (Kbps) Side A",
        "NR PUSCH Modulation Serving Beam 1": "NR PUSCH Modulation Serving Beam 1 Side A",
        "NR PUSCH MCS Serving Beam 1": "NR PUSCH MCS Serving Beam 1 Side A",
        "NR PUSCH BLER (%) Serving Beam 1": "NR PUSCH BLER (%) Serving Beam 1 Side A",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 2 (Kbps) Side A",
        "NR PUSCH Modulation Serving Beam 2": "NR PUSCH Modulation Serving Beam 2 Side A",
        "NR PUSCH MCS Serving Beam 2": "NR PUSCH MCS Serving Beam 2 Side A",
        "NR PUSCH BLER (%) Serving Beam 2": "NR PUSCH BLER (%) Serving Beam 2 Side A",
        "NR MAC UL Throughput Total (kbps)": "NR MAC UL Throughput Total (kbps) Side A",
        "NR RLC DL Throughput Total (kbps)": "NR RLC DL Throughput Total (kbps) Side A",
        "NR RLC UL Throughput Total (kbps)": "NR RLC UL Throughput Total (kbps) Side A",
        "NR RLC UL Throughput (Kbps)": "NR RLC UL Throughput (Kbps) Side A",
        "RadioAccessTechnologyState": "Radio Access Technology State A",
        "FirmwareVersion": "FirmwareVersion Side A",
        "Qualifier": "Qualifier Side A",
        "Date": "Date",
        "Time": "Time",
        "VoiceStartTime_B": "VoiceStartTime Side B",
        "VoiceEndTime_B": "VoiceEndTime Side B",
        "Test Name_B": "Test Name B",
        "Type Mobility_B": "Type of Mobility B",
        "DeviceDescription_B": "DeviceDescription B",
        "VoiceLogfileName_B": "Logfile Name Side B",
        "Operator_B": "Operator B",
        "Country_B": "Route Name B",
        "Sequence_B": "Sequence B",
        "Latitude_B": "Start Latitude B",
        "Longitude_B": "Start Longitude B",
        "EventName_B": "Event Name Side B",
        "IMEI_B": "IMEI Side B",
        "IMSI_B": "IMSI Side B",
        "MCC_B": "MCC B",
        "MNC_B": "MNC B",
        "TAC_B": "TAC B",
        "Technology_Detail_B": "Technology Detail B",
        "PhoneNumber_B": "Phone Number B",
        "Dialed Number_B": "Dialed Number B",
        "Call_Status_B": "Call Status B",
        "Call_Type_B": "Call Type B",
        "Call_Number_B": "Call Number B",
        "MO_Call_Domain_B": "MO Call Domain B",
        "MO_Call_Setup_Time_ms_B": "MO Call Setup Time (ms) B",
        "MO_Call_User_Setup_Time_ms_B": "MO Call User Setup Time (ms) B",
        "MOCallDropRate_B": "MO Call Drop Rate B",
        "MOCallSetupFailureRate_B": "MO Call Setup Failure Rate B",
        "MT_Call_Domain_B": "MT Call Domain B",
        "MT_Call_Setup_Time_ms_B": "MT Call Setup Time (ms) B",
        "MT_Call_User_Setup_Time_ms_B": "MT Call User Setup Time (ms) B",
        "MTCallDropRate_B": "MT Call Drop Rate B",
        "MTCallSetupFailureRate_B": "MT Call Setup Failure Rate B",
        "Call_Duration_B": "Call Duration B",
        "Call_Setup_Duration_B": "Call Setup Duration B",
        "Call_Setup_Time_sec_B": "Call Setup Time (sec) B",
        "Voice_Call_Setup_Time_sec_B": "Voice Call Setup Time (sec) B",
        "Voice_Call_Success_Rate_B": "Voice Call Success Rate B",
        "Voice_Call_Setup_Success_Rate_B": "Voice Call Setup Success Rate B",
        "Voice_Call_Setup_Failure_Rate_B": "Voice Call Setup Failure Rate B",
        "Voice_Call_Completion_Rate_B": "Voice Call Completion Rate B",
        "Voice_Dropped_Call_Rate_B": "Voice Dropped Call Rate B",
        "Voice_Speech_Quality_On_Call_Basis_B": "Voice Speech Quality On Call Basis B",
        "Call Drop Rate_B": "Call Drop Rate B",
        "Call Dropped Count_B": "Call Dropped Count B",
        "Call Dropped VoLTE Count_B": "Call Dropped VoLTE Count B",
        "Call Block Rate_B": "Call Block Rate B",
        "Call Blocked Count_B": "Call Blocked Count B",
        "Call Blocked VoLTE Count_B": "Call Blocked VoLTE Count B",
        "Call Success Count_B": "Call Success Count B",
        "Call Success Rate_B": "Call Success Rate B",
        "Call Success VoLTE Count_B": "Call Success VoLTE Count B",
        "Call Initiation_B": "Call Initiation B",
        "Call Attempt_B": "Call Attempt B",
        "Call Attempt Retry_B": "Call Attempt Retry B",
        "Call Setup_B": "Call Setup B",
        "Call Established_B": "Call Established B",
        "Call End_B": "Call End B",
        "Call_End_Initiator_B": "Call End Initiator B",
        "CallInitiationDelay_B": "Call Initiation Delay B",
        "CallInitiationFailureRate_B": "Call Initiation Failure Rate B",
        "CallInitiationSuccessRate_B": "Call Initiation Success Rate B",
        "Data Radio Bearer_B": "Data Radio Bearer B",
        "Multi RAT Connectivity Mode_B": "Multi RAT Connectivity Mode B",
        "RadioAccessTechnologyState_B": "Radio Access Technology State B",
        "Is_Multi_RAB_B": "Is Multi RAB B",
        "AQM_RAT_B": "AQM RAT B",
        "AQM Algorithm DL_B": "AQM Algorithm DL B",
        "AQM Audio Channel Type DL_B": "AQM Audio Channel Type DL B",
        "AQM Score_B": "AQM Score B",
        "AQM Score DL_B": "AQM Score DL B",
        "MOS Calculator Version Downlink_B": "MOS Calculator Version Downlink B",
        "Speech Codec_B": "Speech Codec B",
        "AMR_Codec_DL_B": "AMR Codec DL B",
        "AMR_Codec_UL_B": "AMR Codec UL B",
        "AMR Codec Name DL Top #1_B": "AMR Codec Name DL Top #1 B",
        "AMR Codec Usage DL Top #1_B": "AMR Codec Usage DL Top #1 B",
        "AMR Codec Name UL Top #1_B": "AMR Codec Name UL Top #1 B",
        "AMR Codec Usage UL Top #1_B": "AMR Codec Usage UL Top #1 B",
        "SQ_MOS_B": "SQ MOS B",
        "MOS Calculator Version Downlink_B": "MOS Calculator Version Downlink B",
        "AMR_Codec_DL_B": "AMR Codec DL B",
        "AMR_Codec_UL_B": "AMR Codec UL B",
        "MultiRABServiceType1_B": "Multi RAB Service Type 1 B",
        "MultiRABServiceType2_B": "Multi RAB Service Type 2 B",
        "AQMDownlinkCallQuality_B": "AQM Downlink Call Quality B",
        "AverageAQMDownlinkCallQuality_B": "Average AQM Downlink Call Quality B",
        "POLQA SWB Score DL_B": "POLQA SWB Score DL B",
        "POLQA Speech Codec_B": "POLQA Speech Codec B",
        "RTP Jitter Audio RFC3550 (ms)_B": "RTP Jitter Audio RFC3550 (ms) B",
        "RTP Lost Packets Rate Audio (%)_B": "RTP Lost Packets Rate Audio (%) B",
        "RTP Relative Packet Delay Audio (ms)_B": "RTP Relative Packet Delay Audio (ms) B",
        "CodecUsed_B": "Codec Used B",
        "ConsecutivePacketsLost_B": "Consecutive Packets Lost B",
        "FERCombinedPacketLoss_B": "FER Combined Packet Loss B",
        "InterarrivalJitter_B": "Inter arrival Jitter B",
        "JitterBufferSizeIncrease_B": "Jitter Buffer Size Increase B",
        "JitterBufferUnderruns_B": "Jitter Buffer Under runs B",
        "MOSequenceNumberReceived_B": "MO Sequence Number Received B",
        "MOSequenceNumberSent_B": "MO Sequence Number Sent B",
        "NumberOfPacketsLost_B": "Number Of Packets Lost B",
        "PacketInterarrivalTime_B": "Packet Interarrival Time B",
        "PacketLossRatio_B": "Packet Loss Ratio B",
        "PayloadTypeAudio_B": "Payload Type Audio B",
        "RTPTimeGap_B": "RTP Time Gap B",
        "LTE Cell Identity(eNB Part)_B": "LTE Cell Identity(eNB Part) Side B",
        "LTE Cell Identity(Cell Part)_B": "LTE Cell Identity(Cell Part) Side B",
        "LTE Serving Cell Identity_B": "LTE Serving Cell Identity Side B",
        "LTE Serving Cell DL EARFCN_B": "LTE Serving Cell DL EARFCN Side B",
        "LTE Serving Cell Frequency Band_B": "LTE Serving Cell Frequency Band Side B",
        "LTE Serving Cell Channel RSSI(dBm)_B": "LTE Serving Cell Channel RSSI(dBm) Side B",
        "LTE Serving Cell RSRP(dBm)_B": "LTE Serving Cell RSRP(dBm) Side B",
        "LTE Serving Cell RS SINR(dB)_B": "LTE Serving Cell RS SINR(dB) Side B",
        "LTE Serving Cell RSRQ (dB)_B": "LTE Serving Cell RSRQ (dB) Side B",
        "LTE_Serving_Cell_Count_Average_B": "LTE Serving Cell Count Side Average Side B",
        "LTE Secondary Serving Cell 1 Identity_B": "LTE Secondary Serving Cell 1 Identity Side B",
        "LTE Secondary Serving Cell 1 DL EARFCN_B": "LTE Secondary Serving Cell 1 DL EARFCN Side B",
        "LTE Secondary Serving Cell 1 Frequency Band_B": "LTE Secondary Serving Cell 1 Frequency Band Side B",
        "LTE Secondary Serving Cell 1 Channel RSSI (dBm)_B": "LTE Secondary Serving Cell 1 Channel RSSI (dBm) Side B",
        "LTE Secondary Serving Cell 1 RSRP (dBm)_B": "LTE Secondary Serving Cell 1 RSRP (dBm) Side B",
        "LTE Secondary Serving Cell 1 RS SINR (dB)_B": "LTE Secondary Serving Cell 1 RS SINR (dB) Side B",
        "LTE Secondary Serving Cell 1 RSRQ (dB)_B": "LTE Secondary Serving Cell 1 RSRQ (dB) Side B",
        "LTE Neighbor Cell 1 PCI_B": "LTE Neighbor Cell 1 PCI Side B",
        "LTE Neighbor Cell 1 DL EARFCN_B": "LTE Neighbor Cell 1 DL EARFCN Side B",
        "LTE Neighbor Cell 1 RSRP_B": "LTE Neighbor Cell 1 RSRP Side B",
        "LTE Neighbor Cell 1 RSRQ_B": "LTE Neighbor Cell 1 RSRQ Side B",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB)_B": "LTE Serving Cell DL Pathloss Carrier 1 (dB) Side B",
        "LTE MAC DL Throughput (kbps)_B": "LTE MAC DL Throughput (kbps) Side B",
        "LTE MAC DL Throughput Carrier 1 (kbps)_B": "LTE MAC DL Throughput Carrier 1 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 2 (kbps)_B": "LTE MAC DL Throughput Carrier 2 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 3 (kbps)_B": "LTE MAC DL Throughput Carrier 3 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 4 (kbps)_B": "LTE MAC DL Throughput Carrier 4 (kbps) Side B",
        "LTE MAC UL Throughput (kbps)_B": "LTE MAC UL Throughput (kbps) Side B",
        "LTE MAC UL Throughput Carrier 1 (kbps)_B": "LTE MAC UL Throughput Carrier 1 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 2 (kbps)_B": "LTE MAC UL Throughput Carrier 2 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 3 (kbps)_B": "LTE MAC UL Throughput Carrier 3 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 4 (kbps)_B": "LTE MAC UL Throughput Carrier 4 (kbps) Side B",
        "LTE PDSCH Modulation_B": "LTE PDSCH Modulation Side B",
        "LTE PDSCH MCS_B": "LTE PDSCH MCS Side B",
        "LTE PDSCH BLER (%)_B": "LTE PDSCH BLER (%) Side B",
        "LTE PDSCH Phy Throughput (kbps)_B": "LTE PDSCH Phy Throughput (kbps) Side B",
        "LTE PDSCH Phy Throughput Total (kbps)_B": "LTE PDSCH Phy Throughput Total (kbps) Side B",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps)_B": "LTE PDSCH Phy Throughput Carrier 1 (kbps) Side B",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps)_B": "LTE PDSCH Phy Throughput Carrier 2 (kbps) Side B",
        "LTE PUSCH Modulation _B": "LTE PUSCH Modulation Side B",
        "LTE PUSCH MCS _B": "LTE PUSCH MCS Side B",
        "PUSCH BLER (%)_B": "PUSCH BLER (%) Side B",
        "LTE UE TX Power - PUSCH (dBm) Carrier 1_B": "LTE UE TX Power - PUSCH (dBm) Carrier 1 Side B",
        "LTE UE TX Power - PUCCH (dBm) Carrier 1_B": "LTE UE TX Power - PUCCH (dBm) Carrier 1 Side B",
        "LTE PUSCH Phy Throughput (kbps)_B": "LTE PUSCH Phy Throughput (kbps) Side B",
        "LTE PUSCH Phy Throughput Total (kbps)_B": "LTE PUSCH Phy Throughput Total (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps)_B": "LTE PUSCH Phy Throughput Carrier 1 (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps)_B": "LTE PUSCH Phy Throughput Carrier 2 (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps)_B": "LTE PUSCH Phy Throughput Carrier 3 (kbps) Side B",
        "PUSCH Phy Throughput Carrier 4 (kbps)_B": "PUSCH Phy Throughput Carrier 4 (kbps) Side B",
        "LTE RLC Throughput DL (Kbps)_B": "LTE RLC Throughput DL (Kbps) Side B",
        "LTE RLC Throughput UL (Kbps)_B": "LTE RLC Throughput UL (Kbps) Side B",
        "LTE Bearer Maximum Bitrate DL (kbit/s)_B": "LTE Bearer Maximum Bitrate DL (kbit/s) Side B",
        "LTE PDN Connection AMBR DL (kbps)_B": "LTE PDN Connection Side AMBR DL (kbps) Side B",
        "NR Serving Beam 1 Cell Identity_B": "NR Serving Beam 1 Cell Identity Side B",
        "NR Serving Beam 1 NRARFCN DL_B": "NR Serving Beam 1 NRARFCN DL Side B",
        "NR Serving Beam 1 Band_B": "NR Serving Beam 1 Band Side B",
        "NR Serving Beam 1 Bandwidth DL_B": "NR Serving Beam 1 Bandwidth DL Side B",
        "NR Serving Beam 1 Bandwidth UL_B": "NR Serving Beam 1 Bandwidth UL Side B",
        "NR Serving Beam 1 SSB Index_B": "NR Serving Beam 1 SSB Index Side B",
        "NR Serving Beam 1 Cell Type_B": "NR Serving Beam 1 Cell Type Side B",
        "NR Serving Beam 2 Cell Identity_B": "NR Serving Beam 2 Cell Identity Side B",
        "NR Serving Beam 2 NRARFCN DL_B": "NR Serving Beam 2 NRARFCN DL Side B",
        "NR Serving Beam 2 Band_B": "NR Serving Beam 2 Band Side B",
        "NR Serving Beam 2 Bandwidth DL_B": "NR Serving Beam 2 Bandwidth DL Side B",
        "NR Serving Beam 2 Bandwidth UL_B": "NR Serving Beam 2 Bandwidth UL Side B",
        "NR Serving Beam 2 SSB Index_B": "NR Serving Beam 2 SSB Index Side B",
        "NR Serving Beam 2 Cell Type_B": "NR Serving Beam 2 Cell Type Side B",
        "NR Serving Cell Identity Top #1_B": "NR Serving Cell Identity Top #1 Side B",
        "NR Serving Cell NRARFCN DL Top #1_B": "NR Serving Cell NRARFCN DL Top #1 Side B",
        "NR Serving Cell SS RSSI Top #1_B": "NR Serving Cell SS RSSI Top #1 Side B",
        "NR Serving Cell SS RSRP Top #1_B": "NR Serving Cell SS RSRP Top #1 Side B",
        "NR Serving Cell SS SINR Top #1_B": "NR Serving Cell SS SINR Top #1 Side B",
        "NR Serving Cell SS RSRQ Top #1_B": "NR Serving Cell SS RSRQ Top #1 Side B",
        "NR PCell SSB Serving Beam Index Top #1_B": "NR PCell SSB Serving Beam Index Top #1 Side B",
        "NR Neighbor Cell 1 Cell Identity_B": "NR Neighbor Cell 1 Cell Identity Side B",
        "NR Neighbor Cell 1 NRARFCN_B": "NR Neighbor Cell 1 NRARFCN Side B",
        "NR Neighbor Cell 1 SS RSRP (dBm)_B": "NR Neighbor Cell 1 SS RSRP (dBm) Side B",
        "NR Neighbor Cell 1 SS SINR (dB)_B": "NR Neighbor Cell 1 SS SINR (dB) Side B",
        "NR Neighbor Cell 1 SS RSRQ (dB)_B": "NR Neighbor Cell 1 SS RSRQ (dB) Side B",
        "NR Neighbor Cell 1 Best Beam Index_B": "NR Neighbor Cell 1 Best Beam Index Side B",
        "NR Neighbor Cell 1 Cell Type_B": "NR Neighbor Cell 1 Cell Type Side B",
        "NR Phy Throughput Multi-RAT DL (kbps)_B": "NR Phy Throughput Multi-RAT DL (kbps) Side B",
        "NR Phy Throughput Multi-RAT UL (kbps)_B": "NR Phy Throughput Multi-RAT UL (kbps) Side B",
        "NR PDSCH Phy Throughput Total (Kbps)_B": "NR PDSCH Phy Throughput Total (Kbps) Side B",
        "NR Pcell PDSCH Scheduled Throughput (Mbps)_B": "NR Pcell PDSCH Scheduled Throughput (Mbps) Side B",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)_B": "NR PDSCH Phy Throughput Serving Beam 1 (Kbps) Side B",
        "NR PDSCH Modulation Serving Beam 1_B": "NR PDSCH Modulation Serving Beam 1 Side B",
        "NR PDSCH MCS Serving Beam 1_B": "NR PDSCH MCS Serving Beam 1 Side B",
        "NR PDSCH BLER (%) Serving Beam 1_B": "NR PDSCH BLER (%) Serving Beam 1 Side B",
        "NR PDSCH CQI Serving Beam 1_B": "NR PDSCH CQI Serving Beam 1 Side B",
        "NR PDSCH RI Serving Beam 1_B": "NR PDSCH RI Serving Beam 1 Side B",
        "NR DL Pathloss Serving Beam 1_B": "NR DL Pathloss Serving Beam 1 Side B",
        "NR PUCCH Tx Power Serving Beam 1 (dBm) _B": "NR PUCCH Tx Power Serving Beam 1 (dBm) Side B",
        "NR PUSCH Tx Power Serving Beam 1 (dBm) _B": "NR PUSCH Tx Power Serving Beam 1 (dBm) Side B",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)_B": "NR PDSCH Phy Throughput Serving Beam 2 (Kbps) Side B",
        "NR PDSCH Modulation Serving Beam 2_B": "NR PDSCH Modulation Serving Beam 2 Side B",
        "NR PDSCH MCS Serving Beam 2_B": "NR PDSCH MCS Serving Beam 2 Side B",
        "NR PDSCH BLER (%) Serving Beam 2_B": "NR PDSCH BLER (%) Serving Beam 2 Side B",
        "NR PDSCH CQI Serving Beam 2_B": "NR PDSCH CQI Serving Beam 2 Side B",
        "NR PDSCH RI Serving Beam 2_B": "NR PDSCH RI Serving Beam 2 Side B",
        "NR DL Pathloss Serving Beam 2_B": "NR DL Pathloss Serving Beam 2 Side B",
        "NR PUSCH Phy Throughput Total (kbps)_B": "NR PUSCH Phy Throughput Total (kbps) Side B",
        "NR Pcell PUSCH Scheduled Throughput (Mbps)_B": "NR Pcell PUSCH Scheduled Throughput (Mbps) Side B",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)_B": "NR PUSCH Phy Throughput Serving Beam 1 (Kbps) Side B",
        "NR PUSCH Modulation Serving Beam 1_B": "NR PUSCH Modulation Serving Beam 1 Side B",
        "NR PUSCH MCS Serving Beam 1_B": "NR PUSCH MCS Serving Beam 1 Side B",
        "NR PUSCH BLER (%) Serving Beam 1_B": "NR PUSCH BLER (%) Serving Beam 1 Side B",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)_B": "NR PUSCH Phy Throughput Serving Beam 2 (Kbps) Side B",
        "NR PUSCH Modulation Serving Beam 2_B": "NR PUSCH Modulation Serving Beam 2 Side B",
        "NR PUSCH MCS Serving Beam 2_B": "NR PUSCH MCS Serving Beam 2 Side B",
        "NR PUSCH BLER (%) Serving Beam 2_B": "NR PUSCH BLER (%) Serving Beam 2 Side B",
        "NR MAC UL Throughput Total (kbps)_B": "NR MAC UL Throughput Total (kbps) Side B",
        "NR RLC DL Throughput Total (kbps)_B": "NR RLC DL Throughput Total (kbps) Side B",
        "NR RLC UL Throughput Total (kbps)_B": "NR RLC UL Throughput Total (kbps) Side B",
        "NR RLC UL Throughput (Kbps)_B": "NR RLC UL Throughput (Kbps) Side B",
        "RadioAccessTechnologyState_B": "Radio Access Technology State B",
        "FirmwareVersion_B": "FirmwareVersion Side B",
        "Qualifier_B": "Qualifier Side B",
        "End Latitude": "End Latitude A",
        "End Longitude": "End Longitude A",
        "End Latitude_B": "End Latitude B",
        "End Longitude_B": "End Longitude B"



}
merged_df.rename(columns=master_rename_map, inplace=True)

def generate_test_ids(merged_df):
    test_name_codes = {
        "HTTP FDFS DL": 5,
        "HTTP FDFS UL": 6,
        "HTTP FDTT DL": 7,
        "HTTP FDTT UL": 8,
        "HTTP BROWSING LIVE": 9,
        "HTTP BROSWING STATIC": 10,
        "YoutubeVOD": 11,
        "YoutubeLIVE": 11,
        "Ping 800": 14,
        "Ping 40": 14,
        "DNS": 15,
        "Data_VideoChat": 13,
        "Data_EGaming": 12,
        "MOS_M2M": 1,
        "MOS_OTT": 4,
        "Voice_M2M": 1,
        "Voice_OTT": 2
    }

    operator_codes = {
        "Vodafone DE": 1,
        "Telefonica DE": 2,
        "Deutsche Telekom": 3
    }

    df = merged_df.copy()
    df["Test_IDs"] = None

    for (test_name, operator), group in df.groupby(["Test Name", "Operator"]):
        test_code = test_name_codes.get(test_name, 0)
        operator_code = operator_codes.get(operator, 0)
        for i, idx in enumerate(group.index, start=1):
            df.at[idx, "Test_IDs"] = f"{test_code}{operator_code}{i:04d}"

    # Reorder: Move Test_IDs to third column (after 'Time')
    first_cols = ['Date', 'Time', 'Test_IDs']
    remaining_cols = [col for col in df.columns if col not in first_cols]
    df = df[first_cols + remaining_cols]

    return df

# === Apply and reorder ===
merged_df = generate_test_ids(merged_df)


schema_groups = {
    "VoiceOTT": [
        "Date",
        "Time",
        "Test_IDs",
        "Route Name",
        "Type of Mobility",
        "Test Name",
        "Operator",
        "MCC",
        "MNC",
        "Logfile Name Side A",
        "Sequence A",
        "Technology Detail A",
        "DeviceDescription A",
        "Latitude",
        "End Latitude A",
        "Longitude",
        "End Longitude A",
        "IMEI Side A",
        "IMSI Side A",
        "Event Name Side A",
        "Phone Number A",
        "Dialed Number A",
        "Call Status A",
        "Call Type A",
        "Call Number A",
        "MO Call Domain A",
        "MO Call Setup Time (ms) A",
        "MO Call User Setup Time (ms) A",
        "MO Call Drop Rate A",
        "MO Call Setup Failure Rate A",
        "MT Call Domain A",
        "MT Call Setup Time (ms) A",
        "MT Call User Setup Time (ms) A",
        "MT Call Drop Rate A",
        "MT Call Setup Failure Rate A",
        "Call Duration A",
        "Call Setup Duration A",
        "Call Setup Time (sec) A",
        "Voice Call Setup Time (sec) A",
        "Voice Call Success Rate A",
        "Voice Call Setup Success Rate A",
        "Voice Call Setup Failure Rate A",
        "Voice Call Completion Rate A",
        "Voice Dropped Call Rate A",
        "Voice Speech Quality On Call Basis A",
        "Call Drop Rate A",
        "Call Dropped Count A",
        "Call Dropped VoLTE Count A",
        "Call Block Rate A",
        "Call Blocked Count A",
        "Call Blocked VoLTE Count A",
        "Call Success Count A",
        "Call Success Rate A",
        "Call Success VoLTE Count A",
        "Call Initiation A",
        "Call Attempt A",
        "Call Attempt Retry A",
        "Call Setup A",
        "Call Established A",
        "Call End A",
        "Call End Initiator A",
        "Call Initiation Delay A",
        "Call Initiation Failure Rate A",
        "Call Initiation Success Rate A",
        "Data Radio Bearer A",
        "Multi RAT Connectivity Mode A",
        "Radio Access Technology State A",
        "Is Multi RAB A",
        "AQM RAT A",
        "AQM Algorithm DL A",
        "AQM Audio Channel Type DL A",
        "AQM Score A",
        "AQM Score DL A",
        "Speech Codec A",
        "AMR Codec DL A",
        "AMR Codec UL A",
        "AMR Codec Name DL Top #1 A",
        "AMR Codec Usage DL Top #1 A",
        "AMR Codec Name UL Top #1 A",
        "AMR Codec Usage UL Top #1 A",
        "SQ MOS A",
        "MOS Calculator Version Downlink A",
        "Multi RAB Service Type 1 A",
        "Multi RAB Service Type 2 A",
        "AQM Downlink Call Quality A",
        "Average AQM Downlink Call Quality A",
        "POLQA SWB Score DL A",
        "POLQA Speech Codec A",
        "RTP Jitter Audio RFC3550 (ms) A",
        "RTP Lost Packets Rate Audio (%) A",
        "RTP Relative Packet Delay Audio (ms) A",
        "Codec Used A",
        "Consecutive Packets Lost A",
        "FER Combined Packet Loss A",
        "Inter arrival Jitter A",
        "Jitter Buffer Size Increase A",
        "Jitter Buffer Under runs A",
        "MO Sequence Number Received A",
        "MO Sequence Number Sent A",
        "Number Of Packets Lost A",
        "Packet Interarrival Time A",
        "Packet Loss Ratio A",
        "Payload Type Audio A",
        "RTP Time Gap A",
        "LTE Cell Identity(eNB Part) Side A",
        "LTE Cell Identity(Cell Part) Side A",
        "LTE Serving Cell Identity Side A",
        "LTE Serving Cell DL EARFCN Side A",
        "LTE Serving Cell Frequency Band Side A",
        "LTE Serving Cell Channel RSSI(dBm) Side A",
        "LTE Serving Cell RSRP(dBm) Side A",
        "LTE Serving Cell RS SINR(dB) Side A",
        "LTE Serving Cell RSRQ (dB) Side A",
        "LTE Serving Cell Count Side Average Side A",
        "LTE Secondary Serving Cell 1 Identity Side A",
        "LTE Secondary Serving Cell 1 DL EARFCN Side A",
        "LTE Secondary Serving Cell 1 Frequency Band Side A",
        "LTE Secondary Serving Cell 1 Channel RSSI (dBm) Side A",
        "LTE Secondary Serving Cell 1 RSRP (dBm) Side A",
        "LTE Secondary Serving Cell 1 RS SINR (dB) Side A",
        "LTE Secondary Serving Cell 1 RSRQ (dB) Side A",
        "LTE Neighbor Cell 1 PCI Side A",
        "LTE Neighbor Cell 1 DL EARFCN Side A",
        "LTE Neighbor Cell 1 RSRP Side A",
        "LTE Neighbor Cell 1 RSRQ Side A",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB) Side A",
        "LTE MAC DL Throughput (kbps) Side A",
        "LTE MAC DL Throughput Carrier 1 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 2 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 3 (kbps) Side A",
        "LTE MAC DL Throughput Carrier 4 (kbps) Side A",
        "LTE MAC UL Throughput (kbps) Side A",
        "LTE MAC UL Throughput Carrier 1 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 2 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 3 (kbps) Side A",
        "LTE MAC UL Throughput Carrier 4 (kbps) Side A",
        "LTE PDSCH Modulation Side A",
        "LTE PDSCH MCS Side A",
        "LTE PDSCH BLER (%) Side A",
        "LTE PDSCH Phy Throughput (kbps) Side A",
        "LTE PDSCH Phy Throughput Total (kbps) Side A",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps) Side A",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps) Side A",
        "LTE PUSCH Modulation Side A",
        "LTE PUSCH MCS Side A",
        "PUSCH BLER (%) Side A",
        "LTE UE TX Power - PUSCH (dBm) Carrier 1 Side A",
        "LTE UE TX Power - PUCCH (dBm) Carrier 1 Side A",
        "LTE PUSCH Phy Throughput (kbps) Side A",
        "LTE PUSCH Phy Throughput Total (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps) Side A",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps) Side A",
        "PUSCH Phy Throughput Carrier 4 (kbps) Side A",
        "LTE RLC Throughput DL (Kbps) Side A",
        "LTE RLC Throughput UL (Kbps) Side A",
        "LTE Bearer Maximum Bitrate DL (kbit/s) Side A",
        "LTE PDN Connection Side AMBR DL (kbps) Side A",
        "NR Serving Beam 1 Cell Identity Side A",
        "NR Serving Beam 1 NRARFCN DL Side A",
        "NR Serving Beam 1 Band Side A",
        "NR Serving Beam 1 Bandwidth DL Side A",
        "NR Serving Beam 1 Bandwidth UL Side A",
        "NR Serving Beam 1 SSB Index Side A",
        "NR Serving Beam 1 Cell Type Side A",
        "NR Serving Beam 2 Cell Identity Side A",
        "NR Serving Beam 2 NRARFCN DL Side A",
        "NR Serving Beam 2 Band Side A",
        "NR Serving Beam 2 Bandwidth DL Side A",
        "NR Serving Beam 2 Bandwidth UL Side A",
        "NR Serving Beam 2 SSB Index Side A",
        "NR Serving Beam 2 Cell Type Side A",
        "NR Serving Cell Identity Top #1 Side A",
        "NR Serving Cell NRARFCN DL Top #1 Side A",
        "NR Serving Cell SS RSSI Top #1 Side A",
        "NR Serving Cell SS RSRP Top #1 Side A",
        "NR Serving Cell SS SINR Top #1 Side A",
        "NR Serving Cell SS RSRQ Top #1 Side A",
        "NR PCell SSB Serving Beam Index Top #1 Side A",
        "NR Neighbor Cell 1 Cell Identity Side A",
        "NR Neighbor Cell 1 NRARFCN Side A",
        "NR Neighbor Cell 1 SS RSRP (dBm) Side A",
        "NR Neighbor Cell 1 SS SINR (dB) Side A",
        "NR Neighbor Cell 1 SS RSRQ (dB) Side A",
        "NR Neighbor Cell 1 Best Beam Index Side A",
        "NR Neighbor Cell 1 Cell Type Side A",
        "NR Phy Throughput Multi-RAT DL (kbps) Side A",
        "NR Phy Throughput Multi-RAT UL (kbps) Side A",
        "NR PDSCH Phy Throughput Total (Kbps) Side A",
        "NR Pcell PDSCH Scheduled Throughput (Mbps) Side A",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps) Side A",
        "NR PDSCH Modulation Serving Beam 1 Side A",
        "NR PDSCH MCS Serving Beam 1 Side A",
        "NR PDSCH BLER (%) Serving Beam 1 Side A",
        "NR PDSCH CQI Serving Beam 1 Side A",
        "NR PDSCH RI Serving Beam 1 Side A",
        "NR DL Pathloss Serving Beam 1 Side A",
        "NR PUCCH Tx Power Serving Beam 1 (dBm) Side A",
        "NR PUSCH Tx Power Serving Beam 1 (dBm) Side A",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps) Side A",
        "NR PDSCH Modulation Serving Beam 2 Side A",
        "NR PDSCH MCS Serving Beam 2 Side A",
        "NR PDSCH BLER (%) Serving Beam 2 Side A",
        "NR PDSCH CQI Serving Beam 2 Side A",
        "NR PDSCH RI Serving Beam 2 Side A",
        "NR DL Pathloss Serving Beam 2 Side A",
        "NR PUSCH Phy Throughput Total (kbps) Side A",
        "NR Pcell PUSCH Scheduled Throughput (Mbps) Side A",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps) Side A",
        "NR PUSCH Modulation Serving Beam 1 Side A",
        "NR PUSCH MCS Serving Beam 1 Side A",
        "NR PUSCH BLER (%) Serving Beam 1 Side A",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps) Side A",
        "NR PUSCH Modulation Serving Beam 2 Side A",
        "NR PUSCH MCS Serving Beam 2 Side A",
        "NR PUSCH BLER (%) Serving Beam 2 Side A",
        "NR MAC UL Throughput Total (kbps) Side A",
        "NR RLC DL Throughput Total (kbps) Side A",
        "NR RLC UL Throughput Total (kbps) Side A",
        "NR RLC UL Throughput (Kbps) Side A",
        "FirmwareVersion Side A",
        "Logfile Name Side B",
        "Sequence B",
        "Technology Detail B",
        "DeviceDescription B",
        "Start Latitude B",
        "End Latitude B",
        "Start Longitude B",
        "End Longitude B",
        "IMEI Side B",
        "IMSI Side B",
        "Event Name Side B",
        "Phone Number B",
        "Dialed Number B",
        "Call Status B",
        "Call Type B",
        "Call Number B",
        "MO Call Domain B",
        "MO Call Setup Time (ms) B",
        "MO Call User Setup Time (ms) B",
        "MO Call Drop Rate B",
        "MO Call Setup Failure Rate B",
        "MT Call Domain B",
        "MT Call Setup Time (ms) B",
        "MT Call User Setup Time (ms) B",
        "MT Call Drop Rate B",
        "MT Call Setup Failure Rate B",
        "Call Duration B",
        "Call Setup Duration B",
        "Call Setup Time (sec) B",
        "Voice Call Setup Time (sec) B",
        "Voice Call Success Rate B",
        "Voice Call Setup Success Rate B",
        "Voice Call Setup Failure Rate B",
        "Voice Call Completion Rate B",
        "Voice Dropped Call Rate B",
        "Voice Speech Quality On Call Basis B",
        "Call Drop Rate B",
        "Call Dropped Count B",
        "Call Dropped VoLTE Count B",
        "Call Block Rate B",
        "Call Blocked Count B",
        "Call Blocked VoLTE Count B",
        "Call Success Count B",
        "Call Success Rate B",
        "Call Success VoLTE Count B",
        "Call Initiation B",
        "Call Attempt B",
        "Call Attempt Retry B",
        "Call Setup B",
        "Call Established B",
        "Call End B",
        "Call End Initiator B",
        "Call Initiation Delay B",
        "Call Initiation Failure Rate B",
        "Call Initiation Success Rate B",
        "Data Radio Bearer B",
        "Multi RAT Connectivity Mode B",
        "Radio Access Technology State B",
        "Is Multi RAB B",
        "AQM RAT B",
        "AQM Algorithm DL B",
        "AQM Audio Channel Type DL B",
        "AQM Score B",
        "AQM Score DL B",
        "Speech Codec B",
        "AMR Codec DL B",
        "AMR Codec UL B",
        "AMR Codec Name DL Top #1 B",
        "AMR Codec Usage DL Top #1 B",
        "AMR Codec Name UL Top #1 B",
        "AMR Codec Usage UL Top #1 B",
        "SQ MOS B",
        "MOS Calculator Version Downlink B",
        "Multi RAB Service Type 1 B",
        "Multi RAB Service Type 2 B",
        "AQM Downlink Call Quality B",
        "Average AQM Downlink Call Quality B",
        "POLQA SWB Score DL B",
        "POLQA Speech Codec B",
        "RTP Jitter Audio RFC3550 (ms) B",
        "RTP Lost Packets Rate Audio (%) B",
        "RTP Relative Packet Delay Audio (ms) B",
        "Codec Used B",
        "Consecutive Packets Lost B",
        "FER Combined Packet Loss B",
        "Inter arrival Jitter B",
        "Jitter Buffer Size Increase B",
        "Jitter Buffer Under runs B",
        "MO Sequence Number Received B",
        "MO Sequence Number Sent B",
        "Number Of Packets Lost B",
        "Packet Interarrival Time B",
        "Packet Loss Ratio B",
        "Payload Type Audio B",
        "RTP Time Gap B",
        "LTE Cell Identity(eNB Part) Side B",
        "LTE Cell Identity(Cell Part) Side B",
        "LTE Serving Cell Identity Side B",
        "LTE Serving Cell DL EARFCN Side B",
        "LTE Serving Cell Frequency Band Side B",
        "LTE Serving Cell Channel RSSI(dBm) Side B",
        "LTE Serving Cell RSRP(dBm) Side B",
        "LTE Serving Cell RS SINR(dB) Side B",
        "LTE Serving Cell RSRQ (dB) Side B",
        "LTE Serving Cell Count Side Average Side B",
        "LTE Secondary Serving Cell 1 Identity Side B",
        "LTE Secondary Serving Cell 1 DL EARFCN Side B",
        "LTE Secondary Serving Cell 1 Frequency Band Side B",
        "LTE Secondary Serving Cell 1 Channel RSSI (dBm) Side B",
        "LTE Secondary Serving Cell 1 RSRP (dBm) Side B",
        "LTE Secondary Serving Cell 1 RS SINR (dB) Side B",
        "LTE Secondary Serving Cell 1 RSRQ (dB) Side B",
        "LTE Neighbor Cell 1 PCI Side B",
        "LTE Neighbor Cell 1 DL EARFCN Side B",
        "LTE Neighbor Cell 1 RSRP Side B",
        "LTE Neighbor Cell 1 RSRQ Side B",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB) Side B",
        "LTE MAC DL Throughput (kbps) Side B",
        "LTE MAC DL Throughput Carrier 1 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 2 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 3 (kbps) Side B",
        "LTE MAC DL Throughput Carrier 4 (kbps) Side B",
        "LTE MAC UL Throughput (kbps) Side B",
        "LTE MAC UL Throughput Carrier 1 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 2 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 3 (kbps) Side B",
        "LTE MAC UL Throughput Carrier 4 (kbps) Side B",
        "LTE PDSCH Modulation Side B",
        "LTE PDSCH MCS Side B",
        "LTE PDSCH BLER (%) Side B",
        "LTE PDSCH Phy Throughput (kbps) Side B",
        "LTE PDSCH Phy Throughput Total (kbps) Side B",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps) Side B",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps) Side B",
        "LTE PUSCH Modulation Side B",
        "LTE PUSCH MCS Side B",
        "PUSCH BLER (%) Side B",
        "LTE UE TX Power - PUSCH (dBm) Carrier 1 Side B",
        "LTE UE TX Power - PUCCH (dBm) Carrier 1 Side B",
        "LTE PUSCH Phy Throughput (kbps) Side B",
        "LTE PUSCH Phy Throughput Total (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps) Side B",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps) Side B",
        "PUSCH Phy Throughput Carrier 4 (kbps) Side B",
        "LTE RLC Throughput DL (Kbps) Side B",
        "LTE RLC Throughput UL (Kbps) Side B",
        "LTE Bearer Maximum Bitrate DL (kbit/s) Side B",
        "LTE PDN Connection Side AMBR DL (kbps) Side B",
        "NR Serving Beam 1 Cell Identity Side B",
        "NR Serving Beam 1 NRARFCN DL Side B",
        "NR Serving Beam 1 Band Side B",
        "NR Serving Beam 1 Bandwidth DL Side B",
        "NR Serving Beam 1 Bandwidth UL Side B",
        "NR Serving Beam 1 SSB Index Side B",
        "NR Serving Beam 1 Cell Type Side B",
        "NR Serving Beam 2 Cell Identity Side B",
        "NR Serving Beam 2 NRARFCN DL Side B",
        "NR Serving Beam 2 Band Side B",
        "NR Serving Beam 2 Bandwidth DL Side B",
        "NR Serving Beam 2 Bandwidth UL Side B",
        "NR Serving Beam 2 SSB Index Side B",
        "NR Serving Beam 2 Cell Type Side B",
        "NR Serving Cell Identity Top #1 Side B",
        "NR Serving Cell NRARFCN DL Top #1 Side B",
        "NR Serving Cell SS RSSI Top #1 Side B",
        "NR Serving Cell SS RSRP Top #1 Side B",
        "NR Serving Cell SS SINR Top #1 Side B",
        "NR Serving Cell SS RSRQ Top #1 Side B",
        "NR PCell SSB Serving Beam Index Top #1 Side B",
        "NR Neighbor Cell 1 Cell Identity Side B",
        "NR Neighbor Cell 1 NRARFCN Side B",
        "NR Neighbor Cell 1 SS RSRP (dBm) Side B",
        "NR Neighbor Cell 1 SS SINR (dB) Side B",
        "NR Neighbor Cell 1 SS RSRQ (dB) Side B",
        "NR Neighbor Cell 1 Best Beam Index Side B",
        "NR Neighbor Cell 1 Cell Type Side B",
        "NR Phy Throughput Multi-RAT DL (kbps) Side B",
        "NR Phy Throughput Multi-RAT UL (kbps) Side B",
        "NR PDSCH Phy Throughput Total (Kbps) Side B",
        "NR Pcell PDSCH Scheduled Throughput (Mbps) Side B",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps) Side B",
        "NR PDSCH Modulation Serving Beam 1 Side B",
        "NR PDSCH MCS Serving Beam 1 Side B",
        "NR PDSCH BLER (%) Serving Beam 1 Side B",
        "NR PDSCH CQI Serving Beam 1 Side B",
        "NR PDSCH RI Serving Beam 1 Side B",
        "NR DL Pathloss Serving Beam 1 Side B",
        "NR PUCCH Tx Power Serving Beam 1 (dBm) Side B",
        "NR PUSCH Tx Power Serving Beam 1 (dBm) Side B",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps) Side B",
        "NR PDSCH Modulation Serving Beam 2 Side B",
        "NR PDSCH MCS Serving Beam 2 Side B",
        "NR PDSCH BLER (%) Serving Beam 2 Side B",
        "NR PDSCH CQI Serving Beam 2 Side B",
        "NR PDSCH RI Serving Beam 2 Side B",
        "NR DL Pathloss Serving Beam 2 Side B",
        "NR PUSCH Phy Throughput Total (kbps) Side B",
        "NR Pcell PUSCH Scheduled Throughput (Mbps) Side B",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps) Side B",
        "NR PUSCH Modulation Serving Beam 1 Side B",
        "NR PUSCH MCS Serving Beam 1 Side B",
        "NR PUSCH BLER (%) Serving Beam 1 Side B",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps) Side B",
        "NR PUSCH Modulation Serving Beam 2 Side B",
        "NR PUSCH MCS Serving Beam 2 Side B",
        "NR PUSCH BLER (%) Serving Beam 2 Side B",
        "NR MAC UL Throughput Total (kbps) Side B",
        "NR RLC DL Throughput Total (kbps) Side B",
        "NR RLC UL Throughput Total (kbps) Side B",
        "NR RLC UL Throughput (Kbps) Side B",
        "FirmwareVersion Side B",
        "Qualifier Side A",
        "Qualifier Side B"




   ]
}


def reorder_columns_strict(df, group_key="VoiceOTT"):
    desired_columns = schema_groups.get(group_key, [])
    # Ambil hanya kolom yang benar-benar ada di dataframe
    selected_columns = [col for col in desired_columns if col in df.columns]
    return df[selected_columns]


merged_df = reorder_columns_strict(merged_df, group_key="VoiceOTT")

# === Step 5: Setup output & log ===
output_dir = Path("/mnt/c/Users/User/Documents/Indra/geo/CDR/parsing/split/Voice_OTT/Output2")
output_dir.mkdir(exist_ok=True)
log_path = output_dir / "log.txt"

# === Step 6: Extract metadata for file naming ===
first_row = merged_df.iloc[0]
raw_date = pd.to_datetime(first_row.get("Date", pd.NaT), errors='coerce')
date_str = raw_date.strftime("%Y%m%d") if not pd.isna(raw_date) else "UnknownDate"
country = str(first_row.get("Route Name", "UnknownCountry")).replace(" ", "_")
output_file_name = f"{date_str}_{country}_BM_CDRVoice_OTT.xlsx"
output_file_path = output_dir / output_file_name

# === Step 7: Write to Excel with operator-based sheets ===
with pd.ExcelWriter(output_file_path, engine="openpyxl") as writer:
    merged_df.to_excel(writer, sheet_name="AllData", index=False)

# === Step 8: Logging ===
log_msg = f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] ✅ Saved: {output_file_name} with all operators in single sheets"
print(log_msg)
with open(log_path, "a") as log_file:
    log_file.write(log_msg + "\n")
