from typing import Any

import pandas as pd


def first_val(x: pd.Series) -> Any:
    return x.dropna().iloc[0] if not x.dropna().empty else None


def last_val(x: pd.Series) -> Any:
    return x.dropna().iloc[-1] if not x.dropna().empty else None


def modus(x: pd.Series) -> Any:
    return x.mode().iloc[0] if not x.mode().empty else None


MOS_M2M_AGG_RULES = {
    "Date Time": last_val,
    "Test Name": first_val,
    "DeviceDescription": first_val,
    "Latitude": first_val,
    "Longitude": first_val,
    "Side": first_val,
    "Country": first_val,
    "Type Mobility": last_val,
    "EventName": modus,
    "IMEI": last_val,
    "IMSI": last_val,
    "MCC": first_val,
    "MNC": first_val,
    "Operator1": first_val,
    "Technology_Detail": last_val,
    "PhoneNumber": last_val,
    "Dialed Number": last_val,
    "Call_Status": modus,
    "Call_Type": last_val,
    "Call_Number": modus,
    "Multi RAT Connectivity Mode": modus,
    "RadioAccessTechnologyState": modus,
    "Is_Multi_RAB": modus,
    "AQM_RAT": last_val,
    "AQM Algorithm DL": last_val,
    "AQM Audio Channel Type DL": last_val,
    "AQM Score": last_val,
    "AQM Score DL": last_val,
    "MOS Calculator Version Downlink": last_val,
    "Speech Codec": last_val,
    "AMR_Codec_DL": modus,
    "AMR_Codec_UL": modus,
    "AMR Codec Name DL Top #1": modus,
    "AMR Codec Usage DL Top #1": modus,
    "AMR Codec Name UL Top #1": modus,
    "AMR Codec Usage UL Top #1": modus,
    "SQ_MOS": last_val,
    "MOS Calculator Version Downlink": modus,
    "AMR_Codec_DL": modus,
    "AMR_Codec_UL": modus,
    "MultiRABServiceType1": last_val,
    "MultiRABServiceType2": last_val,
    "AQMDownlinkCallQuality": last_val,
    "AverageAQMDownlinkCallQuality": last_val,
    "POLQA SWB Score DL": last_val,
    "POLQA Speech Codec": last_val,
    "RTP Jitter Audio RFC3550 (ms)": "mean",
    "RTP Lost Packets Rate Audio (%)": "mean",
    "RTP Relative Packet Delay Audio (ms)": "mean",
    "CodecUsed": modus,
    "ConsecutivePacketsLost": last_val,
    "FERCombinedPacketLoss": "mean",
    "InterarrivalJitter": "mean",
    "JitterBufferSizeIncrease": "sum",
    "JitterBufferUnderruns": "sum",
    "MOSequenceNumberReceived": "max",
    "MOSequenceNumberSent": "max",
    "NumberOfPacketsLost": "sum",
    "PacketInterarrivalTime": "mean",
    "PacketLossRatio": "mean",
    "PayloadTypeAudio": modus,
    "RTPTimeGap": "mean",
    "RadioAccessTechnologyState": modus,
    "FirmwareVersion": modus,
    "VoiceStartTime": last_val,
    "VoiceEndTime": last_val,
}

MOS_M2M_DESIRED_ORDER = [
    "Date Time",
    "VoiceStartTime",
    "VoiceEndTime",
    "Test Id",
    "index_id",
    "Test Name",
    "Sequence",
    "DeviceDescription",
    "Latitude",
    "Longitude",
    "Operator",
    "Operator1",
    "Side",
    "Country",
    "Type Mobility",
    "VoiceLogfileName",
    "EventName",
    "IMEI",
    "IMSI",
    "MCC",
    "MNC",
    "Technology_Detail",
    "PhoneNumber",
    "Dialed Number",
    "Call_Status",
    "Call_Type",
    "Call_Number",
    "Multi RAT Connectivity Mode",
    "RadioAccessTechnologyState",
    "Is_Multi_RAB",
    "AQM_RAT",
    "AQM Algorithm DL",
    "AQM Audio Channel Type DL",
    "AQM Score",
    "AQM Score DL",
    "MOS Calculator Version Downlink",
    "Speech Codec",
    "AMR_Codec_DL",
    "AMR_Codec_UL",
    "AMR Codec Name DL Top #1",
    "AMR Codec Usage DL Top #1",
    "AMR Codec Name UL Top #1",
    "AMR Codec Usage UL Top #1",
    "SQ_MOS",
    "MOS Calculator Version Downlink",
    "AMR_Codec_DL",
    "AMR_Codec_UL",
    "MultiRABServiceType1",
    "MultiRABServiceType2",
    "AQMDownlinkCallQuality",
    "AverageAQMDownlinkCallQuality",
    "POLQA SWB Score DL",
    "POLQA Speech Codec",
    "RTP Jitter Audio RFC3550 (ms)",
    "RTP Lost Packets Rate Audio (%)",
    "RTP Relative Packet Delay Audio (ms)",
    "CodecUsed",
    "ConsecutivePacketsLost",
    "FERCombinedPacketLoss",
    "InterarrivalJitter",
    "JitterBufferSizeIncrease",
    "JitterBufferUnderruns",
    "MOSequenceNumberReceived",
    "MOSequenceNumberSent",
    "NumberOfPacketsLost",
    "PacketInterarrivalTime",
    "PacketLossRatio",
    "PayloadTypeAudio",
    "RTPTimeGap",
    "RadioAccessTechnologyState",
    "FirmwareVersion",
    "Qualifier",
]

MOS_M2M_COLUMNS_TO_FILL = [
    "DeviceDescription",
    "EventName",
    "Speech Codec",
    "Call_Status",
    "Call_Type",
    "PhoneNumber",
    "Dialed Number",
    "Multi RAT Connectivity Mode",
    "CodecUsed",
    "ConsecutivePacketsLost",
]

MOS_M2M_MEAN_COLS = [
    "AQM Score",
    "AQM Score DL",
    "SQ_MOS",
    "AQMDownlinkCallQuality",
    "AverageAQMDownlinkCallQuality",
    "POLQA SWB Score DL",
    "RTP Jitter Audio RFC3550 (ms)",
    "RTP Lost Packets Rate Audio (%)",
    "RTP Relative Packet Delay Audio (ms)",
    "ConsecutivePacketsLost",
    "FERCombinedPacketLoss",
    "InterarrivalJitter",
    "JitterBufferSizeIncrease",
    "JitterBufferUnderruns",
    "MOSequenceNumberReceived",
    "MOSequenceNumberSent",
    "NumberOfPacketsLost",
    "PacketInterarrivalTime",
    "PacketLossRatio",
    "RTPTimeGap",
]

MOS_M2M_COLS_AFTER_FFILL = [
    "IMEI",
    "IMSI",
    "AQMDownlinkCallQuality",
    "AverageAQMDownlinkCallQuality",
    "VoiceEndTime",
    "VoiceStartTime",
]