from typing import Any

import pandas as pd


def first_val(x: pd.Series) -> Any:
    return x.dropna().iloc[0] if not x.dropna().empty else None


def last_val(x: pd.Series) -> Any:
    return x.dropna().iloc[-1] if not x.dropna().empty else None


def modus(x: pd.Series) -> Any:
    return x.mode().iloc[0] if not x.mode().empty else None


VOICE_OTT_AGG_RULES = {
    "Date Time": first_val,
    "Test Name": first_val,
    "DeviceDescription": first_val,
    "Latitude": first_val,
    "Longitude": first_val,
    "Side": first_val,
    "Country": first_val,
    "Type Mobility": first_val,
    "EventName": modus,
    "IMEI": last_val,
    "IMSI": last_val,
    "MCC": first_val,
    "MNC": first_val,
    "TAC": modus,
    "Technology_Detail": modus,
    "PhoneNumber": first_val,
    "Dialed Number": modus,
    "Call_Status": modus,
    "Call_Type": modus,
    "Call_Number": modus,
    "MO_Call_Domain": modus,
    "MO_Call_Setup_Time_ms": "mean",
    "MO_Call_User_Setup_Time_ms": "mean",
    "MOCallDropRate": "mean",
    "MOCallSetupFailureRate": "mean",
    "MT_Call_Domain": modus,
    "MT_Call_Setup_Time_ms": "mean",
    "MT_Call_User_Setup_Time_ms": "mean",
    "MTCallDropRate": "mean",
    "MTCallSetupFailureRate": "mean",
    "Call_Duration": "sum",
    "Call_Setup_Duration": "mean",
    "Call_Setup_Time_sec": "mean",
    "Voice_Call_Setup_Time_sec": "mean",
    "Voice_Call_Success_Rate": "mean",
    "Voice_Call_Setup_Success_Rate": "mean",
    "Voice_Call_Setup_Failure_Rate": "mean",
    "Voice_Call_Completion_Rate": "mean",
    "Voice_Dropped_Call_Rate": "mean",
    "Voice_Speech_Quality_On_Call_Basis": "mean",
    "Call Drop Rate": "mean",
    "Call Dropped Count": "sum",
    "Call Dropped VoLTE Count": "sum",
    "Call Block Rate": "mean",
    "Call Blocked Count": "sum",
    "Call Blocked VoLTE Count": "sum",
    "Call Success Count": "sum",
    "Call Success Rate": "mean",
    "Call Success VoLTE Count": "sum",
    "Call Initiation": modus,
    "Call Attempt": modus,
    "Call Attempt Retry": modus,
    "Call Setup": modus,
    "Call Established": modus,
    "Call End": modus,
    "Call_End_Initiator": modus,
    "CallInitiationDelay": "mean",
    "CallInitiationFailureRate": "mean",
    "CallInitiationSuccessRate": "mean",
    "Data Radio Bearer": modus,
    "Multi RAT Connectivity Mode": modus,
    "RadioAccessTechnologyState": modus,
    "Is_Multi_RAB": modus,
    "AQM_RAT": modus,
    "AQM Algorithm DL": modus,
    "AQM Audio Channel Type DL": modus,
    "AQM Score": "mean",
    "AQM Score DL": "mean",
    "MOS Calculator Version Downlink": modus,
    "Speech Codec": modus,
    "AMR_Codec_DL": modus,
    "AMR_Codec_UL": modus,
    "AMR Codec Name DL Top #1": modus,
    "AMR Codec Usage DL Top #1": modus,
    "AMR Codec Name UL Top #1": modus,
    "AMR Codec Usage UL Top #1": modus,
    "SQ_MOS": "mean",
    "MOS Calculator Version Downlink": modus,
    "AMR_Codec_DL": modus,
    "AMR_Codec_UL": modus,
    "MultiRABServiceType1": last_val,
    "MultiRABServiceType2": last_val,
    "AQMDownlinkCallQuality": "mean",
    "AverageAQMDownlinkCallQuality": "mean",
    "POLQA SWB Score DL": "mean",
    "POLQA Speech Codec": modus,
    "RTP Jitter Audio RFC3550 (ms)": "mean",
    "RTP Lost Packets Rate Audio (%)": "mean",
    "RTP Relative Packet Delay Audio (ms)": "mean",
    "CodecUsed": modus,
    "ConsecutivePacketsLost": "sum",
    "FERCombinedPacketLoss": "mean",
    "InterarrivalJitter": "mean",
    "JitterBufferSizeIncrease": "sum",
    "JitterBufferUnderruns": "sum",
    "MOSequenceNumberReceived": "max",
    "MOSequenceNumberSent": "max",
    "NumberOfPacketsLost": "sum",
    "PacketInterarrivalTime": "mean",
    "PacketLossRatio": "mean",
    "PayloadTypeAudio": modus,
    "RTPTimeGap": "mean",
    "LTE Cell Identity(eNB Part)": modus,
    "LTE Cell Identity(Cell Part)": modus,
    "LTE Serving Cell Identity": modus,
    "LTE Serving Cell DL EARFCN": modus,
    "LTE Serving Cell Frequency Band": modus,
    "LTE Serving Cell Channel RSSI(dBm)": "mean",
    "LTE Serving Cell RSRP(dBm)": "mean",
    "LTE Serving Cell RS SINR(dB)": "mean",
    "LTE Serving Cell RSRQ (dB)": "mean",
    "LTE_Serving_Cell_Count_Average": "mean",
    "LTE Secondary Serving Cell 1 Identity": modus,
    "LTE Secondary Serving Cell 1 DL EARFCN": modus,
    "LTE Secondary Serving Cell 1 Frequency Band": modus,
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)": "mean",
    "LTE Secondary Serving Cell 1 RSRP (dBm)": "mean",
    "LTE Secondary Serving Cell 1 RS SINR (dB)": "mean",
    "LTE Secondary Serving Cell 1 RSRQ (dB)": "mean",
    "LTE Neighbor Cell 1 PCI": modus,
    "LTE Neighbor Cell 1 DL EARFCN": modus,
    "LTE Neighbor Cell 1 RSRP": "mean",
    "LTE Neighbor Cell 1 RSRQ": "mean",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)": "mean",
    "LTE MAC DL Throughput (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 1 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 2 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 3 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 4 (kbps)": "mean",
    "LTE MAC UL Throughput (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 1 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 2 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 3 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 4 (kbps)": "mean",
    "LTE PDSCH Modulation": modus,
    "LTE PDSCH MCS": modus,
    "LTE PDSCH BLER (%)": "mean",
    "LTE PDSCH Phy Throughput (kbps)": "mean",
    "LTE PDSCH Phy Throughput Total (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)": "mean",
    "LTE PUSCH Modulation ": modus,
    "LTE PUSCH MCS ": modus,
    "PUSCH BLER (%)": "mean",
    "LTE UE TX Power - PUSCH (dBm) Carrier 1": "mean",
    "LTE UE TX Power - PUCCH (dBm) Carrier 1": "mean",
    "LTE PUSCH Phy Throughput (kbps)": "mean",
    "LTE PUSCH Phy Throughput Total (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)": "mean",
    "PUSCH Phy Throughput Carrier 4 (kbps)": "mean",
    "LTE RLC Throughput DL (Kbps)": "mean",
    "LTE RLC Throughput UL (Kbps)": "mean",
    "LTE Bearer Maximum Bitrate DL (kbit/s)": "mean",
    "LTE PDN Connection AMBR DL (kbps)": "mean",
    "NR Serving Beam 1 Cell Identity": modus,
    "NR Serving Beam 1 NRARFCN DL": "mean",
    "NR Serving Beam 1 Band": modus,
    "NR Serving Beam 1 Bandwidth DL": "mean",
    "NR Serving Beam 1 Bandwidth UL": "mean",
    "NR Serving Beam 1 SSB Index": modus,
    "NR Serving Beam 1 Cell Type": modus,
    "NR Serving Beam 2 Cell Identity": modus,
    "NR Serving Beam 2 NRARFCN DL": "mean",
    "NR Serving Beam 2 Band": modus,
    "NR Serving Beam 2 Bandwidth DL": "mean",
    "NR Serving Beam 2 Bandwidth UL": "mean",
    "NR Serving Beam 2 SSB Index": modus,
    "NR Serving Beam 2 Cell Type": modus,
    "NR Serving Cell Identity Top #1": modus,
    "NR Serving Cell NRARFCN DL Top #1": modus,
    "NR Serving Cell SS RSSI Top #1": "mean",
    "NR Serving Cell SS RSRP Top #1": "mean",
    "NR Serving Cell SS SINR Top #1": "mean",
    "NR Serving Cell SS RSRQ Top #1": "mean",
    "NR PCell SSB Serving Beam Index Top #1": modus,
    "NR Neighbor Cell 1 Cell Identity": modus,
    "NR Neighbor Cell 1 NRARFCN": modus,
    "NR Neighbor Cell 1 SS RSRP (dBm)": "mean",
    "NR Neighbor Cell 1 SS SINR (dB)": "mean",
    "NR Neighbor Cell 1 SS RSRQ (dB)": "mean",
    "NR Neighbor Cell 1 Best Beam Index": modus,
    "NR Neighbor Cell 1 Cell Type": modus,
    "NR Phy Throughput Multi-RAT DL (kbps)": "mean",
    "NR Phy Throughput Multi-RAT UL (kbps)": "mean",
    "NR PDSCH Phy Throughput Total (Kbps)": "mean",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)": "mean",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)": "mean",
    "NR PDSCH Modulation Serving Beam 1": modus,
    "NR PDSCH MCS Serving Beam 1": modus,
    "NR PDSCH BLER (%) Serving Beam 1": "mean",
    "NR PDSCH CQI Serving Beam 1": "mean",
    "NR PDSCH RI Serving Beam 1": "mean",
    "NR DL Pathloss Serving Beam 1": "mean",
    "NR PUCCH Tx Power Serving Beam 1 (dBm) ": "mean",
    "NR PUSCH Tx Power Serving Beam 1 (dBm) ": "mean",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)": "mean",
    "NR PDSCH Modulation Serving Beam 2": modus,
    "NR PDSCH MCS Serving Beam 2": modus,
    "NR PDSCH BLER (%) Serving Beam 2": "mean",
    "NR PDSCH CQI Serving Beam 2": "mean",
    "NR PDSCH RI Serving Beam 2": "mean",
    "NR DL Pathloss Serving Beam 2": "mean",
    "NR PUSCH Phy Throughput Total (kbps)": "mean",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)": "mean",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)": "mean",
    "NR PUSCH Modulation Serving Beam 1": modus,
    "NR PUSCH MCS Serving Beam 1": modus,
    "NR PUSCH BLER (%) Serving Beam 1": "mean",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)": "mean",
    "NR PUSCH Modulation Serving Beam 2": modus,
    "NR PUSCH MCS Serving Beam 2": modus,
    "NR PUSCH BLER (%) Serving Beam 2": "mean",
    "NR MAC UL Throughput Total (kbps)": "sum",
    "NR RLC DL Throughput Total (kbps)": "sum",
    "NR RLC UL Throughput Total (kbps)": "sum",
    "NR RLC UL Throughput (Kbps)": "sum",
    "RadioAccessTechnologyState": modus,
    "FirmwareVersion": modus,
    "VoiceStartTime": last_val,
    "VoiceEndTime": last_val,
}

VOICE_OTT_DESIRED_ORDER = [
    "Date Time",
    "VoiceStartTime",
    "VoiceEndTime",
    "Test Id",
    "Test Name",
    "Type Mobility",
    "Side",
    "Side_Group_Index",
    "Pair_ID",
    "DeviceDescription",
    "VoiceLogfileName",
    "Operator",
    "Country",
    "Sequence",
    "Latitude",
    "Longitude",
    "EventName",
    "IMEI",
    "IMSI",
    "MCC",
    "MNC",
    "TAC",
    "Technology_Detail",
    "PhoneNumber",
    "Dialed Number",
    "Call_Status",
    "Call_Type",
    "Call_Number",
    "MO_Call_Domain",
    "MO_Call_Setup_Time_ms",
    "MO_Call_User_Setup_Time_ms",
    "MOCallDropRate",
    "MOCallSetupFailureRate",
    "MT_Call_Domain",
    "MT_Call_Setup_Time_ms",
    "MT_Call_User_Setup_Time_ms",
    "MTCallDropRate",
    "MTCallSetupFailureRate",
    "Call_Duration",
    "Call_Setup_Duration",
    "Call_Setup_Time_sec",
    "Voice_Call_Setup_Time_sec",
    "Voice_Call_Success_Rate",
    "Voice_Call_Setup_Success_Rate",
    "Voice_Call_Setup_Failure_Rate",
    "Voice_Call_Completion_Rate",
    "Voice_Dropped_Call_Rate",
    "Voice_Speech_Quality_On_Call_Basis",
    "Call Drop Rate",
    "Call Dropped Count",
    "Call Dropped VoLTE Count",
    "Call Block Rate",
    "Call Blocked Count",
    "Call Blocked VoLTE Count",
    "Call Success Count",
    "Call Success Rate",
    "Call Success VoLTE Count",
    "Call Initiation",
    "Call Attempt",
    "Call Attempt Retry",
    "Call Setup",
    "Call Established",
    "Call End",
    "Call_End_Initiator",
    "CallInitiationDelay",
    "CallInitiationFailureRate",
    "CallInitiationSuccessRate",
    "Data Radio Bearer",
    "Multi RAT Connectivity Mode",
    "RadioAccessTechnologyState",
    "Is_Multi_RAB",
    "AQM_RAT",
    "AQM Algorithm DL",
    "AQM Audio Channel Type DL",
    "AQM Score",
    "AQM Score DL",
    "MOS Calculator Version Downlink",
    "Speech Codec",
    "AMR_Codec_DL",
    "AMR_Codec_UL",
    "AMR Codec Name DL Top #1",
    "AMR Codec Usage DL Top #1",
    "AMR Codec Name UL Top #1",
    "AMR Codec Usage UL Top #1",
    "SQ_MOS",
    "MOS Calculator Version Downlink",
    "AMR_Codec_DL",
    "AMR_Codec_UL",
    "MultiRABServiceType1",
    "MultiRABServiceType2",
    "AQMDownlinkCallQuality",
    "AverageAQMDownlinkCallQuality",
    "POLQA SWB Score DL",
    "POLQA Speech Codec",
    "RTP Jitter Audio RFC3550 (ms)",
    "RTP Lost Packets Rate Audio (%)",
    "RTP Relative Packet Delay Audio (ms)",
    "CodecUsed",
    "ConsecutivePacketsLost",
    "FERCombinedPacketLoss",
    "InterarrivalJitter",
    "JitterBufferSizeIncrease",
    "JitterBufferUnderruns",
    "MOSequenceNumberReceived",
    "MOSequenceNumberSent",
    "NumberOfPacketsLost",
    "PacketInterarrivalTime",
    "PacketLossRatio",
    "PayloadTypeAudio",
    "RTPTimeGap",
    "LTE Cell Identity(eNB Part)",
    "LTE Cell Identity(Cell Part)",
    "LTE Serving Cell Identity",
    "LTE Serving Cell DL EARFCN",
    "LTE Serving Cell Frequency Band",
    "LTE Serving Cell Channel RSSI(dBm)",
    "LTE Serving Cell RSRP(dBm)",
    "LTE Serving Cell RS SINR(dB)",
    "LTE Serving Cell RSRQ (dB)",
    "LTE_Serving_Cell_Count_Average",
    "LTE Secondary Serving Cell 1 Identity",
    "LTE Secondary Serving Cell 1 DL EARFCN",
    "LTE Secondary Serving Cell 1 Frequency Band",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)",
    "LTE Secondary Serving Cell 1 RSRP (dBm)",
    "LTE Secondary Serving Cell 1 RS SINR (dB)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)",
    "LTE Neighbor Cell 1 PCI",
    "LTE Neighbor Cell 1 DL EARFCN",
    "LTE Neighbor Cell 1 RSRP",
    "LTE Neighbor Cell 1 RSRQ",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "LTE MAC DL Throughput (kbps)",
    "LTE MAC DL Throughput Carrier 1 (kbps)",
    "LTE MAC DL Throughput Carrier 2 (kbps)",
    "LTE MAC DL Throughput Carrier 3 (kbps)",
    "LTE MAC DL Throughput Carrier 4 (kbps)",
    "LTE MAC UL Throughput (kbps)",
    "LTE MAC UL Throughput Carrier 1 (kbps)",
    "LTE MAC UL Throughput Carrier 2 (kbps)",
    "LTE MAC UL Throughput Carrier 3 (kbps)",
    "LTE MAC UL Throughput Carrier 4 (kbps)",
    "LTE PDSCH Modulation",
    "LTE PDSCH MCS",
    "LTE PDSCH BLER (%)",
    "LTE PDSCH Phy Throughput (kbps)",
    "LTE PDSCH Phy Throughput Total (kbps)",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Modulation ",
    "LTE PUSCH MCS ",
    "PUSCH BLER (%)",
    "LTE UE TX Power - PUSCH (dBm) Carrier 1",
    "LTE UE TX Power - PUCCH (dBm) Carrier 1",
    "LTE PUSCH Phy Throughput (kbps)",
    "LTE PUSCH Phy Throughput Total (kbps)",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Phy Throughput Carrier 4 (kbps)",
    "LTE RLC Throughput DL (Kbps)",
    "LTE RLC Throughput UL (Kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)",
    "NR Serving Beam 1 Cell Identity",
    "NR Serving Beam 1 NRARFCN DL",
    "NR Serving Beam 1 Band",
    "NR Serving Beam 1 Bandwidth DL",
    "NR Serving Beam 1 Bandwidth UL",
    "NR Serving Beam 1 SSB Index",
    "NR Serving Beam 1 Cell Type",
    "NR Serving Beam 2 Cell Identity",
    "NR Serving Beam 2 NRARFCN DL",
    "NR Serving Beam 2 Band",
    "NR Serving Beam 2 Bandwidth DL",
    "NR Serving Beam 2 Bandwidth UL",
    "NR Serving Beam 2 SSB Index",
    "NR Serving Beam 2 Cell Type",
    "NR Serving Cell Identity Top #1",
    "NR Serving Cell NRARFCN DL Top #1",
    "NR Serving Cell SS RSSI Top #1",
    "NR Serving Cell SS RSRP Top #1",
    "NR Serving Cell SS SINR Top #1",
    "NR Serving Cell SS RSRQ Top #1",
    "NR PCell SSB Serving Beam Index Top #1",
    "NR Neighbor Cell 1 Cell Identity",
    "NR Neighbor Cell 1 NRARFCN",
    "NR Neighbor Cell 1 SS RSRP (dBm)",
    "NR Neighbor Cell 1 SS SINR (dB)",
    "NR Neighbor Cell 1 SS RSRQ (dB)",
    "NR Neighbor Cell 1 Best Beam Index",
    "NR Neighbor Cell 1 Cell Type",
    "NR Phy Throughput Multi-RAT DL (kbps)",
    "NR Phy Throughput Multi-RAT UL (kbps)",
    "NR PDSCH Phy Throughput Total (Kbps)",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PDSCH Modulation Serving Beam 1",
    "NR PDSCH MCS Serving Beam 1",
    "NR PDSCH BLER (%) Serving Beam 1",
    "NR PDSCH CQI Serving Beam 1",
    "NR PDSCH RI Serving Beam 1",
    "NR DL Pathloss Serving Beam 1",
    "NR PUCCH Tx Power Serving Beam 1 (dBm) ",
    "NR PUSCH Tx Power Serving Beam 1 (dBm) ",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PDSCH Modulation Serving Beam 2",
    "NR PDSCH MCS Serving Beam 2",
    "NR PDSCH BLER (%) Serving Beam 2",
    "NR PDSCH CQI Serving Beam 2",
    "NR PDSCH RI Serving Beam 2",
    "NR DL Pathloss Serving Beam 2",
    "NR PUSCH Phy Throughput Total (kbps)",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PUSCH Modulation Serving Beam 1",
    "NR PUSCH MCS Serving Beam 1",
    "NR PUSCH BLER (%) Serving Beam 1",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PUSCH Modulation Serving Beam 2",
    "NR PUSCH MCS Serving Beam 2",
    "NR PUSCH BLER (%) Serving Beam 2",
    "NR MAC UL Throughput Total (kbps)",
    "NR RLC DL Throughput Total (kbps)",
    "NR RLC UL Throughput Total (kbps)",
    "NR RLC UL Throughput (Kbps)",
    "RadioAccessTechnologyState",
    "FirmwareVersion",
    "Qualifier"


    ]

VOICE_OTT_MEAN_COLS = [
    "MO_Call_Setup_Time_ms",
    "MO_Call_User_Setup_Time_ms",
    "MOCallDropRate",
    "MOCallSetupFailureRate",
    "MT_Call_Setup_Time_ms",
    "MT_Call_User_Setup_Time_ms",
    "MTCallDropRate",
    "MTCallSetupFailureRate",
    "Call_Duration",
    "Call_Setup_Duration",
    "Call_Setup_Time_sec",
    "Voice_Call_Setup_Time_sec",
    "Voice_Call_Success_Rate",
    "Voice_Call_Setup_Success_Rate",
    "Voice_Call_Setup_Failure_Rate",
    "Voice_Call_Completion_Rate",
    "Voice_Dropped_Call_Rate",
    "Voice_Speech_Quality_On_Call_Basis",
    "Call Drop Rate",
    "Call Dropped Count",
    "Call Dropped VoLTE Count",
    "Call Block Rate",
    "Call Blocked Count",
    "Call Blocked VoLTE Count",
    "Call Success Count",
    "Call Success Rate",
    "Call Success VoLTE Count",
    "CallInitiationDelay",
    "CallInitiationFailureRate",
    "CallInitiationSuccessRate",
    "AQM Score",
    "AQM Score DL",
    "SQ_MOS",
    "AQMDownlinkCallQuality",
    "AverageAQMDownlinkCallQuality",
    "POLQA SWB Score DL",
    "RTP Jitter Audio RFC3550 (ms)",
    "RTP Lost Packets Rate Audio (%)",
    "RTP Relative Packet Delay Audio (ms)",
    "ConsecutivePacketsLost",
    "FERCombinedPacketLoss",
    "InterarrivalJitter",
    "JitterBufferSizeIncrease",
    "JitterBufferUnderruns",
    "MOSequenceNumberReceived",
    "MOSequenceNumberSent",
    "NumberOfPacketsLost",
    "PacketInterarrivalTime",
    "PacketLossRatio",
    "RTPTimeGap",
    "LTE Serving Cell Channel RSSI(dBm)",
    "LTE Serving Cell RSRP(dBm)",
    "LTE Serving Cell RS SINR(dB)",
    "LTE Serving Cell RSRQ (dB)",
    "LTE_Serving_Cell_Count_Average",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)",
    "LTE Secondary Serving Cell 1 RSRP (dBm)",
    "LTE Secondary Serving Cell 1 RS SINR (dB)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)",
    "LTE Neighbor Cell 1 RSRP",
    "LTE Neighbor Cell 1 RSRQ",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "LTE MAC DL Throughput (kbps)",
    "LTE MAC DL Throughput Carrier 1 (kbps)",
    "LTE MAC DL Throughput Carrier 2 (kbps)",
    "LTE MAC DL Throughput Carrier 3 (kbps)",
    "LTE MAC DL Throughput Carrier 4 (kbps)",
    "LTE MAC UL Throughput (kbps)",
    "LTE MAC UL Throughput Carrier 1 (kbps)",
    "LTE MAC UL Throughput Carrier 2 (kbps)",
    "LTE MAC UL Throughput Carrier 3 (kbps)",
    "LTE MAC UL Throughput Carrier 4 (kbps)",
    "LTE PDSCH BLER (%)",
    "LTE PDSCH Phy Throughput (kbps)",
    "LTE PDSCH Phy Throughput Total (kbps)",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "PUSCH BLER (%)",
    "LTE UE TX Power - PUSCH (dBm) Carrier 1",
    "LTE UE TX Power - PUCCH (dBm) Carrier 1",
    "LTE PUSCH Phy Throughput (kbps)",
    "LTE PUSCH Phy Throughput Total (kbps)",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Phy Throughput Carrier 4 (kbps)",
    "LTE RLC Throughput DL (Kbps)",
    "LTE RLC Throughput UL (Kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)",
    "NR Serving Beam 1 NRARFCN DL",
    "NR Serving Beam 1 Bandwidth DL",
    "NR Serving Beam 1 Bandwidth UL",
    "NR Serving Beam 2 NRARFCN DL",
    "NR Serving Beam 2 Bandwidth DL",
    "NR Serving Beam 2 Bandwidth UL",
    "NR Serving Cell SS RSSI Top #1",
    "NR Serving Cell SS RSRP Top #1",
    "NR Serving Cell SS SINR Top #1",
    "NR Serving Cell SS RSRQ Top #1",
    "NR Neighbor Cell 1 SS RSRP (dBm)",
    "NR Neighbor Cell 1 SS SINR (dB)",
    "NR Neighbor Cell 1 SS RSRQ (dB)",
    "NR Phy Throughput Multi-RAT DL (kbps)",
    "NR Phy Throughput Multi-RAT UL (kbps)",
    "NR PDSCH Phy Throughput Total (Kbps)",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PDSCH BLER (%) Serving Beam 1",
    "NR PDSCH CQI Serving Beam 1",
    "NR PDSCH RI Serving Beam 1",
    "NR DL Pathloss Serving Beam 1",
    "NR PUCCH Tx Power Serving Beam 1 (dBm) ",
    "NR PUSCH Tx Power Serving Beam 1 (dBm) ",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PDSCH BLER (%) Serving Beam 2",
    "NR PDSCH CQI Serving Beam 2",
    "NR PDSCH RI Serving Beam 2",
    "NR DL Pathloss Serving Beam 2",
    "NR PUSCH Phy Throughput Total (kbps)",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PUSCH BLER (%) Serving Beam 1",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PUSCH BLER (%) Serving Beam 2",
    "NR MAC UL Throughput Total (kbps)",
    "NR RLC DL Throughput Total (kbps)",
    "NR RLC UL Throughput Total (kbps)",
    "NR RLC UL Throughput (Kbps)",
]
