from typing import Any

import pandas as pd


def first_val(x: pd.Series) -> Any:
    return x.dropna().iloc[0] if not x.dropna().empty else None


def last_val(x: pd.Series) -> Any:
    return x.dropna().iloc[-1] if not x.dropna().empty else None


def modus(x: pd.Series) -> Any:
    return x.mode().iloc[0] if not x.mode().empty else None


STREAMING_DESIRED_ORDER = [
    "Date Time",
    "Stop Date Time",
    "Test Id",
    "Test Name",
    "Type Mobility",
    "Operator",
    "Country",
    "Sequence",
    "Latitude",
    "Longitude",
    "MNC",
    "Technology_Detail",
    "StreamingDevice",
    "StreamingOperator",
    "StreamingImsi",
    "TAC",
    "StreamingStartLongitude",
    "StreamingStartLatitude",
    "StreamingEndLongitude",
    "StreamingEndLatitude",
    "StreamingStartRat",
    "StreamingEndRat",
    "Play Request to 1st Picture",
    "StreamingStartMultiRATConnectivityMode",
    "StreamingEndMultiRATConnectivityMode",
    "StreamingStartTime",
    "StreamingEndTime",
    "StreamingLogfileName",
    "Streaming_URL",
    "Streaming_Outcome_Type",
    "Aborted_by_User",
    "Streaming_Completion_Rate",
    "Streaming_Setup_Success_Rate",
    "Streaming_Success_Rate",
    "StreamingDataRadioBearer",
    "StreamingServiceBearer",
    "StreamingSessionIdentity",
    "StreamingSessionTime",
    "Streaming_Session_Failure_Ratio",
    "Streaming_Number_Of_Video_Session_Interruptions",
    "Streaming_Total_Duration_Of_Video_Session_Interruptions",
    "Streaming_Maximum_Duration_Of_Video_Session_Interruptions",
    "Streaming_Session_Without_Interruption_Rate",
    "Streaming_Duration",
    "Seconds_Start_to_End_Streaming",
    "Streaming_HD_Resolution",
    "Streaming_HD_Resolution_Ratio",
    "Streaming_Average_Session_Resolution",
    "Streaming_Average_Throughput",
    "StreamingThroughputAvg",
    "Streaming_Throughput_Filtered",
    "StreamingPlayerDownloadDataTransferTime",
    "StreamingPlayerIpServiceAccessTime",
    "StreamingPlayerSessionTime",
    "StreamingProbeName",
    "StreamingProbeVersion",
    "StreamingReproductionStartDelay",
    "StreamingResolutionAvg",
    "StreamingServiceStatus",
    "StreamingServiceAccessTime",
    "Streaming_Service_Access_Time_ms",
    "Streaming_Service_Access_Time_sec",
    "Streaming_Service_Non_Accessibility",
    "StreamingInterruptionDurationTotal",
    "StreamingInterruptionDurationMax",
    "Streaming_State_Event_Source_Time",
    "Streaming_State_Prebuffering_to_Reproducing_Delay",
    "Streaming_State_Request_to_Prebuffering_Delay",
    "Streaming_State_Request_to_Reproducing_Delay",
    "StreamingStateBufferingCompleteTime",
    "StreamingStateDoneTime",
    "StreamingStatePlayerDownloadEndTime",
    "StreamingStatePlayerDownloadStartTime",
    "StreamingStatePlayerRequestTime",
    "StreamingStatePrebufferingTime",
    "StreamingStateRebufferingTime",
    "StreamingStateReproducingTime",
    "StreamingStateVideoRequestTime",
    "StreamingTimeToFirstByte",
    "StreamingVideoInterruptionCount",
    "StreamingVideoIpServiceAccessTime",
    "StreamingVideoPlayStartTime",
    "StreamingVideoSessionTime",
    "Streaming_Video_IP_Service_Access_Time_ms",
    "Streaming_Video_IP_Service_Access_Time_sec",
    "Streaming_Video_Play_Start_Failure_Ratio",
    "Streaming_Video_Play_Start_Time_sec",
    "Streaming_Video_Session_Cutoff_Ratio",
    "Streaming_Video_Session_Failure_Ratio",
    "Streaming_Video_Session_Success_Ratio",
    "Streaming_Video_Session_Time_sec",
    "Streaming_Reproduction_Cutoff_Ratio",
    "Streaming_Reproduction_Start_Delay_sec",
    "Streaming_Reproduction_Start_Failure_Ratio",
    "Streaming_Impairment_Free",
    "Streaming_Impairment_Free_Video_Session_Ratio",
    "LTE Cell Identity(eNB Part)",
    "LTE Cell Identity(Cell Part)",
    "LTE Serving Cell Identity",
    "LTE Serving Cell DL EARFCN",
    "LTE Serving Cell Frequency Band",
    "LTE Serving Cell Channel RSSI(dBm)",
    "LTE Serving Cell RSRP(dBm)",
    "LTE Serving Cell RS SINR(dB)",
    "LTE Serving Cell RSRQ (dB)",
    "LTE_Serving_Cell_Count_Average",
    "LTE Secondary Serving Cell 1 Identity",
    "LTE Secondary Serving Cell 1 DL EARFCN",
    "LTE Secondary Serving Cell 1 Frequency Band",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)",
    "LTE Secondary Serving Cell 1 RSRP (dBm)",
    "LTE Secondary Serving Cell 1 RS SINR (dB)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)",
    "LTE Neighbor Cell 1 PCI",
    "LTE Neighbor Cell 1 DL EARFCN",
    "LTE Neighbor Cell 1 RSRP",
    "LTE Neighbor Cell 1 RSRQ",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "LTE MAC DL Throughput (kbps)",
    "LTE MAC DL Throughput Carrier 1 (kbps)",
    "LTE MAC DL Throughput Carrier 2 (kbps)",
    "LTE MAC DL Throughput Carrier 3 (kbps)",
    "LTE MAC DL Throughput Carrier 4 (kbps)",
    "LTE MAC UL Throughput (kbps)",
    "LTE MAC UL Throughput Carrier 1 (kbps)",
    "LTE MAC UL Throughput Carrier 2 (kbps)",
    "LTE MAC UL Throughput Carrier 3 (kbps)",
    "LTE MAC UL Throughput Carrier 4 (kbps)",
    "LTE PDSCH Modulation",
    "LTE PDSCH MCS",
    "LTE PDSCH BLER (%)",
    "LTE PDSCH Phy Throughput (kbps)",
    "LTE PDSCH Phy Throughput Total (kbps)",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
    "LTE PUSCH Modulation ",
    "LTE PUSCH MCS ",
    "PUSCH BLER (%)",
    "LTE PUSCH Phy Throughput (kbps)",
    "LTE PUSCH Phy Throughput Total (kbps)",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Phy Throughput Carrier 4 (kbps)",
    "LTE RLC Throughput DL (Kbps)",
    "LTE RLC Throughput UL (Kbps)",
    "NR Serving Beam 1 Cell Identity",
    "NR Serving Beam 1 NRARFCN DL",
    "NR Serving Beam 1 Band",
    "NR Serving Beam 1 Bandwidth DL",
    "NR Serving Beam 1 Bandwidth UL",
    "NR Serving Beam 1 SSB Index",
    "NR Serving Beam 1 Cell Type",
    "NR Serving Beam 1 GSCN",
    "NR Serving Beam 2 Cell Identity",
    "NR Serving Beam 2 NRARFCN DL",
    "NR Serving Beam 2 Band",
    "NR Serving Beam 2 Bandwidth DL",
    "NR Serving Beam 2 Bandwidth UL",
    "NR Serving Beam 2 SSB Index",
    "NR Serving Beam 2 Cell Type",
    "NR Serving Beam 2 GSCN",
    "NR Serving Cell Identity Top #1",
    "NR Serving Cell NRARFCN DL Top #1",
    "NR Serving Cell SS RSSI Top #1",
    "NR Serving Cell SS RSRP Top #1",
    "NR Serving Cell SS SINR Top #1",
    "NR Serving Cell SS RSRQ Top #1",
    "NR PCell SSB Serving Beam Index Top #1",
    "NR Neighbor Cell 1 Cell Identity",
    "NR Neighbor Cell 1 NRARFCN",
    "NR Neighbor Cell 1 SS RSRP (dBm)",
    "NR Neighbor Cell 1 SS SINR (dB)",
    "NR Neighbor Cell 1 SS RSRQ (dB)",
    "NR Neighbor Cell 1 Best Beam Index",
    "NR Neighbor Cell 1 Cell Type",
    "NR Phy Throughput Multi-RAT DL (kbps)",
    "NR Phy Throughput Multi-RAT UL (kbps)",
    "NR PDSCH Phy Throughput Total (Kbps)",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PDSCH Modulation Serving Beam 1",
    "NR PDSCH MCS Serving Beam 1",
    "NR PDSCH BLER (%) Serving Beam 1",
    "NR PDSCH CQI Serving Beam 1",
    "NR PDSCH RI Serving Beam 1",
    "NR DL Pathloss Serving Beam 1",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PDSCH Modulation Serving Beam 2",
    "NR PDSCH MCS Serving Beam 2",
    "NR PDSCH BLER (%) Serving Beam 2",
    "NR PDSCH CQI Serving Beam 2",
    "NR PDSCH RI Serving Beam 2",
    "NR DL Pathloss Serving Beam 2",
    "NR PUSCH Phy Throughput Total (kbps)",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PUSCH Modulation Serving Beam 1",
    "NR PUSCH MCS Serving Beam 1",
    "NR PUSCH BLER (%) Serving Beam 1",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PUSCH Modulation Serving Beam 2",
    "NR PUSCH MCS Serving Beam 2",
    "NR PUSCH BLER (%) Serving Beam 2",
    "NR MAC DL Throughput Total (kbps)",
    "NR MAC UL Throughput Total (kbps)",
    "NR RLC DL Throughput Total (kbps)",
    "NR RLC UL Throughput Total (kbps)",
    "NR RLC DL Throughput (Kbps)",
    "NR RLC UL Throughput (Kbps)",
    "NR BWP Center NR-ARFCN DL Serving Beam 1",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
    "NR BWP ID DL Serving Beam 1",
    "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Subcarrier Spacing DL Serving Beam 1",
    "NR BWPs Configured Count DL serving Beam 1",
    "NR BWP Center NR-ARFCN DL Serving Beam 2",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
    "NR BWP ID DL Serving Beam 2",
    "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Subcarrier Spacing DL Serving Beam 2",
    "NR BWPs Configured Count DL serving Beam 2",
    "NR BWP Center NR-ARFCN UL Serving Beam 1",
    "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
    "NR BWP ID UL Serving Beam 1",
    "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Subcarrier Spacing UL Serving Beam 1",
    "NR BWPs Configured Count UL Serving Beam 1",
    "NR BWP Center NR-ARFCN UL Serving Beam 2",
    "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
    "NR BWP ID UL Serving Beam 2",
    "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Subcarrier Spacing UL Serving Beam 2",
    "NR BWPs Configured Count UL Serving Beam 2",
    "RadioAccessTechnologyState",
    "MR-DC Cell 1 SINR (dB)",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
    "PDSCH BWP ID Serving Beam 1",
    "PDSCH RB Allocation Count Serving Beam 1",
    "PDSCH RB Allocation Count per TB Serving Beam 1",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)",
    "PDSCH RBG Size Serving Beam 1",
    "PDSCH Slot Allocation Count Serving Beam 1",
    "PDSCH Slot Allocation Count per TB Serving Beam 1",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)",
    "PDSCH Slot Utilization Serving Beam 1 (%)",
    "PDSCH RB Dist Current Count Serving Beam 1",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
    "PDSCH BWP ID Serving Beam 2",
    "PDSCH RB Allocation Count Serving Beam 2",
    "PDSCH RB Allocation Count per TB Serving Beam 2",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)",
    "PDSCH RBG Size Serving Beam 2",
    "PDSCH Slot Allocation Count Serving Beam 2",
    "PDSCH Slot Allocation Count per TB Serving Beam 2",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)",
    "PDSCH Slot Utilization Serving Beam 2 (%)",
    "PDSCH RB Dist Current Count Serving Beam 2",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1",
    "PUSCH BWP ID Serving Beam 1",
    "PUSCH RB Allocation Count Serving Beam 1",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)",
    "PUSCH RBG Size Serving Beam 1",
    "PUSCH Slot Allocation Count Serving Beam 1",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)",
    "PUSCH Slot Utilization Serving Beam 1 (%)",
    "PUSCH RB Dist Current Count Serving Beam 1",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2",
    "PUSCH BWP ID Serving Beam 2",
    "PUSCH RB Allocation Count Serving Beam 2",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)",
    "PUSCH RBG Size Serving Beam 2",
    "PUSCH Slot Allocation Count Serving Beam 2",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)",
    "PUSCH Slot Utilization Serving Beam 2 (%)",
    "PUSCH RB Dist Current Count Serving Beam 2",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2",
    "Radio Common Throughput DL (kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)",
    "FirmwareVersion",
    "Qualifier",
]

STREAMING_AGG_RULES = {
    "Date Time": first_val,
    "Streaming_Outcome_Type": last_val,
    "StreamingServiceStatus": last_val,
    "StreamingLogfileName": last_val,
    "MNC": first_val,
    "Type Mobility": first_val,
    "Country": first_val,
    "Latitude": first_val,
    "Longitude": first_val,
    "Technology_Detail": modus,
    "StreamingDevice": last_val,
    "StreamingOperator": last_val,
    "StreamingImsi": last_val,
    "TAC": modus,
    "StreamingStartLongitude": first_val,
    "StreamingStartLatitude": first_val,
    "StreamingEndLongitude": last_val,
    "StreamingEndLatitude": last_val,
    "StreamingStartRat": modus,
    "StreamingEndRat": modus,
    "StreamingStartMultiRATConnectivityMode": modus,
    "StreamingEndMultiRATConnectivityMode": modus,
    "StreamingStartTime": last_val,
    "StreamingEndTime": last_val,
    "Aborted_by_User": "sum",
    "Streaming_Completion_Rate": "mean",
    "Streaming_Setup_Success_Rate": "mean",
    "Streaming_Success_Rate": "mean",
    "StreamingDataRadioBearer": modus,
    "StreamingServiceBearer": modus,
    "StreamingSessionIdentity": last_val,
    "StreamingSessionTime": "mean",
    "Streaming_Session_Failure_Ratio": "mean",
    "Streaming_Number_Of_Video_Session_Interruptions": "sum",
    "Streaming_Total_Duration_Of_Video_Session_Interruptions": "sum",
    "Streaming_Maximum_Duration_Of_Video_Session_Interruptions": "max",
    "Streaming_Session_Without_Interruption_Rate": "mean",
    "Streaming_Duration": "mean",
    "Seconds_Start_to_End_Streaming": "mean",
    "Streaming_HD_Resolution": modus,
    "Streaming_HD_Resolution_Ratio": "mean",
    "Streaming_Average_Session_Resolution": "mean",
    "Streaming_Average_Throughput": "mean",
    "StreamingThroughputAvg": "mean",
    "Streaming_Throughput_Filtered": "mean",
    "StreamingPlayerDownloadDataTransferTime": "mean",
    "StreamingPlayerIpServiceAccessTime": "mean",
    "StreamingPlayerSessionTime": "mean",
    "StreamingProbeName": last_val,
    "StreamingProbeVersion": last_val,
    "StreamingReproductionStartDelay": "mean",
    "StreamingResolutionAvg": "mean",
    "StreamingServiceAccessTime": "mean",
    "Streaming_Service_Access_Time_ms": "mean",
    "Streaming_Service_Access_Time_sec": "mean",
    "Streaming_Service_Non_Accessibility": "mean",
    "StreamingInterruptionDurationTotal": "sum",
    "StreamingInterruptionDurationMax": "max",
    "Streaming_State_Event_Source_Time": "mean",
    "Streaming_State_Prebuffering_to_Reproducing_Delay": "mean",
    "Streaming_State_Request_to_Prebuffering_Delay": "mean",
    "Streaming_State_Request_to_Reproducing_Delay": "mean",
    "StreamingStateBufferingCompleteTime": last_val,
    "StreamingStateDoneTime": last_val,
    "StreamingStatePlayerDownloadEndTime": last_val,
    "StreamingStatePlayerDownloadStartTime": last_val,
    "StreamingStatePlayerRequestTime": last_val,
    "StreamingStatePrebufferingTime": last_val,
    "StreamingStateRebufferingTime": "mean",
    "StreamingStateReproducingTime": last_val,
    "StreamingStateVideoRequestTime": last_val,
    "StreamingTimeToFirstByte": "mean",
    "StreamingVideoInterruptionCount": "mean",
    "StreamingVideoIpServiceAccessTime": "mean",
    "StreamingVideoPlayStartTime": "mean",
    "StreamingVideoSessionTime": "mean",
    "Streaming_Video_IP_Service_Access_Time_ms": "mean",
    "Streaming_Video_IP_Service_Access_Time_sec": "mean",
    "Streaming_Video_Play_Start_Failure_Ratio": "mean",
    "Streaming_Video_Play_Start_Time_sec": "mean",
    "Streaming_Video_Session_Cutoff_Ratio": "mean",
    "Streaming_Video_Session_Failure_Ratio": "mean",
    "Streaming_Video_Session_Success_Ratio": "mean",
    "Streaming_Video_Session_Time_sec": "mean",
    "Streaming_Reproduction_Cutoff_Ratio": "mean",
    "Streaming_Reproduction_Start_Delay_sec": "mean",
    "Streaming_Reproduction_Start_Failure_Ratio": "mean",
    "Streaming_Impairment_Free": modus,
    "Streaming_Impairment_Free_Video_Session_Ratio": "mean",
    "LTE Cell Identity(eNB Part)": modus,
    "LTE Cell Identity(Cell Part)": modus,
    "LTE Serving Cell Identity": modus,
    "LTE Serving Cell DL EARFCN": modus,
    "LTE Serving Cell Frequency Band": modus,
    "LTE Serving Cell Channel RSSI(dBm)": "mean",
    "LTE Serving Cell RSRP(dBm)": "mean",
    "LTE Serving Cell RS SINR(dB)": "mean",
    "LTE Serving Cell RSRQ (dB)": "mean",
    "LTE_Serving_Cell_Count_Average": "mean",
    "LTE Secondary Serving Cell 1 Identity": modus,
    "LTE Secondary Serving Cell 1 DL EARFCN": modus,
    "LTE Secondary Serving Cell 1 Frequency Band": modus,
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)": "mean",
    "LTE Secondary Serving Cell 1 RSRP (dBm)": "mean",
    "LTE Secondary Serving Cell 1 RS SINR (dB)": "mean",
    "LTE Secondary Serving Cell 1 RSRQ (dB)": "mean",
    "LTE Neighbor Cell 1 PCI": modus,
    "LTE Neighbor Cell 1 DL EARFCN": modus,
    "LTE Neighbor Cell 1 RSRP": "mean",
    "LTE Neighbor Cell 1 RSRQ": "mean",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)": "mean",
    "LTE MAC DL Throughput (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 1 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 2 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 3 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 4 (kbps)": "mean",
    "LTE MAC UL Throughput (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 1 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 2 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 3 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 4 (kbps)": "mean",
    "LTE PDSCH Modulation": modus,
    "LTE PDSCH MCS": modus,
    "LTE PDSCH BLER (%)": "mean",
    "LTE PDSCH Phy Throughput (kbps)": "mean",
    "LTE PDSCH Phy Throughput Total (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)": "mean",
    "LTE PUSCH Modulation ": modus,
    "LTE PUSCH MCS ": modus,
    "PUSCH BLER (%)": "mean",
    "LTE PUSCH Phy Throughput (kbps)": "mean",
    "LTE PUSCH Phy Throughput Total (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)": "mean",
    "PUSCH Phy Throughput Carrier 4 (kbps)": "mean",
    "LTE RLC Throughput DL (Kbps)": "mean",
    "LTE RLC Throughput UL (Kbps)": "mean",
    "NR Serving Beam 1 Cell Identity": modus,
    "NR Serving Beam 1 NRARFCN DL": modus,
    "NR Serving Beam 1 Band": modus,
    "NR Serving Beam 1 Bandwidth DL": modus,
    "NR Serving Beam 1 Bandwidth UL": modus,
    "NR Serving Beam 1 SSB Index": modus,
    "NR Serving Beam 1 Cell Type": modus,
    "NR Serving Beam 1 GSCN": modus,
    "NR Serving Beam 2 Cell Identity": modus,
    "NR Serving Beam 2 NRARFCN DL": modus,
    "NR Serving Beam 2 Band": modus,
    "NR Serving Beam 2 Bandwidth DL": modus,
    "NR Serving Beam 2 Bandwidth UL": modus,
    "NR Serving Beam 2 SSB Index": modus,
    "NR Serving Beam 2 Cell Type": modus,
    "NR Serving Beam 2 GSCN": modus,
    "NR Serving Cell Identity Top #1": modus,
    "NR Serving Cell NRARFCN DL Top #1": modus,
    "NR Serving Cell SS RSSI Top #1": "mean",
    "NR Serving Cell SS RSRP Top #1": "mean",
    "NR Serving Cell SS SINR Top #1": "mean",
    "NR Serving Cell SS RSRQ Top #1": "mean",
    "NR PCell SSB Serving Beam Index Top #1": modus,
    "NR Neighbor Cell 1 Cell Identity": modus,
    "NR Neighbor Cell 1 NRARFCN": modus,
    "NR Neighbor Cell 1 SS RSRP (dBm)": "mean",
    "NR Neighbor Cell 1 SS SINR (dB)": "mean",
    "NR Neighbor Cell 1 SS RSRQ (dB)": "mean",
    "NR Neighbor Cell 1 Best Beam Index": modus,
    "NR Neighbor Cell 1 Cell Type": modus,
    "NR Phy Throughput Multi-RAT DL (kbps)": "mean",
    "NR Phy Throughput Multi-RAT UL (kbps)": "mean",
    "NR PDSCH Phy Throughput Total (Kbps)": "mean",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)": "mean",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)": "mean",
    "NR PDSCH Modulation Serving Beam 1": modus,
    "NR PDSCH MCS Serving Beam 1": modus,
    "NR PDSCH BLER (%) Serving Beam 1": "mean",
    "NR PDSCH CQI Serving Beam 1": "mean",
    "NR PDSCH RI Serving Beam 1": "mean",
    "NR DL Pathloss Serving Beam 1": "mean",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)": "mean",
    "NR PDSCH Modulation Serving Beam 2": modus,
    "NR PDSCH MCS Serving Beam 2": modus,
    "NR PDSCH BLER (%) Serving Beam 2": "mean",
    "NR PDSCH CQI Serving Beam 2": "mean",
    "NR PDSCH RI Serving Beam 2": "mean",
    "NR DL Pathloss Serving Beam 2": "mean",
    "NR PUSCH Phy Throughput Total (kbps)": "mean",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)": "mean",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)": "mean",
    "NR PUSCH Modulation Serving Beam 1": modus,
    "NR PUSCH MCS Serving Beam 1": modus,
    "NR PUSCH BLER (%) Serving Beam 1": "mean",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)": "mean",
    "NR PUSCH Modulation Serving Beam 2": modus,
    "NR PUSCH MCS Serving Beam 2": modus,
    "NR PUSCH BLER (%) Serving Beam 2": "mean",
    "NR MAC DL Throughput Total (kbps)": "sum",
    "NR MAC UL Throughput Total (kbps)": "sum",
    "NR RLC DL Throughput Total (kbps)": "sum",
    "NR RLC UL Throughput Total (kbps)": "sum",
    "NR RLC DL Throughput (Kbps)": "sum",
    "NR RLC UL Throughput (Kbps)": "sum",
    "NR BWP Center NR-ARFCN DL Serving Beam 1": modus,
    "NR BWP Bandwidth DL (Mhz) Serving Beam 1": modus,
    "NR BWP ID DL Serving Beam 1": modus,
    "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)": modus,
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1": modus,
    "NR BWP Start Point NR-ARFCN DL Serving Beam 1": modus,
    "NR BWP Subcarrier Spacing DL Serving Beam 1": modus,
    "NR BWPs Configured Count DL serving Beam 1": "max",
    "NR BWP Center NR-ARFCN DL Serving Beam 2": modus,
    "NR BWP Bandwidth DL (Mhz) Serving Beam 2": modus,
    "NR BWP ID DL Serving Beam 2": modus,
    "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)": modus,
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2": modus,
    "NR BWP Start Point NR-ARFCN DL Serving Beam 2": modus,
    "NR BWP Subcarrier Spacing DL Serving Beam 2": modus,
    "NR BWPs Configured Count DL serving Beam 2": "max",
    "NR BWP Center NR-ARFCN UL Serving Beam 1": modus,
    "NR BWP Bandwidth UL Serving Beam 1 (Mhz)": modus,
    "NR BWP ID UL Serving Beam 1": modus,
    "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)": modus,
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1": modus,
    "NR BWP Start Point NR-ARFCN UL Serving Beam 1": modus,
    "NR BWP Subcarrier Spacing UL Serving Beam 1": modus,
    "NR BWPs Configured Count UL Serving Beam 1": "max",
    "NR BWP Center NR-ARFCN UL Serving Beam 2": modus,
    "NR BWP Bandwidth UL Serving Beam 2 (Mhz)": modus,
    "NR BWP ID UL Serving Beam 2": modus,
    "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)": modus,
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2": modus,
    "NR BWP Start Point NR-ARFCN UL Serving Beam 2": modus,
    "NR BWP Subcarrier Spacing UL Serving Beam 2": modus,
    "NR BWPs Configured Count UL Serving Beam 2": "max",
    "RadioAccessTechnologyState": modus,
    "MR-DC Cell 1 SINR (dB)": "mean",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1": "mean",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1": "mean",
    "PDSCH BWP ID Serving Beam 1": modus,
    "PDSCH RB Allocation Count Serving Beam 1": "sum",
    "PDSCH RB Allocation Count per TB Serving Beam 1": "sum",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)": "mean",
    "PDSCH RBG Size Serving Beam 1": modus,
    "PDSCH Slot Allocation Count Serving Beam 1": "sum",
    "PDSCH Slot Allocation Count per TB Serving Beam 1": "sum",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)": "mean",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)": "mean",
    "PDSCH Slot Utilization Serving Beam 1 (%)": "mean",
    "PDSCH RB Dist Current Count Serving Beam 1": "sum",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1": "sum",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2": "mean",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2": "mean",
    "PDSCH BWP ID Serving Beam 2": modus,
    "PDSCH RB Allocation Count Serving Beam 2": "sum",
    "PDSCH RB Allocation Count per TB Serving Beam 2": "sum",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)": "mean",
    "PDSCH RBG Size Serving Beam 2": modus,
    "PDSCH Slot Allocation Count Serving Beam 2": "sum",
    "PDSCH Slot Allocation Count per TB Serving Beam 2": "sum",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)": "mean",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)": "mean",
    "PDSCH Slot Utilization Serving Beam 2 (%)": "mean",
    "PDSCH RB Dist Current Count Serving Beam 2": "sum",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2": "sum",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1": "mean",
    "PUSCH BWP ID Serving Beam 1": modus,
    "PUSCH RB Allocation Count Serving Beam 1": "sum",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)": "mean",
    "PUSCH RBG Size Serving Beam 1": modus,
    "PUSCH Slot Allocation Count Serving Beam 1": "sum",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)": "mean",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)": "mean",
    "PUSCH Slot Utilization Serving Beam 1 (%)": "mean",
    "PUSCH RB Dist Current Count Serving Beam 1": "sum",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1": "sum",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2": "mean",
    "PUSCH BWP ID Serving Beam 2": modus,
    "PUSCH RB Allocation Count Serving Beam 2": "sum",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)": "mean",
    "PUSCH RBG Size Serving Beam 2": modus,
    "PUSCH Slot Allocation Count Serving Beam 2": "sum",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)": "mean",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)": "mean",
    "PUSCH Slot Utilization Serving Beam 2 (%)": "mean",
    "PUSCH RB Dist Current Count Serving Beam 2": "sum",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2": "sum",
    "Radio Common Throughput DL (kbps)": "mean",
    "LTE Bearer Maximum Bitrate DL (kbit/s)": "mean",
    "LTE PDN Connection AMBR DL (kbps)": "mean",
    "FirmwareVersion": modus,
}

STREAMING_MEAN_COLS = [
    "Aborted_by_User",
    "PUSCH Phy Throughput Carrier 4 (kbps)",
    "Streaming_Completion_Rate",
    "LTE RLC Throughput DL (Kbps)",
    "Streaming_Setup_Success_Rate",
    "LTE RLC Throughput UL (Kbps)",
    "Streaming_Success_Rate",
    "NR Serving Cell SS RSSI Top #1",
    "StreamingSessionTime",
    "NR Serving Cell SS RSRP Top #1",
    "Streaming_Session_Failure_Ratio",
    "NR Serving Cell SS SINR Top #1",
    "Streaming_Number_Of_Video_Session_Interruptions",
    "NR Serving Cell SS RSRQ Top #1",
    "Streaming_Total_Duration_Of_Video_Session_Interruptions",
    "NR Neighbor Cell 1 SS RSRP (dBm)",
    "Streaming_Maximum_Duration_Of_Video_Session_Interruptions",
    "NR Neighbor Cell 1 SS SINR (dB)",
    "Streaming_Session_Without_Interruption_Rate",
    "NR Neighbor Cell 1 SS RSRQ (dB)",
    "Streaming_Duration",
    "NR Phy Throughput Multi-RAT DL (kbps)",
    "Seconds_Start_to_End_Streaming",
    "NR Phy Throughput Multi-RAT UL (kbps)",
    "Streaming_HD_Resolution_Ratio",
    "NR PDSCH Phy Throughput Total (Kbps)",
    "Streaming_Average_Session_Resolution",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "Streaming_Average_Throughput",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "StreamingThroughputAvg",
    "NR PDSCH BLER (%) Serving Beam 1",
    "Streaming_Throughput_Filtered",
    "NR PDSCH CQI Serving Beam 1",
    "StreamingPlayerDownloadDataTransferTime",
    "NR PDSCH RI Serving Beam 1",
    "StreamingPlayerIpServiceAccessTime",
    "NR DL Pathloss Serving Beam 1",
    "StreamingPlayerSessionTime",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "StreamingReproductionStartDelay",
    "NR PDSCH BLER (%) Serving Beam 2",
    "StreamingResolutionAvg",
    "NR PDSCH CQI Serving Beam 2",
    "StreamingServiceAccessTime",
    "NR PDSCH RI Serving Beam 2",
    "Streaming_Service_Access_Time_ms",
    "NR DL Pathloss Serving Beam 2",
    "Streaming_Service_Access_Time_sec",
    "NR PUSCH Phy Throughput Total (kbps)",
    "Streaming_Service_Non_Accessibility",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "StreamingInterruptionDurationTotal",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "StreamingInterruptionDurationMax",
    "NR PUSCH BLER (%) Serving Beam 1",
    "Streaming_State_Event_Source_Time",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "Streaming_State_Prebuffering_to_Reproducing_Delay",
    "NR PUSCH BLER (%) Serving Beam 2",
    "Streaming_State_Request_to_Prebuffering_Delay",
    "NR MAC DL Throughput Total (kbps)",
    "Streaming_State_Request_to_Reproducing_Delay",
    "NR MAC UL Throughput Total (kbps)",
    "StreamingStateRebufferingTime",
    "NR RLC DL Throughput Total (kbps)",
    "StreamingTimeToFirstByte",
    "NR RLC UL Throughput Total (kbps)",
    "StreamingVideoInterruptionCount",
    "NR RLC DL Throughput (Kbps)",
    "StreamingVideoIpServiceAccessTime",
    "NR RLC UL Throughput (Kbps)",
    "StreamingVideoPlayStartTime",
    "NR BWPs Configured Count DL serving Beam 1",
    "StreamingVideoSessionTime",
    "NR BWPs Configured Count DL serving Beam 2",
    "Streaming_Video_IP_Service_Access_Time_ms",
    "NR BWPs Configured Count UL Serving Beam 1",
    "Streaming_Video_IP_Service_Access_Time_sec",
    "NR BWPs Configured Count UL Serving Beam 2",
    "Streaming_Video_Play_Start_Failure_Ratio",
    "MR-DC Cell 1 SINR (dB)",
    "Streaming_Video_Play_Start_Time_sec",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1",
    "Streaming_Video_Session_Cutoff_Ratio",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
    "Streaming_Video_Session_Failure_Ratio",
    "PDSCH RB Allocation Count Serving Beam 1",
    "Streaming_Video_Session_Success_Ratio",
    "PDSCH RB Allocation Count per TB Serving Beam 1",
    "Streaming_Video_Session_Time_sec",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)",
    "Streaming_Reproduction_Cutoff_Ratio",
    "PDSCH Slot Allocation Count Serving Beam 1",
    "Streaming_Reproduction_Start_Delay_sec",
    "PDSCH Slot Allocation Count per TB Serving Beam 1",
    "Streaming_Reproduction_Start_Failure_Ratio",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
    "Streaming_Impairment_Free_Video_Session_Ratio",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)",
    "LTE Serving Cell Channel RSSI(dBm)",
    "PDSCH Slot Utilization Serving Beam 1 (%)",
    "LTE Serving Cell RSRP(dBm)",
    "PDSCH RB Dist Current Count Serving Beam 1",
    "LTE Serving Cell RS SINR(dB)",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1",
    "LTE Serving Cell RSRQ (dB)",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2",
    "LTE_Serving_Cell_Count_Average",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)",
    "PDSCH RB Allocation Count Serving Beam 2",
    "LTE Secondary Serving Cell 1 RSRP (dBm)",
    "PDSCH RB Allocation Count per TB Serving Beam 2",
    "LTE Secondary Serving Cell 1 RS SINR (dB)",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)",
    "PDSCH Slot Allocation Count Serving Beam 2",
    "LTE Neighbor Cell 1 RSRP",
    "PDSCH Slot Allocation Count per TB Serving Beam 2",
    "LTE Neighbor Cell 1 RSRQ",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)",
    "LTE MAC DL Throughput (kbps)",
    "PDSCH Slot Utilization Serving Beam 2 (%)",
    "LTE MAC DL Throughput Carrier 1 (kbps)",
    "PDSCH RB Dist Current Count Serving Beam 2",
    "LTE MAC DL Throughput Carrier 2 (kbps)",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2",
    "LTE MAC DL Throughput Carrier 3 (kbps)",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1",
    "LTE MAC DL Throughput Carrier 4 (kbps)",
    "PUSCH RB Allocation Count Serving Beam 1",
    "LTE MAC UL Throughput (kbps)",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)",
    "LTE MAC UL Throughput Carrier 1 (kbps)",
    "PUSCH Slot Allocation Count Serving Beam 1",
    "LTE MAC UL Throughput Carrier 2 (kbps)",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
    "LTE MAC UL Throughput Carrier 3 (kbps)",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)",
    "LTE MAC UL Throughput Carrier 4 (kbps)",
    "PUSCH Slot Utilization Serving Beam 1 (%)",
    "LTE PDSCH BLER (%)",
    "PUSCH RB Dist Current Count Serving Beam 1",
    "LTE PDSCH Phy Throughput (kbps)",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1",
    "LTE PDSCH Phy Throughput Total (kbps)",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "PUSCH RB Allocation Count Serving Beam 2",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Slot Allocation Count Serving Beam 2",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PUSCH BLER (%)",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)",
    "LTE PUSCH Phy Throughput (kbps)",
    "PUSCH Slot Utilization Serving Beam 2 (%)",
    "LTE PUSCH Phy Throughput Total (kbps)",
    "PUSCH RB Dist Current Count Serving Beam 2",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "Radio Common Throughput DL (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)",
]
