from typing import Any

import pandas as pd


def first_val(x: pd.Series) -> Any:
    return x.dropna().iloc[0] if not x.dropna().empty else None


def last_val(x: pd.Series) -> Any:
    return x.dropna().iloc[-1] if not x.dropna().empty else None


def modus(x: pd.Series) -> Any:
    return x.mode().iloc[0] if not x.mode().empty else None


VIDEOCHAT_AGG_RULES = {
    "Date Time": first_val,
    "Test Name": first_val,
    "Latitude": first_val,
    "Longitude": first_val,
    "Country": first_val,
    "Type Mobility": first_val,
    "DeviceDescription": first_val,
    "TWAMP Address": modus,
    "TWAMP Start Time": modus,
    "TWAMP End Time": modus,
    "IMEI": first_val,
    "IMSI": first_val,
    "MCC": first_val,
    "MNC": first_val,
    "SIM Operator": first_val,
    "Technology_Detail": modus,
    "Multi RAT Connectivity Mode": modus,
    "RadioAccessTechnologyState": modus,
    "TWAMP Start Sessions": modus,
    "TWAMP Start Sessions Acknowledgement": modus,
    "TWAMP Stop Session": modus,
    "TWAMP Operation Start": modus,
    "TWAMP Operation End": modus,
    "TWAMP Operation Attempt": modus,
    "TWAMP Operation Error": modus,
    "TWAMP Operation Success": modus,
    "TWAMP_Chunk_Interactivity_Score": "mean",
    "TWAMP_Packet_Delay_Variation_Median_ms": "mean",
    "TWAMP_Packet_Delay_Variation_Score": "mean",
    "TWAMP_Packet_Delay_Variation_Standard_Deviation": "mean",
    "TWAMP_Chunk_Jitter_Average_ms": "mean",
    "TWAMP_Chunk_Jitter_Max_ms": "max",
    "TWAMP_Chunk_Jitter_Median_ms": "median",
    "TWAMP_Chunk_Jitter_Min_ms": "min",
    "TWAMP_Chunk_Jitter_Standard_Deviation_ms": "mean",
    "TWAMP_Chunk_Jitter_Variance_ms": "mean",
    "TWAMP_Jitter_Average_ms": "mean",
    "TWAMP_Jitter_Max_ms": "max",
    "TWAMP_Jitter_Median_ms": "median",
    "TWAMP_Jitter_Min_ms": "min",
    "TWAMP_Jitter_Standard_Deviation_ms": "mean",
    "TWAMP_Jitter_Variance_ms": "mean",
    "TWAMP_Latency_Score": "mean",
    "TWAMP_Chunk_Packet_Loss": "sum",
    "TWAMP_Packet_Loss": "sum",
    "TWAMP_Packet_Loss_Score": "mean",
    "TWAMP_Overall_Session_Packet_Loss": "sum",
    "TWAMP_Chunk_Rtt_Average_ms": "mean",
    "TWAMP_Chunk_Rtt_Max_ms": "max",
    "TWAMP_Chunk_Rtt_Median_ms": "median",
    "TWAMP_Chunk_Rtt_Min_ms": "min",
    "TWAMP_Chunk_Rtt_Standard_Deviation_ms": "mean",
    "TWAMP_Chunk_Rtt_Variance_ms": "mean",
    "TWAMP_Overall_Session_Rtt_Average_ms": "mean",
    "TWAMP_Overall_Session_Rtt_Max_ms": "max",
    "TWAMP_Overall_Session_Rtt_Median_ms": "median",
    "TWAMP_Overall_Session_Rtt_Min_ms": "min",
    "TWAMP_Overall_Session_Rtt_Standard_Deviation_ms": "mean",
    "TWAMP_Overall_Session_Rtt_Variance_ms": "mean",
    "TWAMP_Rtt_Average_ms": "mean",
    "TWAMP_Rtt_Max_ms": "max",
    "TWAMP_Rtt_Median_ms": "median",
    "TWAMP_Rtt_Min_ms": "min",
    "TWAMP_Rtt_Standard_Deviation_ms": "mean",
    "TWAMP_Rtt_Variance_ms": "mean",
    "TWAMP_Interactivity_Score": "mean",
    "LTE Cell Identity(eNB Part)": modus,
    "LTE Cell Identity(Cell Part)": modus,
    "LTE Serving Cell Identity": modus,
    "LTE Serving Cell DL EARFCN": modus,
    "LTE Serving Cell Frequency Band": modus,
    "LTE Serving Cell Channel RSSI(dBm)": "mean",
    "LTE Serving Cell RSRP(dBm)": "mean",
    "LTE Serving Cell RS SINR(dB)": "mean",
    "LTE Serving Cell RSRQ (dB)": "mean",
    "LTE_Serving_Cell_Count_Average": "mean",
    "LTE Secondary Serving Cell 1 Identity": modus,
    "LTE Secondary Serving Cell 1 DL EARFCN": modus,
    "LTE Secondary Serving Cell 1 Frequency Band": modus,
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)": "mean",
    "LTE Secondary Serving Cell 1 RSRP (dBm)": "mean",
    "LTE Secondary Serving Cell 1 RS SINR (dB)": "mean",
    "LTE Secondary Serving Cell 1 RSRQ (dB)": "mean",
    "LTE Neighbor Cell 1 PCI": modus,
    "LTE Neighbor Cell 1 DL EARFCN": modus,
    "LTE Neighbor Cell 1 RSRP": "mean",
    "LTE Neighbor Cell 1 RSRQ": "mean",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)": "mean",
    "LTE MAC DL Throughput (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 1 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 2 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 3 (kbps)": "mean",
    "LTE MAC DL Throughput Carrier 4 (kbps)": "mean",
    "LTE MAC UL Throughput (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 1 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 2 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 3 (kbps)": "mean",
    "LTE MAC UL Throughput Carrier 4 (kbps)": "mean",
    "LTE PDSCH Modulation": modus,
    "LTE PDSCH MCS": modus,
    "LTE PDSCH BLER (%)": "mean",
    "LTE PDSCH Phy Throughput (kbps)": "mean",
    "LTE PDSCH Phy Throughput Total (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)": "mean",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)": "mean",
    "LTE PUSCH Modulation ": modus,
    "LTE PUSCH MCS ": modus,
    "PUSCH BLER (%)": "mean",
    "LTE PUSCH Phy Throughput (kbps)": "mean",
    "LTE PUSCH Phy Throughput Total (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)": "mean",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)": "mean",
    "PUSCH Phy Throughput Carrier 4 (kbps)": "mean",
    "LTE RLC Throughput DL (Kbps)": "mean",
    "LTE RLC Throughput UL (Kbps)": "mean",
    "LTE Bearer Maximum Bitrate DL (kbit/s)": "mean",
    "LTE PDN Connection AMBR DL (kbps)": "mean",
    "NR Serving Beam 1 Cell Identity": modus,
    "NR Serving Beam 1 NRARFCN DL": "mean",
    "NR Serving Beam 1 Band": modus,
    "NR Serving Beam 1 Bandwidth DL": "mean",
    "NR Serving Beam 1 Bandwidth UL": "mean",
    "NR Serving Beam 1 SSB Index": modus,
    "NR Serving Beam 1 Cell Type": modus,
    "NR Serving Beam 1 GSCN": "mean",
    "NR Serving Beam 2 Cell Identity": modus,
    "NR Serving Beam 2 NRARFCN DL": "mean",
    "NR Serving Beam 2 Band": modus,
    "NR Serving Beam 2 Bandwidth DL": "mean",
    "NR Serving Beam 2 Bandwidth UL": "mean",
    "NR Serving Beam 2 SSB Index": modus,
    "NR Serving Beam 2 Cell Type": modus,
    "NR Serving Beam 2 GSCN": "mean",
    "NR Serving Cell Identity Top #1": modus,
    "NR Serving Cell NRARFCN DL Top #1": modus,
    "NR Serving Cell SS RSSI Top #1": "mean",
    "NR Serving Cell SS RSRP Top #1": "mean",
    "NR Serving Cell SS SINR Top #1": "mean",
    "NR Serving Cell SS RSRQ Top #1": "mean",
    "NR PCell SSB Serving Beam Index Top #1": modus,
    "NR Neighbor Cell 1 Cell Identity": modus,
    "NR Neighbor Cell 1 NRARFCN": modus,
    "NR Neighbor Cell 1 SS RSRP (dBm)": "mean",
    "NR Neighbor Cell 1 SS SINR (dB)": "mean",
    "NR Neighbor Cell 1 SS RSRQ (dB)": "mean",
    "NR Neighbor Cell 1 Best Beam Index": modus,
    "NR Neighbor Cell 1 Cell Type": modus,
    "NR Phy Throughput Multi-RAT DL (kbps)": "mean",
    "NR Phy Throughput Multi-RAT UL (kbps)": "mean",
    "NR PDSCH Phy Throughput Total (Kbps)": "mean",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)": "mean",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)": "mean",
    "NR PDSCH Modulation Serving Beam 1": modus,
    "NR PDSCH MCS Serving Beam 1": modus,
    "NR PDSCH BLER (%) Serving Beam 1": "mean",
    "NR PDSCH CQI Serving Beam 1": "mean",
    "NR PDSCH RI Serving Beam 1": "mean",
    "NR DL Pathloss Serving Beam 1": "mean",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)": "mean",
    "NR PDSCH Modulation Serving Beam 2": modus,
    "NR PDSCH MCS Serving Beam 2": modus,
    "NR PDSCH BLER (%) Serving Beam 2": "mean",
    "NR PDSCH CQI Serving Beam 2": "mean",
    "NR PDSCH RI Serving Beam 2": "mean",
    "NR DL Pathloss Serving Beam 2": "mean",
    "NR PUSCH Phy Throughput Total (kbps)": "mean",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)": "mean",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)": "mean",
    "NR PUSCH Modulation Serving Beam 1": modus,
    "NR PUSCH MCS Serving Beam 1": modus,
    "NR PUSCH BLER (%) Serving Beam 1": "mean",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)": "mean",
    "NR PUSCH Modulation Serving Beam 2": modus,
    "NR PUSCH MCS Serving Beam 2": modus,
    "NR PUSCH BLER (%) Serving Beam 2": "mean",
    "NR MAC DL Throughput Total (kbps)": "sum",
    "NR MAC UL Throughput Total (kbps)": "sum",
    "NR RLC DL Throughput Total (kbps)": "sum",
    "NR RLC UL Throughput Total (kbps)": "sum",
    "NR RLC DL Throughput (Kbps)": "sum",
    "NR RLC UL Throughput (Kbps)": "sum",
    "NR BWP Center NR-ARFCN DL Serving Beam 1": modus,
    "NR BWP Bandwidth DL (Mhz) Serving Beam 1": modus,
    "NR BWP ID DL Serving Beam 1": modus,
    "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)": modus,
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1": modus,
    "NR BWP Start Point NR-ARFCN DL Serving Beam 1": modus,
    "NR BWP Subcarrier Spacing DL Serving Beam 1": modus,
    "NR BWPs Configured Count DL serving Beam 1": "max",
    "NR BWP Center NR-ARFCN DL Serving Beam 2": modus,
    "NR BWP Bandwidth DL (Mhz) Serving Beam 2": modus,
    "NR BWP ID DL Serving Beam 2": modus,
    "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)": modus,
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2": modus,
    "NR BWP Start Point NR-ARFCN DL Serving Beam 2": modus,
    "NR BWP Subcarrier Spacing DL Serving Beam 2": modus,
    "NR BWPs Configured Count DL serving Beam 2": "max",
    "NR BWP Center NR-ARFCN UL Serving Beam 1": modus,
    "NR BWP Bandwidth UL Serving Beam 1 (Mhz)": modus,
    "NR BWP ID UL Serving Beam 1": modus,
    "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)": modus,
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1": modus,
    "NR BWP Start Point NR-ARFCN UL Serving Beam 1": modus,
    "NR BWP Subcarrier Spacing UL Serving Beam 1": modus,
    "NR BWPs Configured Count UL Serving Beam 1": "max",
    "NR BWP Center NR-ARFCN UL Serving Beam 2": modus,
    "NR BWP Bandwidth UL Serving Beam 2 (Mhz)": modus,
    "NR BWP ID UL Serving Beam 2": modus,
    "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)": modus,
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2": modus,
    "NR BWP Start Point NR-ARFCN UL Serving Beam 2": modus,
    "NR BWP Subcarrier Spacing UL Serving Beam 2": modus,
    "NR BWPs Configured Count UL Serving Beam 2": "max",
    "RadioAccessTechnologyState": modus,
    "MR-DC Cell 1 SINR (dB)": "mean",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1": "mean",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1": "mean",
    "PDSCH BWP ID Serving Beam 1": modus,
    "PDSCH RB Allocation Count Serving Beam 1": "sum",
    "PDSCH RB Allocation Count per TB Serving Beam 1": "sum",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)": "mean",
    "PDSCH RBG Size Serving Beam 1": modus,
    "PDSCH Slot Allocation Count Serving Beam 1": "sum",
    "PDSCH Slot Allocation Count per TB Serving Beam 1": "sum",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)": "mean",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)": "mean",
    "PDSCH Slot Utilization Serving Beam 1 (%)": "mean",
    "PDSCH RB Dist Current Count Serving Beam 1": "sum",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1": "sum",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2": "mean",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2": "mean",
    "PDSCH BWP ID Serving Beam 2": modus,
    "PDSCH RB Allocation Count Serving Beam 2": "sum",
    "PDSCH RB Allocation Count per TB Serving Beam 2": "sum",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)": "mean",
    "PDSCH RBG Size Serving Beam 2": modus,
    "PDSCH Slot Allocation Count Serving Beam 2": "sum",
    "PDSCH Slot Allocation Count per TB Serving Beam 2": "sum",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)": "mean",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)": "mean",
    "PDSCH Slot Utilization Serving Beam 2 (%)": "mean",
    "PDSCH RB Dist Current Count Serving Beam 2": "sum",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2": "sum",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1": "mean",
    "PUSCH BWP ID Serving Beam 1": modus,
    "PUSCH RB Allocation Count Serving Beam 1": "sum",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)": "mean",
    "PUSCH RBG Size Serving Beam 1": modus,
    "PUSCH Slot Allocation Count Serving Beam 1": "sum",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)": "mean",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)": "mean",
    "PUSCH Slot Utilization Serving Beam 1 (%)": "mean",
    "PUSCH RB Dist Current Count Serving Beam 1": "sum",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1": "sum",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2": "mean",
    "PUSCH BWP ID Serving Beam 2": modus,
    "PUSCH RB Allocation Count Serving Beam 2": "sum",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)": "mean",
    "PUSCH RBG Size Serving Beam 2": modus,
    "PUSCH Slot Allocation Count Serving Beam 2": "sum",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)": "mean",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)": "mean",
    "PUSCH Slot Utilization Serving Beam 2 (%)": "mean",
    "PUSCH RB Dist Current Count Serving Beam 2": "sum",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2": "sum",
    "Radio Common Throughput DL (kbps)": "mean",
    "FirmwareVersion": modus,
}

VIDEOCHAT_DESIRED_ORDER = [
    "Date Time",
    "Test Id",
    "TWAMP Address",
    "TWAMP Start Time",
    "TWAMP End Time",
    "Test Name",
    "Type Mobility",
    "DeviceDescription",
    "Operator",
    "Country",
    "Sequence",
    "Latitude",
    "end_latitude",
    "Longitude",
    "end_longitude",
    "Logfile Name",
    "EventName",
    "IMEI",
    "IMSI",
    "MCC",
    "MNC",
    "SIM Operator",
    "Technology_Detail",
    "Multi RAT Connectivity Mode",
    "RadioAccessTechnologyState",
    "TWAMP Start Sessions",
    "TWAMP Start Sessions Acknowledgement",
    "TWAMP Stop Session",
    "TWAMP Operation Start",
    "TWAMP Operation End",
    "TWAMP Operation Attempt",
    "TWAMP Operation Error",
    "TWAMP Operation Success",
    "TWAMP_Chunk_Interactivity_Score",
    "TWAMP_Packet_Delay_Variation_Median_ms",
    "TWAMP_Packet_Delay_Variation_Standard_Deviation",
    "TWAMP_Chunk_Jitter_Average_ms",
    "TWAMP_Chunk_Jitter_Max_ms",
    "TWAMP_Chunk_Jitter_Median_ms",
    "TWAMP_Chunk_Jitter_Min_ms",
    "TWAMP_Chunk_Jitter_Standard_Deviation_ms",
    "TWAMP_Chunk_Jitter_Variance_ms",
    "TWAMP_Jitter_Average_ms",
    "TWAMP_Jitter_Max_ms",
    "TWAMP_Jitter_Median_ms",
    "TWAMP_Jitter_Min_ms",
    "TWAMP_Jitter_Standard_Deviation_ms",
    "TWAMP_Jitter_Variance_ms",
    "TWAMP_Latency_Score",
    "TWAMP_Chunk_Packet_Loss",
    "TWAMP_Packet_Loss",
    "TWAMP_Packet_Loss_Score",
    "TWAMP_Overall_Session_Packet_Loss",
    "TWAMP_Chunk_Rtt_Average_ms",
    "TWAMP_Chunk_Rtt_Max_ms",
    "TWAMP_Chunk_Rtt_Median_ms",
    "TWAMP_Chunk_Rtt_Min_ms",
    "TWAMP_Chunk_Rtt_Standard_Deviation_ms",
    "TWAMP_Chunk_Rtt_Variance_ms",
    "TWAMP_Overall_Session_Rtt_Average_ms",
    "TWAMP_Overall_Session_Rtt_Max_ms",
    "TWAMP_Overall_Session_Rtt_Median_ms",
    "TWAMP_Overall_Session_Rtt_Min_ms",
    "TWAMP_Overall_Session_Rtt_Standard_Deviation_ms",
    "TWAMP_Overall_Session_Rtt_Variance_ms",
    "TWAMP_Rtt_Average_ms",
    "TWAMP_Rtt_Max_ms",
    "TWAMP_Rtt_Median_ms",
    "TWAMP_Rtt_Min_ms",
    "TWAMP_Rtt_Standard_Deviation_ms",
    "TWAMP_Rtt_Variance_ms",
    "TWAMP_Interactivity_Score",
    "TWAMP_Packet_Delay_Variation_Score",
    "LTE Cell Identity(eNB Part)",
    "LTE Cell Identity(Cell Part)",
    "LTE Serving Cell Identity",
    "LTE Serving Cell DL EARFCN",
    "LTE Serving Cell Frequency Band",
    "LTE Serving Cell Channel RSSI(dBm)",
    "LTE Serving Cell RSRP(dBm)",
    "LTE Serving Cell RS SINR(dB)",
    "LTE Serving Cell RSRQ (dB)",
    "LTE_Serving_Cell_Count_Average",
    "LTE Secondary Serving Cell 1 Identity",
    "LTE Secondary Serving Cell 1 DL EARFCN",
    "LTE Secondary Serving Cell 1 Frequency Band",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)",
    "LTE Secondary Serving Cell 1 RSRP (dBm)",
    "LTE Secondary Serving Cell 1 RS SINR (dB)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)",
    "LTE Neighbor Cell 1 PCI",
    "LTE Neighbor Cell 1 DL EARFCN",
    "LTE Neighbor Cell 1 RSRP",
    "LTE Neighbor Cell 1 RSRQ",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "LTE MAC DL Throughput (kbps)",
    "LTE MAC DL Throughput Carrier 1 (kbps)",
    "LTE MAC DL Throughput Carrier 2 (kbps)",
    "LTE MAC DL Throughput Carrier 3 (kbps)",
    "LTE MAC DL Throughput Carrier 4 (kbps)",
    "LTE MAC UL Throughput (kbps)",
    "LTE MAC UL Throughput Carrier 1 (kbps)",
    "LTE MAC UL Throughput Carrier 2 (kbps)",
    "LTE MAC UL Throughput Carrier 3 (kbps)",
    "LTE MAC UL Throughput Carrier 4 (kbps)",
    "LTE PDSCH Modulation",
    "LTE PDSCH MCS",
    "LTE PDSCH BLER (%)",
    "LTE PDSCH Phy Throughput (kbps)",
    "LTE PDSCH Phy Throughput Total (kbps)",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
    "LTE PUSCH Modulation ",
    "LTE PUSCH MCS ",
    "PUSCH BLER (%)",
    "LTE PUSCH Phy Throughput (kbps)",
    "LTE PUSCH Phy Throughput Total (kbps)",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Phy Throughput Carrier 4 (kbps)",
    "LTE RLC Throughput DL (Kbps)",
    "LTE RLC Throughput UL (Kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)",
    "NR Serving Beam 1 Cell Identity",
    "NR Serving Beam 1 NRARFCN DL",
    "NR Serving Beam 1 Band",
    "NR Serving Beam 1 Bandwidth DL",
    "NR Serving Beam 1 Bandwidth UL",
    "NR Serving Beam 1 SSB Index",
    "NR Serving Beam 1 Cell Type",
    "NR Serving Beam 1 GSCN",
    "NR Serving Beam 2 Cell Identity",
    "NR Serving Beam 2 NRARFCN DL",
    "NR Serving Beam 2 Band",
    "NR Serving Beam 2 Bandwidth DL",
    "NR Serving Beam 2 Bandwidth UL",
    "NR Serving Beam 2 SSB Index",
    "NR Serving Beam 2 Cell Type",
    "NR Serving Beam 2 GSCN",
    "NR Serving Cell Identity Top #1",
    "NR Serving Cell NRARFCN DL Top #1",
    "NR Serving Cell SS RSSI Top #1",
    "NR Serving Cell SS RSRP Top #1",
    "NR Serving Cell SS SINR Top #1",
    "NR Serving Cell SS RSRQ Top #1",
    "NR PCell SSB Serving Beam Index Top #1",
    "NR Neighbor Cell 1 Cell Identity",
    "NR Neighbor Cell 1 NRARFCN",
    "NR Neighbor Cell 1 SS RSRP (dBm)",
    "NR Neighbor Cell 1 SS SINR (dB)",
    "NR Neighbor Cell 1 SS RSRQ (dB)",
    "NR Neighbor Cell 1 Best Beam Index",
    "NR Neighbor Cell 1 Cell Type",
    "NR Phy Throughput Multi-RAT DL (kbps)",
    "NR Phy Throughput Multi-RAT UL (kbps)",
    "NR PDSCH Phy Throughput Total (Kbps)",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PDSCH Modulation Serving Beam 1",
    "NR PDSCH MCS Serving Beam 1",
    "NR PDSCH BLER (%) Serving Beam 1",
    "NR PDSCH CQI Serving Beam 1",
    "NR PDSCH RI Serving Beam 1",
    "NR DL Pathloss Serving Beam 1",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PDSCH Modulation Serving Beam 2",
    "NR PDSCH MCS Serving Beam 2",
    "NR PDSCH BLER (%) Serving Beam 2",
    "NR PDSCH CQI Serving Beam 2",
    "NR PDSCH RI Serving Beam 2",
    "NR DL Pathloss Serving Beam 2",
    "NR PUSCH Phy Throughput Total (kbps)",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PUSCH Modulation Serving Beam 1",
    "NR PUSCH MCS Serving Beam 1",
    "NR PUSCH BLER (%) Serving Beam 1",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PUSCH Modulation Serving Beam 2",
    "NR PUSCH MCS Serving Beam 2",
    "NR PUSCH BLER (%) Serving Beam 2",
    "NR MAC DL Throughput Total (kbps)",
    "NR MAC UL Throughput Total (kbps)",
    "NR RLC DL Throughput Total (kbps)",
    "NR RLC UL Throughput Total (kbps)",
    "NR RLC DL Throughput (Kbps)",
    "NR RLC UL Throughput (Kbps)",
    "NR BWP Center NR-ARFCN DL Serving Beam 1",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
    "NR BWP ID DL Serving Beam 1",
    "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Subcarrier Spacing DL Serving Beam 1",
    "NR BWPs Configured Count DL serving Beam 1",
    "NR BWP Center NR-ARFCN DL Serving Beam 2",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
    "NR BWP ID DL Serving Beam 2",
    "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Subcarrier Spacing DL Serving Beam 2",
    "NR BWPs Configured Count DL serving Beam 2",
    "NR BWP Center NR-ARFCN UL Serving Beam 1",
    "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
    "NR BWP ID UL Serving Beam 1",
    "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Subcarrier Spacing UL Serving Beam 1",
    "NR BWPs Configured Count UL Serving Beam 1",
    "NR BWP Center NR-ARFCN UL Serving Beam 2",
    "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
    "NR BWP ID UL Serving Beam 2",
    "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Subcarrier Spacing UL Serving Beam 2",
    "NR BWPs Configured Count UL Serving Beam 2",
    "RadioAccessTechnologyState",
    "MR-DC Cell 1 SINR (dB)",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
    "PDSCH BWP ID Serving Beam 1",
    "PDSCH RB Allocation Count Serving Beam 1",
    "PDSCH RB Allocation Count per TB Serving Beam 1",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)",
    "PDSCH RBG Size Serving Beam 1",
    "PDSCH Slot Allocation Count Serving Beam 1",
    "PDSCH Slot Allocation Count per TB Serving Beam 1",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)",
    "PDSCH Slot Utilization Serving Beam 1 (%)",
    "PDSCH RB Dist Current Count Serving Beam 1",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
    "PDSCH BWP ID Serving Beam 2",
    "PDSCH RB Allocation Count Serving Beam 2",
    "PDSCH RB Allocation Count per TB Serving Beam 2",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)",
    "PDSCH RBG Size Serving Beam 2",
    "PDSCH Slot Allocation Count Serving Beam 2",
    "PDSCH Slot Allocation Count per TB Serving Beam 2",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)",
    "PDSCH Slot Utilization Serving Beam 2 (%)",
    "PDSCH RB Dist Current Count Serving Beam 2",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1",
    "PUSCH BWP ID Serving Beam 1",
    "PUSCH RB Allocation Count Serving Beam 1",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)",
    "PUSCH RBG Size Serving Beam 1",
    "PUSCH Slot Allocation Count Serving Beam 1",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)",
    "PUSCH Slot Utilization Serving Beam 1 (%)",
    "PUSCH RB Dist Current Count Serving Beam 1",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2",
    "PUSCH BWP ID Serving Beam 2",
    "PUSCH RB Allocation Count Serving Beam 2",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)",
    "PUSCH RBG Size Serving Beam 2",
    "PUSCH Slot Allocation Count Serving Beam 2",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)",
    "PUSCH Slot Utilization Serving Beam 2 (%)",
    "PUSCH RB Dist Current Count Serving Beam 2",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2",
    "Radio Common Throughput DL (kbps)",
    "FirmwareVersion",
]

VIDEOCHAT_MEAN_COLS = [
    "TWAMP_Chunk_Interactivity_Score",
    "TWAMP_Interactivity_Score",
    "TWAMP_Packet_Delay_Variation_Median_ms",
    "TWAMP_Packet_Delay_Variation_Standard_Deviation",
    "TWAMP_Jitter_Median_ms",
    "TWAMP_Jitter_Variance_msTWAMP_Chunk_Interactivity_Score",
    "TWAMP_Packet_Delay_Variation_Median_ms",
    "TWAMP_Packet_Delay_Variation_Score",
    "TWAMP_Chunk_Jitter_Average_ms",
    "TWAMP_Chunk_Jitter_Max_ms",
    "TWAMP_Chunk_Jitter_Median_ms",
    "TWAMP_Chunk_Jitter_Min_ms",
    "TWAMP_Chunk_Jitter_Standard_Deviation_ms",
    "TWAMP_Chunk_Jitter_Variance_ms",
    "TWAMP_Jitter_Average_ms",
    "TWAMP_Jitter_Max_ms",
    "TWAMP_Jitter_Median_ms",
    "TWAMP_Jitter_Min_ms",
    "TWAMP_Jitter_Standard_Deviation_ms",
    "TWAMP_Jitter_Variance_ms",
    "TWAMP_Latency_Score",
    "TWAMP_Chunk_Packet_Loss",
    "TWAMP_Packet_Loss",
    "TWAMP_Packet_Loss_Score",
    "TWAMP_Overall_Session_Packet_Loss",
    "TWAMP_Chunk_Rtt_Average_ms",
    "TWAMP_Chunk_Rtt_Max_ms",
    "TWAMP_Chunk_Rtt_Median_ms",
    "TWAMP_Chunk_Rtt_Min_ms",
    "TWAMP_Chunk_Rtt_Standard_Deviation_ms",
    "TWAMP_Chunk_Rtt_Variance_ms",
    "TWAMP_Overall_Session_Rtt_Average_ms",
    "TWAMP_Overall_Session_Rtt_Max_ms",
    "TWAMP_Overall_Session_Rtt_Median_ms",
    "TWAMP_Overall_Session_Rtt_Min_ms",
    "TWAMP_Overall_Session_Rtt_Standard_Deviation_ms",
    "TWAMP_Overall_Session_Rtt_Variance_ms",
    "TWAMP_Rtt_Average_ms",
    "TWAMP_Rtt_Max_ms",
    "TWAMP_Rtt_Median_ms",
    "TWAMP_Rtt_Min_ms",
    "TWAMP_Rtt_Standard_Deviation_ms",
    "TWAMP_Rtt_Variance_ms",
    "LTE Serving Cell Channel RSSI(dBm)",
    "LTE Serving Cell RSRP(dBm)",
    "LTE Serving Cell RS SINR(dB)",
    "LTE Serving Cell RSRQ (dB)",
    "LTE_Serving_Cell_Count_Average",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)",
    "LTE Secondary Serving Cell 1 RSRP (dBm)",
    "LTE Secondary Serving Cell 1 RS SINR (dB)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)",
    "LTE Neighbor Cell 1 RSRP",
    "LTE Neighbor Cell 1 RSRQ",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "LTE MAC DL Throughput (kbps)",
    "LTE MAC DL Throughput Carrier 1 (kbps)",
    "LTE MAC DL Throughput Carrier 2 (kbps)",
    "LTE MAC DL Throughput Carrier 3 (kbps)",
    "LTE MAC DL Throughput Carrier 4 (kbps)",
    "LTE MAC UL Throughput (kbps)",
    "LTE MAC UL Throughput Carrier 1 (kbps)",
    "LTE MAC UL Throughput Carrier 2 (kbps)",
    "LTE MAC UL Throughput Carrier 3 (kbps)",
    "LTE MAC UL Throughput Carrier 4 (kbps)",
    "LTE PDSCH BLER (%)",
    "LTE PDSCH Phy Throughput (kbps)",
    "LTE PDSCH Phy Throughput Total (kbps)",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
    "PUSCH BLER (%)",
    "LTE PUSCH Phy Throughput (kbps)",
    "LTE PUSCH Phy Throughput Total (kbps)",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Phy Throughput Carrier 4 (kbps)",
    "LTE RLC Throughput DL (Kbps)",
    "LTE RLC Throughput UL (Kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)",
    "NR Serving Beam 1 NRARFCN DL",
    "NR Serving Beam 1 Bandwidth DL",
    "NR Serving Beam 1 Bandwidth UL",
    "NR Serving Beam 1 GSCN",
    "NR Serving Beam 2 NRARFCN DL",
    "NR Serving Beam 2 Bandwidth DL",
    "NR Serving Beam 2 Bandwidth UL",
    "NR Serving Beam 2 GSCN",
    "NR Serving Cell SS RSSI Top #1",
    "NR Serving Cell SS RSRP Top #1",
    "NR Serving Cell SS SINR Top #1",
    "NR Serving Cell SS RSRQ Top #1",
    "NR Neighbor Cell 1 SS RSRP (dBm)",
    "NR Neighbor Cell 1 SS SINR (dB)",
    "NR Neighbor Cell 1 SS RSRQ (dB)",
    "NR Phy Throughput Multi-RAT DL (kbps)",
    "NR Phy Throughput Multi-RAT UL (kbps)",
    "NR PDSCH Phy Throughput Total (Kbps)",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PDSCH BLER (%) Serving Beam 1",
    "NR PDSCH CQI Serving Beam 1",
    "NR PDSCH RI Serving Beam 1",
    "NR DL Pathloss Serving Beam 1",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PDSCH BLER (%) Serving Beam 2",
    "NR PDSCH CQI Serving Beam 2",
    "NR PDSCH RI Serving Beam 2",
    "NR DL Pathloss Serving Beam 2",
    "NR PUSCH Phy Throughput Total (kbps)",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PUSCH BLER (%) Serving Beam 1",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PUSCH BLER (%) Serving Beam 2",
    "NR MAC DL Throughput Total (kbps)",
    "NR MAC UL Throughput Total (kbps)",
    "NR RLC DL Throughput Total (kbps)",
    "NR RLC UL Throughput Total (kbps)",
    "NR RLC DL Throughput (Kbps)",
    "NR RLC UL Throughput (Kbps)",
    "NR BWPs Configured Count DL serving Beam 1",
    "NR BWPs Configured Count DL serving Beam 2",
    "NR BWPs Configured Count UL Serving Beam 1",
    "NR BWPs Configured Count UL Serving Beam 2",
    "MR-DC Cell 1 SINR (dB)",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
    "PDSCH RB Allocation Count Serving Beam 1",
    "PDSCH RB Allocation Count per TB Serving Beam 1",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)",
    "PDSCH Slot Allocation Count Serving Beam 1",
    "PDSCH Slot Allocation Count per TB Serving Beam 1",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)",
    "PDSCH Slot Utilization Serving Beam 1 (%)",
    "PDSCH RB Dist Current Count Serving Beam 1",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
    "PDSCH RB Allocation Count Serving Beam 2",
    "PDSCH RB Allocation Count per TB Serving Beam 2",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)",
    "PDSCH Slot Allocation Count Serving Beam 2",
    "PDSCH Slot Allocation Count per TB Serving Beam 2",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)",
    "PDSCH Slot Utilization Serving Beam 2 (%)",
    "PDSCH RB Dist Current Count Serving Beam 2",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1",
    "PUSCH RB Allocation Count Serving Beam 1",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)",
    "PUSCH Slot Allocation Count Serving Beam 1",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)",
    "PUSCH Slot Utilization Serving Beam 1 (%)",
    "PUSCH RB Dist Current Count Serving Beam 1",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2",
    "PUSCH RB Allocation Count Serving Beam 2",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)",
    "PUSCH Slot Allocation Count Serving Beam 2",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)",
    "PUSCH Slot Utilization Serving Beam 2 (%)",
    "PUSCH RB Dist Current Count Serving Beam 2",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2",
    "TWAMP_Interactivity_Score",
    "Radio Common Throughput DL (kbps)",
]
