import pandas as pd
from pathlib import Path
from datetime import datetime


# === Load Excel ===
input_folder = Path("/mnt/c/Users/User/Documents/Indra/geo/CDR/parsing/split/Streaming/Input")
all_files = list(input_folder.glob("*.xlsx"))

df_list = []

for file_path in all_files:
    xls = pd.ExcelFile(file_path)
    df_sheet = xls.parse(xls.sheet_names[0])
    df_sheet["SourceFile"] = file_path.stem  # Optional: keep track of where each row came from
    df_list.append(df_sheet)

# Combine all into one DataFrame
df = pd.concat(df_list, ignore_index=True)

date_split = df['Date Time'].astype(str).str.split(' ', expand=True)
date_split.columns = ['Date', 'Time']
df = pd.concat([df.drop(columns=['Date Time']), date_split], axis=1)

df = pd.concat([
    df,
    df[["StreamingServiceBearer"]].rename(columns={"StreamingServiceBearer": "Streaming Service Bearer"})
], axis=1)


# === Step 2: Rename columns globally
master_rename_map = {
    "Date Time": "Date",
    "Time": "Time",
    "Test Name": "Test Name",
    "Type Mobility": "Type of Mobility",
    "Operator": "Operator",
    "Country": "Route Name",
    "Sequence": "Sequence",
    "MNC": "MNC",
    "Technology_Detail": "Session Start Technology",
    "StreamingDevice": "Streaming Device",
    "StreamingOperator": "Streaming Operator",
    "StreamingImsi": "IMSI",
    "TAC": "Session Start TAC",
    "StreamingStartLongitude": "Longitude",
    "StreamingStartLatitude": "Latitude",
    "StreamingEndLongitude": "Session End Longitude",
    "StreamingEndLatitude": "Session End Latitude",
    "StreamingStartRat": "Streaming Start RAT",
    "StreamingEndRat": "Streaming End RAT",
    "Play Request to 1st Picture": "Play Request to 1st Picture",
    "StreamingStartMultiRATConnectivityMode": "Session Start MultiRAT",
    "StreamingEndMultiRATConnectivityMode": "Session End MultiRAT",
    "StreamingStartTime": "Session Start Time",
    "StreamingEndTime": "Session End Time",
    "StreamingLogfileName": "Logfile Name",
    "Streaming_URL": "Streaming URL",
    "Streaming_Outcome_Type": "Streaming Outcome Type",
    "Aborted_by_User": "Aborted by User Status",
    "Streaming_Completion_Rate": "Streaming Completion Rate",
    "Streaming_Setup_Success_Rate": "Streaming Setup Success Rate",
    "Streaming_Success_Rate": "Streaming Success Rate",
    "StreamingDataRadioBearer": "Streaming Data Radio Bearer",
    "StreamingServiceBearer": "Session Start Data Radio Bearer",
    "StreamingSessionIdentity": "Streaming Session Identity",
    "StreamingSessionTime": "Streaming Session Time",
    "Streaming_Session_Failure_Ratio": "Streaming Session Failure Ratio",
    "Streaming_Number_Of_Video_Session_Interruptions": "Streaming Number Of Video Session Interruptions",
    "Streaming_Total_Duration_Of_Video_Session_Interruptions": "Streaming Total Duration Of Video Session Interruptions",
    "Streaming_Maximum_Duration_Of_Video_Session_Interruptions": "Streaming Maximum Duration Of Video Session Interruptions",
    "Streaming_Session_Without_Interruption_Rate": "Streaming Session Without Interruption Rate",
    "Streaming_Duration": "Streaming Duration",
    "Seconds_Start_to_End_Streaming": "Seconds Start to End Streaming",
    "Streaming_HD_Resolution": "Streaming HD Resolution",
    "Streaming_HD_Resolution_Ratio": "Streaming HD Resolution Ratio",
    "Streaming_Average_Session_Resolution": "Streaming Average Session Resolution",
    "Streaming_Average_Throughput": "Streaming Average Throughput",
    "StreamingThroughputAvg": "Streaming Throughput Avg",
    "Streaming_Throughput_Filtered": "Streaming Throughput Filtered",
    "StreamingPlayerDownloadDataTransferTime": "Streaming Player Download Data Transfer Time",
    "StreamingPlayerIpServiceAccessTime": "Streaming Player IP Service Access Time",
    "StreamingPlayerSessionTime": "Streaming Player Session Time",
    "StreamingProbeName": "Streaming Probe Name",
    "StreamingProbeVersion": "Streaming Probe Version",
    "StreamingReproductionStartDelay": "Streaming Reproduction Start Delay",
    "StreamingResolutionAvg": "Streaming ResolutionAvg",
    "StreamingServiceStatus": "Streaming ServiceStatus",
    "StreamingServiceAccessTime": "Streaming ServiceAccessTime",
    "Streaming_Service_Access_Time_ms": "Streaming Service Access Time (ms)",
    "Streaming_Service_Access_Time_sec": "Streaming Service Access Time (sec)",
    "Streaming_Service_Non_Accessibility": "Streaming Service Non Accessibility",
    "StreamingInterruptionDurationTotal": "Streaming Interruption Duration Total",
    "StreamingInterruptionDurationMax": "Streaming Interruption Duration Max",
    "Streaming_State_Event_Source_Time": "Streaming State Event Source Time",
    "Streaming_State_Prebuffering_to_Reproducing_Delay": "Streaming State Prebuffering to Reproducing Delay",
    "Streaming_State_Request_to_Prebuffering_Delay": "Streaming State Request to Prebuffering Delay",
    "Streaming_State_Request_to_Reproducing_Delay": "Streaming State Request to Reproducing Delay",
    "StreamingStateBufferingCompleteTime": "Streaming State Buffering Complete Time",
    "StreamingStateDoneTime": "Streaming State Done Time",
    "StreamingStatePlayerDownloadEndTime": "Streaming State Player Download End Time",
    "StreamingStatePlayerDownloadStartTime": "Streaming State Player Download Start Time",
    "StreamingStatePlayerRequestTime": "Streaming State Player Request Time",
    "StreamingStatePrebufferingTime": "Streaming State Prebuffering Time",
    "StreamingStateRebufferingTime": "Streaming State Rebuffering Time",
    "StreamingStateReproducingTime": "Streaming State Reproducing Time",
    "StreamingStateVideoRequestTime": "Streaming State Video Request Time",
    "StreamingTimeToFirstByte": "Streaming Time To First Byte (TTFB)",
    "StreamingVideoInterruptionCount": "Streaming Video Interruption Count",
    "StreamingVideoIpServiceAccessTime": "Streaming Video IP Service Access Time",
    "StreamingVideoPlayStartTime": "Streaming Video Play Start Time",
    "StreamingVideoSessionTime": "Streaming Video Session Time",
    "Streaming_Video_IP_Service_Access_Time_ms": "Streaming Video IP Service Access Time (ms)",
    "Streaming_Video_IP_Service_Access_Time_sec": "Streaming Video IP Service Access Time (sec)",
    "Streaming_Video_Play_Start_Failure_Ratio": "Streaming Video Play Start Failure Ratio",
    "Streaming_Video_Play_Start_Time_sec": "Streaming Video Play Start Time (sec)",
    "Streaming_Video_Session_Cutoff_Ratio": "Streaming Video Session Cutoff Ratio",
    "Streaming_Video_Session_Failure_Ratio": "Streaming Video Session Failure Ratio",
    "Streaming_Video_Session_Success_Ratio": "Streaming Video Session Success Ratio",
    "Streaming_Video_Session_Time_sec": "Streaming Video Session Time (sec)",
    "Streaming_Reproduction_Cutoff_Ratio": "Streaming Reproduction Cutoff Ratio",
    "Streaming_Reproduction_Start_Delay_sec": "Streaming Reproduction Start Delay (sec)",
    "Streaming_Reproduction_Start_Failure_Ratio": "Streaming Reproduction Start Failure Ratio",
    "Streaming_Impairment_Free": "Streaming Impairment Free",
    "Streaming_Impairment_Free_Video_Session_Ratio": "Streaming Impairment Free Video Session Ratio",
    "LTE Cell Identity(eNB Part)": "LTE Cell Identity(eNB Part)",
    "LTE Cell Identity(Cell Part)": "LTE Cell Identity(Cell Part)",
    "LTE Serving Cell Identity": "LTE Serving Cell Identity",
    "LTE Serving Cell DL EARFCN": "LTE Serving Cell DL EARFCN",
    "LTE Serving Cell Frequency Band": "LTE Serving Cell Frequency Band",
    "LTE Serving Cell Channel RSSI(dBm)": "LTE Serving Cell Channel RSSI(dBm)",
    "LTE Serving Cell RSRP(dBm)": "LTE Serving Cell RSRP(dBm)",
    "LTE Serving Cell RS SINR(dB)": "LTE Serving Cell RS SINR(dB)",
    "LTE Serving Cell RSRQ (dB)": "LTE Serving Cell RSRQ (dB)",
    "LTE_Serving_Cell_Count_Average": "LTE_Serving_Cell_Count_Average",
    "LTE Secondary Serving Cell 1 Identity": "LTE (sec)ondary Serving Cell 1 Identity",
    "LTE Secondary Serving Cell 1 DL EARFCN": "LTE (sec)ondary Serving Cell 1 DL EARFCN",
    "LTE Secondary Serving Cell 1 Frequency Band": "LTE (sec)ondary Serving Cell 1 Frequency Band",
    "LTE Secondary Serving Cell 1 Channel RSSI (dBm)": "LTE (sec)ondary Serving Cell 1 Channel RSSI (dBm)",
    "LTE Secondary Serving Cell 1 RSRP (dBm)": "LTE (sec)ondary Serving Cell 1 RSRP (dBm)",
    "LTE Secondary Serving Cell 1 RS SINR (dB)": "LTE (sec)ondary Serving Cell 1 RS SINR (dB)",
    "LTE Secondary Serving Cell 1 RSRQ (dB)": "LTE (sec)ondary Serving Cell 1 RSRQ (dB)",
    "LTE Neighbor Cell 1 PCI": "LTE Neighbor Cell 1 PCI",
    "LTE Neighbor Cell 1 DL EARFCN": "LTE Neighbor Cell 1 DL EARFCN",
    "LTE Neighbor Cell 1 RSRP": "LTE Neighbor Cell 1 RSRP",
    "LTE Neighbor Cell 1 RSRQ": "LTE Neighbor Cell 1 RSRQ",
    "LTE Serving Cell DL Pathloss Carrier 1 (dB)": "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
    "LTE MAC DL Throughput (kbps)": "LTE MAC DL Throughput (kbps)",
    "LTE MAC DL Throughput Carrier 1 (kbps)": "LTE MAC DL Throughput Carrier 1 (kbps)",
    "LTE MAC DL Throughput Carrier 2 (kbps)": "LTE MAC DL Throughput Carrier 2 (kbps)",
    "LTE MAC DL Throughput Carrier 3 (kbps)": "LTE MAC DL Throughput Carrier 3 (kbps)",
    "LTE MAC DL Throughput Carrier 4 (kbps)": "LTE MAC DL Throughput Carrier 4 (kbps)",
    "LTE MAC UL Throughput (kbps)": "LTE MAC UL Throughput (kbps)",
    "LTE MAC UL Throughput Carrier 1 (kbps)": "LTE MAC UL Throughput Carrier 1 (kbps)",
    "LTE MAC UL Throughput Carrier 2 (kbps)": "LTE MAC UL Throughput Carrier 2 (kbps)",
    "LTE MAC UL Throughput Carrier 3 (kbps)": "LTE MAC UL Throughput Carrier 3 (kbps)",
    "LTE MAC UL Throughput Carrier 4 (kbps)": "LTE MAC UL Throughput Carrier 4 (kbps)",
    "LTE PDSCH Modulation": "LTE PDSCH Modulation",
    "LTE PDSCH MCS": "LTE PDSCH MCS",
    "LTE PDSCH BLER (%)": "LTE PDSCH BLER (%)",
    "LTE PDSCH Phy Throughput (kbps)": "LTE PDSCH Phy Throughput (kbps)",
    "LTE PDSCH Phy Throughput Total (kbps)": "LTE PDSCH Phy Throughput Total (kbps)",
    "LTE PDSCH Phy Throughput Carrier 1 (kbps)": "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 2 (kbps)": "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 3 (kbps)": "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
    "LTE PDSCH Phy Throughput Carrier 4 (kbps)": "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
    "LTE PUSCH Modulation ": "LTE PUSCH Modulation",
    "LTE PUSCH MCS ": "LTE PUSCH MCS",
    "PUSCH BLER (%)": "PUSCH BLER (%)",
    "LTE PUSCH Phy Throughput (kbps)": "LTE PUSCH Phy Throughput (kbps)",
    "LTE PUSCH Phy Throughput Total (kbps)": "LTE PUSCH Phy Throughput Total (kbps)",
    "LTE PUSCH Phy Throughput Carrier 1 (kbps)": "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 2 (kbps)": "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
    "LTE PUSCH Phy Throughput Carrier 3 (kbps)": "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
    "PUSCH Phy Throughput Carrier 4 (kbps)": "PUSCH Phy Throughput Carrier 4 (kbps)",
    "LTE RLC Throughput DL (Kbps)": "LTE RLC Throughput DL (Kbps)",
    "LTE RLC Throughput UL (Kbps)": "LTE RLC Throughput UL (Kbps)",
    "NR Serving Beam 1 Cell Identity": "NR Serving Beam 1 Cell Identity",
    "NR Serving Beam 1 NRARFCN DL": "NR Serving Beam 1 NRARFCN DL",
    "NR Serving Beam 1 Band": "NR Serving Beam 1 Band",
    "NR Serving Beam 1 Bandwidth DL": "NR Serving Beam 1 Bandwidth DL",
    "NR Serving Beam 1 Bandwidth UL": "NR Serving Beam 1 Bandwidth UL",
    "NR Serving Beam 1 SSB Index": "NR Serving Beam 1 SSB Index",
    "NR Serving Beam 1 Cell Type": "NR Serving Beam 1 Cell Type",
    "NR Serving Beam 1 GSCN": "NR Serving Beam 1 GSCN",
    "NR Serving Beam 2 Cell Identity": "NR Serving Beam 2 Cell Identity",
    "NR Serving Beam 2 NRARFCN DL": "NR Serving Beam 2 NRARFCN DL",
    "NR Serving Beam 2 Band": "NR Serving Beam 2 Band",
    "NR Serving Beam 2 Bandwidth DL": "NR Serving Beam 2 Bandwidth DL",
    "NR Serving Beam 2 Bandwidth UL": "NR Serving Beam 2 Bandwidth UL",
    "NR Serving Beam 2 SSB Index": "NR Serving Beam 2 SSB Index",
    "NR Serving Beam 2 Cell Type": "NR Serving Beam 2 Cell Type",
    "NR Serving Beam 2 GSCN": "NR Serving Beam 2 GSCN",
    "NR Serving Cell Identity Top #1": "NR Serving Cell Identity Top #1",
    "NR Serving Cell NRARFCN DL Top #1": "NR Serving Cell NRARFCN DL Top #1",
    "NR Serving Cell SS RSSI Top #1": "NR Serving Cell SS RSSI Top #1",
    "NR Serving Cell SS RSRP Top #1": "NR Serving Cell SS RSRP Top #1",
    "NR Serving Cell SS SINR Top #1": "NR Serving Cell SS SINR Top #1",
    "NR Serving Cell SS RSRQ Top #1": "NR Serving Cell SS RSRQ Top #1",
    "NR PCell SSB Serving Beam Index Top #1": "NR PCell SSB Serving Beam Index Top #1",
    "NR Neighbor Cell 1 Cell Identity": "NR Neighbor Cell 1 Cell Identity",
    "NR Neighbor Cell 1 NRARFCN": "NR Neighbor Cell 1 NRARFCN",
    "NR Neighbor Cell 1 SS RSRP (dBm)": "NR Neighbor Cell 1 SS RSRP (dBm)",
    "NR Neighbor Cell 1 SS SINR (dB)": "NR Neighbor Cell 1 SS SINR (dB)",
    "NR Neighbor Cell 1 SS RSRQ (dB)": "NR Neighbor Cell 1 SS RSRQ (dB)",
    "NR Neighbor Cell 1 Best Beam Index": "NR Neighbor Cell 1 Best Beam Index",
    "NR Neighbor Cell 1 Cell Type": "NR Neighbor Cell 1 Cell Type",
    "NR Phy Throughput Multi-RAT DL (kbps)": "NR Phy Throughput Multi-RAT DL (kbps)",
    "NR Phy Throughput Multi-RAT UL (kbps)": "NR Phy Throughput Multi-RAT UL (kbps)",
    "NR PDSCH Phy Throughput Total (Kbps)": "NR PDSCH Phy Throughput Total (Kbps)",
    "NR Pcell PDSCH Scheduled Throughput (Mbps)": "NR Pcell PDSCH Scheduled Throughput (Mbps)",
    "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PDSCH Modulation Serving Beam 1": "NR PDSCH Modulation Serving Beam 1",
    "NR PDSCH MCS Serving Beam 1": "NR PDSCH MCS Serving Beam 1",
    "NR PDSCH BLER (%) Serving Beam 1": "NR PDSCH BLER (%) Serving Beam 1",
    "NR PDSCH CQI Serving Beam 1": "NR PDSCH CQI Serving Beam 1",
    "NR PDSCH RI Serving Beam 1": "NR PDSCH RI Serving Beam 1",
    "NR DL Pathloss Serving Beam 1": "NR DL Pathloss Serving Beam 1",
    "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PDSCH Modulation Serving Beam 2": "NR PDSCH Modulation Serving Beam 2",
    "NR PDSCH MCS Serving Beam 2": "NR PDSCH MCS Serving Beam 2",
    "NR PDSCH BLER (%) Serving Beam 2": "NR PDSCH BLER (%) Serving Beam 2",
    "NR PDSCH CQI Serving Beam 2": "NR PDSCH CQI Serving Beam 2",
    "NR PDSCH RI Serving Beam 2": "NR PDSCH RI Serving Beam 2",
    "NR DL Pathloss Serving Beam 2": "NR DL Pathloss Serving Beam 2",
    "NR PUSCH Phy Throughput Total (kbps)": "NR PUSCH Phy Throughput Total (kbps)",
    "NR Pcell PUSCH Scheduled Throughput (Mbps)": "NR Pcell PUSCH Scheduled Throughput (Mbps)",
    "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
    "NR PUSCH Modulation Serving Beam 1": "NR PUSCH Modulation Serving Beam 1",
    "NR PUSCH MCS Serving Beam 1": "NR PUSCH MCS Serving Beam 1",
    "NR PUSCH BLER (%) Serving Beam 1": "NR PUSCH BLER (%) Serving Beam 1",
    "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)": "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
    "NR PUSCH Modulation Serving Beam 2": "NR PUSCH Modulation Serving Beam 2",
    "NR PUSCH MCS Serving Beam 2": "NR PUSCH MCS Serving Beam 2",
    "NR PUSCH BLER (%) Serving Beam 2": "NR PUSCH BLER (%) Serving Beam 2",
    "NR MAC DL Throughput Total (kbps)": "NR MAC DL Throughput Total (kbps)",
    "NR MAC UL Throughput Total (kbps)": "NR MAC UL Throughput Total (kbps)",
    "NR RLC DL Throughput Total (kbps)": "NR RLC DL Throughput Total (kbps)",
    "NR RLC UL Throughput Total (kbps)": "NR RLC UL Throughput Total (kbps)",
    "NR RLC DL Throughput (Kbps)": "NR RLC DL Throughput (Kbps)",
    "NR RLC UL Throughput (Kbps)": "NR RLC UL Throughput (Kbps)",
    "NR BWP Center NR-ARFCN DL Serving Beam 1": "NR BWP Center NR-ARFCN DL Serving Beam 1",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 1": "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
    "NR BWP ID DL Serving Beam 1": "NR BWP ID DL Serving Beam 1",
    "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)": "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1": "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 1": "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
    "NR BWP Subcarrier Spacing DL Serving Beam 1": "NR BWP Subcarrier Spacing DL Serving Beam 1",
    "NR BWPs Configured Count DL serving Beam 1": "NR BWPs Configured Count DL serving Beam 1",
    "NR BWP Center NR-ARFCN DL Serving Beam 2": "NR BWP Center NR-ARFCN DL Serving Beam 2",
    "NR BWP Bandwidth DL (Mhz) Serving Beam 2": "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
    "NR BWP ID DL Serving Beam 2": "NR BWP ID DL Serving Beam 2",
    "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)": "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2": "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN DL Serving Beam 2": "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
    "NR BWP Subcarrier Spacing DL Serving Beam 2": "NR BWP Subcarrier Spacing DL Serving Beam 2",
    "NR BWPs Configured Count DL serving Beam 2": "NR BWPs Configured Count DL serving Beam 2",
    "NR BWP Center NR-ARFCN UL Serving Beam 1": "NR BWP Center NR-ARFCN UL Serving Beam 1",
    "NR BWP Bandwidth UL Serving Beam 1 (Mhz)": "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
    "NR BWP ID UL Serving Beam 1": "NR BWP ID UL Serving Beam 1",
    "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)": "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1": "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 1": "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
    "NR BWP Subcarrier Spacing UL Serving Beam 1": "NR BWP Subcarrier Spacing UL Serving Beam 1",
    "NR BWPs Configured Count UL Serving Beam 1": "NR BWPs Configured Count UL Serving Beam 1",
    "NR BWP Center NR-ARFCN UL Serving Beam 2": "NR BWP Center NR-ARFCN UL Serving Beam 2",
    "NR BWP Bandwidth UL Serving Beam 2 (Mhz)": "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
    "NR BWP ID UL Serving Beam 2": "NR BWP ID UL Serving Beam 2",
    "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)": "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
    "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2": "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Start Point NR-ARFCN UL Serving Beam 2": "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
    "NR BWP Subcarrier Spacing UL Serving Beam 2": "NR BWP Subcarrier Spacing UL Serving Beam 2",
    "NR BWPs Configured Count UL Serving Beam 2": "NR BWPs Configured Count UL Serving Beam 2",
    "RadioAccessTechnologyState": "RadioAccessTechnologyState",
    "MR-DC Cell 1 SINR (dB)": "MR-DC Cell 1 SINR (dB)",
    "PDSCH Average RBs per Allocated Slot Serving Beam 1": "PDSCH Average RBs per Allocated Slot Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1": "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
    "PDSCH BWP ID Serving Beam 1": "PDSCH BWP ID Serving Beam 1",
    "PDSCH RB Allocation Count Serving Beam 1": "PDSCH RB Allocation Count Serving Beam 1",
    "PDSCH RB Allocation Count per TB Serving Beam 1": "PDSCH RB Allocation Count per TB Serving Beam 1",
    "PDSCH RB Allocation Usage Serving Beam 1 (%)": "PDSCH RB Allocation Usage Serving Beam 1 (%)",
    "PDSCH RBG Size Serving Beam 1": "PDSCH RBG Size Serving Beam 1",
    "PDSCH Slot Allocation Count Serving Beam 1": "PDSCH Slot Allocation Count Serving Beam 1",
    "PDSCH Slot Allocation Count per TB Serving Beam 1": "PDSCH Slot Allocation Count per TB Serving Beam 1",
    "PDSCH Slot Allocation TDD Serving Beam 1 (%)": "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PDSCH Slot Allocation Total Serving Beam 1 (%)": "PDSCH Slot Allocation Total Serving Beam 1 (%)",
    "PDSCH Slot Utilization Serving Beam 1 (%)": "PDSCH Slot Utilization Serving Beam 1 (%)",
    "PDSCH RB Dist Current Count Serving Beam 1": "PDSCH RB Dist Current Count Serving Beam 1",
    "PDSCH RB Utillization Dist Current Count Serving Beam 1": "PDSCH RB Utillization Dist Current Count Serving Beam 1",
    "PDSCH Average RBs per Allocated Slot Serving Beam 2": "PDSCH Average RBs per Allocated Slot Serving Beam 2",
    "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2": "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
    "PDSCH BWP ID Serving Beam 2": "PDSCH BWP ID Serving Beam 2",
    "PDSCH RB Allocation Count Serving Beam 2": "PDSCH RB Allocation Count Serving Beam 2",
    "PDSCH RB Allocation Count per TB Serving Beam 2": "PDSCH RB Allocation Count per TB Serving Beam 2",
    "PDSCH RB Allocation Usage Serving Beam 2 (%)": "PDSCH RB Allocation Usage Serving Beam 2 (%)",
    "PDSCH RBG Size Serving Beam 2": "PDSCH RBG Size Serving Beam 2",
    "PDSCH Slot Allocation Count Serving Beam 2": "PDSCH Slot Allocation Count Serving Beam 2",
    "PDSCH Slot Allocation Count per TB Serving Beam 2": "PDSCH Slot Allocation Count per TB Serving Beam 2",
    "PDSCH Slot Allocation TDD Serving Beam 2 (%)": "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PDSCH Slot Allocation Total Serving Beam 2 (%)": "PDSCH Slot Allocation Total Serving Beam 2 (%)",
    "PDSCH Slot Utilization Serving Beam 2 (%)": "PDSCH Slot Utilization Serving Beam 2 (%)",
    "PDSCH RB Dist Current Count Serving Beam 2": "PDSCH RB Dist Current Count Serving Beam 2",
    "PDSCH RB Utillization Dist Current Count Serving Beam 2": "PDSCH RB Utillization Dist Current Count Serving Beam 2",
    "PUSCH Average RBs per Allocated Slot Serving Beam 1": "PUSCH Average RBs per Allocated Slot Serving Beam 1",
    "PUSCH BWP ID Serving Beam 1": "PUSCH BWP ID Serving Beam 1",
    "PUSCH RB Allocation Count Serving Beam 1": "PUSCH RB Allocation Count Serving Beam 1",
    "PUSCH RB Allocation Usage Serving Beam 1 (%)": "PUSCH RB Allocation Usage Serving Beam 1 (%)",
    "PUSCH RBG Size Serving Beam 1": "PUSCH RBG Size Serving Beam 1",
    "PUSCH Slot Allocation Count Serving Beam 1": "PUSCH Slot Allocation Count Serving Beam 1",
    "PUSCH Slot Allocation TDD Serving Beam 1 (%)": "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
    "PUSCH Slot Allocation Total Serving Beam 1 (%)": "PUSCH Slot Allocation Total Serving Beam 1 (%)",
    "PUSCH Slot Utilization Serving Beam 1 (%)": "PUSCH Slot Utilization Serving Beam 1 (%)",
    "PUSCH RB Dist Current Count Serving Beam 1": "PUSCH RB Dist Current Count Serving Beam 1",
    "PUSCH RB Utillization Dist Current Count Serving Beam 1": "PUSCH RB Utillization Dist Current Count Serving Beam 1",
    "PUSCH Average RBs per Allocated Slot Serving Beam 2": "PUSCH Average RBs per Allocated Slot Serving Beam 2",
    "PUSCH BWP ID Serving Beam 2": "PUSCH BWP ID Serving Beam 2",
    "PUSCH RB Allocation Count Serving Beam 2": "PUSCH RB Allocation Count Serving Beam 2",
    "PUSCH RB Allocation Usage Serving Beam 2 (%)": "PUSCH RB Allocation Usage Serving Beam 2 (%)",
    "PUSCH RBG Size Serving Beam 2": "PUSCH RBG Size Serving Beam 2",
    "PUSCH Slot Allocation Count Serving Beam 2": "PUSCH Slot Allocation Count Serving Beam 2",
    "PUSCH Slot Allocation TDD Serving Beam 2 (%)": "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
    "PUSCH Slot Allocation Total Serving Beam 2 (%)": "PUSCH Slot Allocation Total Serving Beam 2 (%)",
    "PUSCH Slot Utilization Serving Beam 2 (%)": "PUSCH Slot Utilization Serving Beam 2 (%)",
    "PUSCH RB Dist Current Count Serving Beam 2": "PUSCH RB Dist Current Count Serving Beam 2",
    "PUSCH RB Utillization Dist Current Count Serving Beam 2": "PUSCH RB Utillization Dist Current Count Serving Beam 2",
    "Radio Common Throughput DL (kbps)": "Radio Common Throughput DL (kbps)",
    "LTE Bearer Maximum Bitrate DL (kbit/s)": "LTE Bearer Maximum Bitrate DL (kbit/s)",
    "LTE PDN Connection AMBR DL (kbps)": "LTE PDN Connection AMBR DL (kbps)",
    "FirmwareVersion": "FirmwareVersion",
    "Qualifier": "Qualifier",


}
df.rename(columns=master_rename_map, inplace=True)



# === Step 3: Define schema groups
schema_groups = {
    "Streaming": [
        "Date",
        "Time",
        "Test Name",
        "Sequence",
        "Logfile Name",
        "Route Name",
        "Operator",
        "MNC",
        "IMSI",
        "Type of Mobility",
        "Session Start Time",
        "Latitude",
        "Longitude",
        "Session Start Technology",
        "Session Start Data Radio Bearer",
        "Session Start MultiRAT",
        "Session Start TAC",
        "Streaming Device",
        "Streaming Operator",
        "Streaming URL",
        "Streaming Outcome Type",
        "Aborted by User Status",
        "Streaming Completion Rate",
        "Streaming Setup Success Rate",
        "Streaming Success Rate",
        "Streaming Data Radio Bearer",
        "Streaming Service Bearer",
        "Streaming Session Identity",
        "Streaming Session Time",
        "Streaming Session Failure Ratio",
        "Streaming Number Of Video Session Interruptions",
        "Streaming Total Duration Of Video Session Interruptions",
        "Streaming Maximum Duration Of Video Session Interruptions",
        "Streaming Session Without Interruption Rate",
        "Streaming Duration",
        "Seconds Start to End Streaming",
        "Streaming HD Resolution",
        "Streaming HD Resolution Ratio",
        "Streaming Average Session Resolution",
        "Streaming Average Throughput",
        "Streaming Throughput Avg",
        "Streaming Throughput Filtered",
        "Streaming Player Download Data Transfer Time",
        "Streaming Player IP Service Access Time",
        "Streaming Player Session Time",
        "Streaming Probe Name",
        "Streaming Probe Version",
        "Streaming Reproduction Start Delay",
        "Streaming ResolutionAvg",
        "Streaming ServiceStatus",
        "Streaming ServiceAccessTime",
        "Streaming Service Access Time (ms)",
        "Streaming Service Access Time (sec)",
        "Streaming Service Non Accessibility",
        "Streaming Interruption Duration Total",
        "Streaming Interruption Duration Max",
        "Streaming State Event Source Time",
        "Streaming State Prebuffering to Reproducing Delay",
        "Streaming State Request to Prebuffering Delay",
        "Streaming State Request to Reproducing Delay",
        "Streaming State Buffering Complete Time",
        "Streaming State Done Time",
        "Streaming State Player Download End Time",
        "Streaming State Player Download Start Time",
        "Streaming State Player Request Time",
        "Streaming State Prebuffering Time",
        "Streaming State Rebuffering Time",
        "Streaming State Reproducing Time",
        "Streaming State Video Request Time",
        "Streaming Time To First Byte (TTFB)",
        "Streaming Video Interruption Count",
        "Streaming Video IP Service Access Time",
        "Streaming Video Play Start Time",
        "Streaming Video Session Time",
        "Streaming Video IP Service Access Time (ms)",
        "Streaming Video IP Service Access Time (sec)",
        "Streaming Video Play Start Failure Ratio",
        "Streaming Video Play Start Time (sec)",
        "Streaming Video Session Cutoff Ratio",
        "Streaming Video Session Failure Ratio",
        "Streaming Video Session Success Ratio",
        "Streaming Video Session Time (sec)",
        "Streaming Reproduction Cutoff Ratio",
        "Streaming Reproduction Start Delay (sec)",
        "Streaming Reproduction Start Failure Ratio",
        "Streaming Impairment Free",
        "Streaming Impairment Free Video Session Ratio",
        "Streaming Start RAT",
        "Streaming End RAT",
        "Play Request to 1st Picture",
        "Session End Time",
        "Session End MultiRAT",
        "Session End Latitude",
        "Session End Longitude",
        "LTE Cell Identity(eNB Part)",
        "LTE Cell Identity(Cell Part)",
        "LTE Serving Cell Identity",
        "LTE Serving Cell DL EARFCN",
        "LTE Serving Cell Frequency Band",
        "LTE Serving Cell Channel RSSI(dBm)",
        "LTE Serving Cell RSRP(dBm)",
        "LTE Serving Cell RS SINR(dB)",
        "LTE Serving Cell RSRQ (dB)",
        "LTE_Serving_Cell_Count_Average",
        "LTE (sec)ondary Serving Cell 1 Identity",
        "LTE (sec)ondary Serving Cell 1 DL EARFCN",
        "LTE (sec)ondary Serving Cell 1 Frequency Band",
        "LTE (sec)ondary Serving Cell 1 Channel RSSI (dBm)",
        "LTE (sec)ondary Serving Cell 1 RSRP (dBm)",
        "LTE (sec)ondary Serving Cell 1 RS SINR (dB)",
        "LTE (sec)ondary Serving Cell 1 RSRQ (dB)",
        "LTE Neighbor Cell 1 PCI",
        "LTE Neighbor Cell 1 DL EARFCN",
        "LTE Neighbor Cell 1 RSRP",
        "LTE Neighbor Cell 1 RSRQ",
        "LTE Serving Cell DL Pathloss Carrier 1 (dB)",
        "LTE MAC DL Throughput (kbps)",
        "LTE MAC DL Throughput Carrier 1 (kbps)",
        "LTE MAC DL Throughput Carrier 2 (kbps)",
        "LTE MAC DL Throughput Carrier 3 (kbps)",
        "LTE MAC DL Throughput Carrier 4 (kbps)",
        "LTE MAC UL Throughput (kbps)",
        "LTE MAC UL Throughput Carrier 1 (kbps)",
        "LTE MAC UL Throughput Carrier 2 (kbps)",
        "LTE MAC UL Throughput Carrier 3 (kbps)",
        "LTE MAC UL Throughput Carrier 4 (kbps)",
        "LTE PDSCH Modulation",
        "LTE PDSCH MCS",
        "LTE PDSCH BLER (%)",
        "LTE PDSCH Phy Throughput (kbps)",
        "LTE PDSCH Phy Throughput Total (kbps)",
        "LTE PDSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 3 (kbps)",
        "LTE PDSCH Phy Throughput Carrier 4 (kbps)",
        "LTE PUSCH Modulation",
        "LTE PUSCH MCS",
        "PUSCH BLER (%)",
        "LTE PUSCH Phy Throughput (kbps)",
        "LTE PUSCH Phy Throughput Total (kbps)",
        "LTE PUSCH Phy Throughput Carrier 1 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 2 (kbps)",
        "LTE PUSCH Phy Throughput Carrier 3 (kbps)",
        "PUSCH Phy Throughput Carrier 4 (kbps)",
        "LTE RLC Throughput DL (Kbps)",
        "LTE RLC Throughput UL (Kbps)",
        "LTE Bearer Maximum Bitrate DL (kbit/s)",
        "LTE PDN Connection AMBR DL (kbps)",
        "NR Serving Beam 1 Cell Identity",
        "NR Serving Beam 1 NRARFCN DL",
        "NR Serving Beam 1 Band",
        "NR Serving Beam 1 Bandwidth DL",
        "NR Serving Beam 1 Bandwidth UL",
        "NR Serving Beam 1 SSB Index",
        "NR Serving Beam 1 Cell Type",
        "NR Serving Beam 1 GSCN",
        "NR Serving Beam 2 Cell Identity",
        "NR Serving Beam 2 NRARFCN DL",
        "NR Serving Beam 2 Band",
        "NR Serving Beam 2 Bandwidth DL",
        "NR Serving Beam 2 Bandwidth UL",
        "NR Serving Beam 2 SSB Index",
        "NR Serving Beam 2 Cell Type",
        "NR Serving Beam 2 GSCN",
        "NR Serving Cell Identity Top #1",
        "NR Serving Cell NRARFCN DL Top #1",
        "NR Serving Cell SS RSSI Top #1",
        "NR Serving Cell SS RSRP Top #1",
        "NR Serving Cell SS SINR Top #1",
        "NR Serving Cell SS RSRQ Top #1",
        "NR PCell SSB Serving Beam Index Top #1",
        "NR Neighbor Cell 1 Cell Identity",
        "NR Neighbor Cell 1 NRARFCN",
        "NR Neighbor Cell 1 SS RSRP (dBm)",
        "NR Neighbor Cell 1 SS SINR (dB)",
        "NR Neighbor Cell 1 SS RSRQ (dB)",
        "NR Neighbor Cell 1 Best Beam Index",
        "NR Neighbor Cell 1 Cell Type",
        "NR Phy Throughput Multi-RAT DL (kbps)",
        "NR Phy Throughput Multi-RAT UL (kbps)",
        "NR PDSCH Phy Throughput Total (Kbps)",
        "NR Pcell PDSCH Scheduled Throughput (Mbps)",
        "NR PDSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PDSCH Modulation Serving Beam 1",
        "NR PDSCH MCS Serving Beam 1",
        "NR PDSCH BLER (%) Serving Beam 1",
        "NR PDSCH CQI Serving Beam 1",
        "NR PDSCH RI Serving Beam 1",
        "NR DL Pathloss Serving Beam 1",
        "NR PDSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PDSCH Modulation Serving Beam 2",
        "NR PDSCH MCS Serving Beam 2",
        "NR PDSCH BLER (%) Serving Beam 2",
        "NR PDSCH CQI Serving Beam 2",
        "NR PDSCH RI Serving Beam 2",
        "NR DL Pathloss Serving Beam 2",
        "NR PUSCH Phy Throughput Total (kbps)",
        "NR Pcell PUSCH Scheduled Throughput (Mbps)",
        "NR PUSCH Phy Throughput Serving Beam 1 (Kbps)",
        "NR PUSCH Modulation Serving Beam 1",
        "NR PUSCH MCS Serving Beam 1",
        "NR PUSCH BLER (%) Serving Beam 1",
        "NR PUSCH Phy Throughput Serving Beam 2 (Kbps)",
        "NR PUSCH Modulation Serving Beam 2",
        "NR PUSCH MCS Serving Beam 2",
        "NR PUSCH BLER (%) Serving Beam 2",
        "NR MAC DL Throughput Total (kbps)",
        "NR MAC UL Throughput Total (kbps)",
        "NR RLC DL Throughput Total (kbps)",
        "NR RLC UL Throughput Total (kbps)",
        "NR RLC DL Throughput (Kbps)",
        "NR RLC UL Throughput (Kbps)",
        "NR BWP Center NR-ARFCN DL Serving Beam 1",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 1",
        "NR BWP ID DL Serving Beam 1",
        "NR BWP Initial Bandwidth DL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 1",
        "NR BWP Subcarrier Spacing DL Serving Beam 1",
        "NR BWPs Configured Count DL serving Beam 1",
        "NR BWP Center NR-ARFCN DL Serving Beam 2",
        "NR BWP Bandwidth DL (Mhz) Serving Beam 2",
        "NR BWP ID DL Serving Beam 2",
        "NR BWP Initial Bandwidth DL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN DL Serving Beam 2",
        "NR BWP Subcarrier Spacing DL Serving Beam 2",
        "NR BWPs Configured Count DL serving Beam 2",
        "NR BWP Center NR-ARFCN UL Serving Beam 1",
        "NR BWP Bandwidth UL Serving Beam 1 (Mhz)",
        "NR BWP ID UL Serving Beam 1",
        "NR BWP Initial Bandwidth UL Serving Beam 1 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 1",
        "NR BWP Subcarrier Spacing UL Serving Beam 1",
        "NR BWPs Configured Count UL Serving Beam 1",
        "NR BWP Center NR-ARFCN UL Serving Beam 2",
        "NR BWP Bandwidth UL Serving Beam 2 (Mhz)",
        "NR BWP ID UL Serving Beam 2",
        "NR BWP Initial Bandwidth UL Serving Beam 2 (MHz)",
        "NR BWP Initial Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Start Point NR-ARFCN UL Serving Beam 2",
        "NR BWP Subcarrier Spacing UL Serving Beam 2",
        "NR BWPs Configured Count UL Serving Beam 2",
        "RadioAccessTechnologyState",
        "MR-DC Cell 1 SINR (dB)",
        "PDSCH Average RBs per Allocated Slot Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 1",
        "PDSCH BWP ID Serving Beam 1",
        "PDSCH RB Allocation Count Serving Beam 1",
        "PDSCH RB Allocation Count per TB Serving Beam 1",
        "PDSCH RB Allocation Usage Serving Beam 1 (%)",
        "PDSCH RBG Size Serving Beam 1",
        "PDSCH Slot Allocation Count Serving Beam 1",
        "PDSCH Slot Allocation Count per TB Serving Beam 1",
        "PDSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PDSCH Slot Allocation Total Serving Beam 1 (%)",
        "PDSCH Slot Utilization Serving Beam 1 (%)",
        "PDSCH RB Dist Current Count Serving Beam 1",
        "PDSCH RB Utillization Dist Current Count Serving Beam 1",
        "PDSCH Average RBs per Allocated Slot Serving Beam 2",
        "PDSCH Average RBs per Allocated Slot per TB Serving Beam 2",
        "PDSCH BWP ID Serving Beam 2",
        "PDSCH RB Allocation Count Serving Beam 2",
        "PDSCH RB Allocation Count per TB Serving Beam 2",
        "PDSCH RB Allocation Usage Serving Beam 2 (%)",
        "PDSCH RBG Size Serving Beam 2",
        "PDSCH Slot Allocation Count Serving Beam 2",
        "PDSCH Slot Allocation Count per TB Serving Beam 2",
        "PDSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PDSCH Slot Allocation Total Serving Beam 2 (%)",
        "PDSCH Slot Utilization Serving Beam 2 (%)",
        "PDSCH RB Dist Current Count Serving Beam 2",
        "PDSCH RB Utillization Dist Current Count Serving Beam 2",
        "PUSCH Average RBs per Allocated Slot Serving Beam 1",
        "PUSCH BWP ID Serving Beam 1",
        "PUSCH RB Allocation Count Serving Beam 1",
        "PUSCH RB Allocation Usage Serving Beam 1 (%)",
        "PUSCH RBG Size Serving Beam 1",
        "PUSCH Slot Allocation Count Serving Beam 1",
        "PUSCH Slot Allocation TDD Serving Beam 1 (%)",
        "PUSCH Slot Allocation Total Serving Beam 1 (%)",
        "PUSCH Slot Utilization Serving Beam 1 (%)",
        "PUSCH RB Dist Current Count Serving Beam 1",
        "PUSCH RB Utillization Dist Current Count Serving Beam 1",
        "PUSCH Average RBs per Allocated Slot Serving Beam 2",
        "PUSCH BWP ID Serving Beam 2",
        "PUSCH RB Allocation Count Serving Beam 2",
        "PUSCH RB Allocation Usage Serving Beam 2 (%)",
        "PUSCH RBG Size Serving Beam 2",
        "PUSCH Slot Allocation Count Serving Beam 2",
        "PUSCH Slot Allocation TDD Serving Beam 2 (%)",
        "PUSCH Slot Allocation Total Serving Beam 2 (%)",
        "PUSCH Slot Utilization Serving Beam 2 (%)",
        "PUSCH RB Dist Current Count Serving Beam 2",
        "PUSCH RB Utillization Dist Current Count Serving Beam 2",
        "Radio Common Throughput DL (kbps)",
        "FirmwareVersion",
        "Qualifier"

 

   ]
}

# === Step 4: Map each test name to schema group
testname_to_group = {
    "YoutubeVOD": "Streaming",
    "YoutubeLIVE": "Streaming"
    
    
}



# === Function to generate Test_IDs column ===
def generate_test_ids(df):
    test_name_codes = {
        "HTTP FDFS DL": 5,
        "HTTP FDFS UL": 6,
        "HTTP FDTT DL": 7,
        "HTTP FDTT UL": 8,
        "HTTP BROWSING LIVE": 9,
        "HTTP BROSWING STATIC": 10,
        "YoutubeVOD": 11,
        "YoutubeLIVE": 11

    }

    operator_codes = {
        "Vodafone DE": 1,
        "Telefonica DE": 2,
        "Deutsche Telekom": 3
    }

    df = df.copy()
    df["Test_IDs"] = None

    for (test_name, operator), group in df.groupby(["Test Name", "Operator"]):
        test_code = test_name_codes.get(test_name, 0)
        operator_code = operator_codes.get(operator, 0)

        for i, idx in enumerate(group.index, start=1):
            seq = f"{i:04d}"
            df.at[idx, "Test_IDs"] = f"{test_code}{operator_code}{seq}"

    return df

df = generate_test_ids(df)



# === Step 5: Setup output & log
output_dir = Path("/mnt/c/Users/User/Documents/Indra/geo/CDR/parsing/split/Streaming/Output2")
output_dir.mkdir(exist_ok=True)
log_path = output_dir / "log.txt"


# === Step 6: Export all operators into one Excel file with different sheets


first_row = df.iloc[0]
raw_date = pd.to_datetime(first_row.get("Date", pd.NaT), errors='coerce')
date_str = raw_date.strftime("%Y%m%d") if not pd.isna(raw_date) else "UnknownDate"
country = str(first_row.get("Route Name", "UnknownCountry")).replace(" ", "_")
test_name = str(first_row.get("Test Name", "UnknownTest")).replace("/", "-").replace("\\", "-").replace(":", "-").replace(" ", "_")


group_key = testname_to_group.get(test_name)
if not group_key:
    group_key = "Streaming"  

selected_columns = schema_groups[group_key] + ["Test_IDs"]

if "Test_IDs" in selected_columns:
    selected_columns.remove("Test_IDs")
    selected_columns.insert(2, "Test_IDs")

output_file_name = f"{date_str}_{country}_BM_CDRData_Streaming.xlsx"
file_path = output_dir / output_file_name
filtered_df = df[selected_columns]
# === Save to one Excel file with sheets per operator
with pd.ExcelWriter(file_path, engine="xlsxwriter") as writer:
    filtered_df.to_excel(writer, sheet_name="AllData", index=False)

# === Log
msg = f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] ✅ Saved: {output_file_name} with all operators in Single sheets"
print(msg)
with open(log_path, "a") as log_file:
    log_file.write(msg + "\n")

